// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteInternalIngestionRunsByRunIdData, DeleteInternalIngestionRunsByRunIdErrors, DeleteInternalIngestionRunsByRunIdResponses, GetInternalBasketCacheHealthData, GetInternalBasketCacheHealthErrors, GetInternalBasketCacheHealthResponses, GetInternalIngestionRunsByRunIdData, GetInternalIngestionRunsByRunIdErrors, GetInternalIngestionRunsByRunIdErrorsData, GetInternalIngestionRunsByRunIdErrorsErrors, GetInternalIngestionRunsByRunIdErrorsResponses, GetInternalIngestionRunsByRunIdFilesData, GetInternalIngestionRunsByRunIdFilesErrors, GetInternalIngestionRunsByRunIdFilesResponses, GetInternalIngestionRunsByRunIdResponses, GetInternalIngestionRunsData, GetInternalIngestionRunsErrors, GetInternalIngestionRunsResponses, GetInternalIngestionStatsData, GetInternalIngestionStatsErrors, GetInternalIngestionStatsResponses, GetInternalItemsSearchData, GetInternalItemsSearchErrors, GetInternalItemsSearchResponses, GetInternalPricesByChainSlugByStoreIdData, GetInternalPricesByChainSlugByStoreIdErrors, GetInternalPricesByChainSlugByStoreIdResponses, PostInternalBasketCacheRefreshByChainSlugData, PostInternalBasketCacheRefreshByChainSlugErrors, PostInternalBasketCacheRefreshByChainSlugResponses, PostInternalBasketCacheWarmupData, PostInternalBasketCacheWarmupErrors, PostInternalBasketCacheWarmupResponses, PostInternalBasketOptimizeMultiData, PostInternalBasketOptimizeMultiErrors, PostInternalBasketOptimizeMultiResponses, PostInternalBasketOptimizeSingleData, PostInternalBasketOptimizeSingleErrors, PostInternalBasketOptimizeSingleResponses, PostInternalIngestionRunsByRunIdRerunData, PostInternalIngestionRunsByRunIdRerunErrors, PostInternalIngestionRunsByRunIdRerunResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get cache health
 *
 * Returns the health status and freshness information for all cached chains
 */
export const getInternalBasketCacheHealth = <ThrowOnError extends boolean = false>(options?: Options<GetInternalBasketCacheHealthData, ThrowOnError>) => (options?.client ?? client).get<GetInternalBasketCacheHealthResponses, GetInternalBasketCacheHealthErrors, ThrowOnError>({ url: '/internal/basket/cache/health', ...options });

/**
 * Refresh chain cache
 *
 * Refreshes the price cache for a specific chain
 */
export const postInternalBasketCacheRefreshByChainSlug = <ThrowOnError extends boolean = false>(options: Options<PostInternalBasketCacheRefreshByChainSlugData, ThrowOnError>) => (options.client ?? client).post<PostInternalBasketCacheRefreshByChainSlugResponses, PostInternalBasketCacheRefreshByChainSlugErrors, ThrowOnError>({ url: '/internal/basket/cache/refresh/{chainSlug}', ...options });

/**
 * Warm up price cache
 *
 * Triggers a full cache warmup for all chains
 */
export const postInternalBasketCacheWarmup = <ThrowOnError extends boolean = false>(options?: Options<PostInternalBasketCacheWarmupData, ThrowOnError>) => (options?.client ?? client).post<PostInternalBasketCacheWarmupResponses, PostInternalBasketCacheWarmupErrors, ThrowOnError>({ url: '/internal/basket/cache/warmup', ...options });

/**
 * Optimize basket across multiple stores
 *
 * Finds the optimal distribution of basket items across multiple stores
 */
export const postInternalBasketOptimizeMulti = <ThrowOnError extends boolean = false>(options: Options<PostInternalBasketOptimizeMultiData, ThrowOnError>) => (options.client ?? client).post<PostInternalBasketOptimizeMultiResponses, PostInternalBasketOptimizeMultiErrors, ThrowOnError>({
    url: '/internal/basket/optimize/multi',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Optimize basket for single store
 *
 * Finds the best single store for a basket of items based on price and coverage
 */
export const postInternalBasketOptimizeSingle = <ThrowOnError extends boolean = false>(options: Options<PostInternalBasketOptimizeSingleData, ThrowOnError>) => (options.client ?? client).post<PostInternalBasketOptimizeSingleResponses, PostInternalBasketOptimizeSingleErrors, ThrowOnError>({
    url: '/internal/basket/optimize/single',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List ingestion runs
 *
 * Returns a paginated list of ingestion runs with optional chain and status filters
 */
export const getInternalIngestionRuns = <ThrowOnError extends boolean = false>(options?: Options<GetInternalIngestionRunsData, ThrowOnError>) => (options?.client ?? client).get<GetInternalIngestionRunsResponses, GetInternalIngestionRunsErrors, ThrowOnError>({ url: '/internal/ingestion/runs', ...options });

/**
 * Delete ingestion run
 *
 * Deletes an ingestion run and all its associated files and errors
 */
export const deleteInternalIngestionRunsByRunId = <ThrowOnError extends boolean = false>(options: Options<DeleteInternalIngestionRunsByRunIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteInternalIngestionRunsByRunIdResponses, DeleteInternalIngestionRunsByRunIdErrors, ThrowOnError>({ url: '/internal/ingestion/runs/{runId}', ...options });

/**
 * Get ingestion run
 *
 * Returns a single ingestion run by its ID
 */
export const getInternalIngestionRunsByRunId = <ThrowOnError extends boolean = false>(options: Options<GetInternalIngestionRunsByRunIdData, ThrowOnError>) => (options.client ?? client).get<GetInternalIngestionRunsByRunIdResponses, GetInternalIngestionRunsByRunIdErrors, ThrowOnError>({ url: '/internal/ingestion/runs/{runId}', ...options });

/**
 * List ingestion errors
 *
 * Returns a paginated list of errors for a specific ingestion run
 */
export const getInternalIngestionRunsByRunIdErrors = <ThrowOnError extends boolean = false>(options: Options<GetInternalIngestionRunsByRunIdErrorsData, ThrowOnError>) => (options.client ?? client).get<GetInternalIngestionRunsByRunIdErrorsResponses, GetInternalIngestionRunsByRunIdErrorsErrors, ThrowOnError>({ url: '/internal/ingestion/runs/{runId}/errors', ...options });

/**
 * List ingestion files
 *
 * Returns a paginated list of files for a specific ingestion run
 */
export const getInternalIngestionRunsByRunIdFiles = <ThrowOnError extends boolean = false>(options: Options<GetInternalIngestionRunsByRunIdFilesData, ThrowOnError>) => (options.client ?? client).get<GetInternalIngestionRunsByRunIdFilesResponses, GetInternalIngestionRunsByRunIdFilesErrors, ThrowOnError>({ url: '/internal/ingestion/runs/{runId}/files', ...options });

/**
 * Rerun ingestion
 *
 * Creates a new run that reruns a specific file, chunk, or entry from an existing run
 */
export const postInternalIngestionRunsByRunIdRerun = <ThrowOnError extends boolean = false>(options: Options<PostInternalIngestionRunsByRunIdRerunData, ThrowOnError>) => (options.client ?? client).post<PostInternalIngestionRunsByRunIdRerunResponses, PostInternalIngestionRunsByRunIdRerunErrors, ThrowOnError>({
    url: '/internal/ingestion/runs/{runId}/rerun',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get ingestion stats
 *
 * Returns aggregated statistics for ingestion runs within a time range (24h/7d/30d buckets)
 */
export const getInternalIngestionStats = <ThrowOnError extends boolean = false>(options: Options<GetInternalIngestionStatsData, ThrowOnError>) => (options.client ?? client).get<GetInternalIngestionStatsResponses, GetInternalIngestionStatsErrors, ThrowOnError>({ url: '/internal/ingestion/stats', ...options });

/**
 * Search items
 *
 * Search for items by name with optional chain filter. Requires minimum 3 characters.
 */
export const getInternalItemsSearch = <ThrowOnError extends boolean = false>(options: Options<GetInternalItemsSearchData, ThrowOnError>) => (options.client ?? client).get<GetInternalItemsSearchResponses, GetInternalItemsSearchErrors, ThrowOnError>({ url: '/internal/items/search', ...options });

/**
 * Get store prices
 *
 * Returns paginated prices for a specific store in a chain
 */
export const getInternalPricesByChainSlugByStoreId = <ThrowOnError extends boolean = false>(options: Options<GetInternalPricesByChainSlugByStoreIdData, ThrowOnError>) => (options.client ?? client).get<GetInternalPricesByChainSlugByStoreIdResponses, GetInternalPricesByChainSlugByStoreIdErrors, ThrowOnError>({ url: '/internal/prices/{chainSlug}/{storeId}', ...options });
