// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/internal` | (string & {});
};

export type HandlersBasketItem = {
    itemId: string;
    name: string;
    quantity: number;
};

export type HandlersGetStatsResponse = {
    buckets?: Array<HandlersStatsBucket>;
};

export type HandlersGetStorePricesResponse = {
    prices?: Array<HandlersStorePrice>;
    total?: number;
};

export type HandlersIngestionError = {
    chunkId?: string;
    createdAt?: string;
    entryId?: string;
    errorDetails?: string;
    errorMessage?: string;
    errorType?: string;
    fileId?: string;
    id?: string;
    runId?: string;
    severity?: string;
};

export type HandlersIngestionFile = {
    chunkSize?: number;
    createdAt?: string;
    entryCount?: number;
    fileHash?: string;
    fileSize?: number;
    fileType?: string;
    filename?: string;
    id?: string;
    metadata?: string;
    processedAt?: string;
    processedChunks?: number;
    runId?: string;
    status?: string;
    totalChunks?: number;
};

export type HandlersIngestionRun = {
    chainSlug?: string;
    completedAt?: string;
    createdAt?: string;
    errorCount?: number;
    id?: string;
    metadata?: string;
    processedEntries?: number;
    processedFiles?: number;
    source?: string;
    startedAt?: string;
    status?: string;
    totalEntries?: number;
    totalFiles?: number;
};

export type HandlersItemPriceInfo = {
    basePrice?: number;
    discountPrice?: number;
    effectivePrice?: number;
    hasDiscount?: boolean;
    itemId?: string;
    itemName?: string;
    lineTotal?: number;
    quantity?: number;
};

export type HandlersListErrorsResponse = {
    errors?: Array<HandlersIngestionError>;
    total?: number;
};

export type HandlersListFilesResponse = {
    files?: Array<HandlersIngestionFile>;
    total?: number;
};

export type HandlersListRunsResponse = {
    runs?: Array<HandlersIngestionRun>;
    total?: number;
};

export type HandlersLocation = {
    latitude: number;
    longitude: number;
};

export type HandlersMissingItem = {
    isOptional?: boolean;
    itemId?: string;
    itemName?: string;
    penalty?: number;
};

export type HandlersMultiStoreResult = {
    algorithmUsed?: string;
    combinedTotal?: number;
    coverageRatio?: number;
    stores?: Array<HandlersStoreAllocation>;
    unassignedItems?: Array<HandlersMissingItem>;
};

export type HandlersOptimizeRequest = {
    basketItems: Array<HandlersBasketItem>;
    chainSlug: string;
    location?: HandlersLocation;
    maxDistance?: number;
    maxStores?: number;
};

export type HandlersRerunRunRequest = {
    /**
     * "file", "chunk", "entry"
     */
    rerunType: string;
    /**
     * ID of file/chunk/entry to rerun
     */
    targetId: string;
};

export type HandlersSearchItem = {
    /**
     * Average price across stores
     */
    avgPrice?: number;
    brand?: string;
    category?: string;
    chainSlug?: string;
    description?: string;
    externalId?: string;
    id?: string;
    imageUrl?: string;
    name?: string;
    /**
     * Number of stores with this item
     */
    storeCount?: number;
    subcategory?: string;
    unit?: string;
    unitQuantity?: string;
};

export type HandlersSearchItemsResponse = {
    items?: Array<HandlersSearchItem>;
    query?: string;
    total?: number;
};

export type HandlersStatsBucket = {
    completed?: number;
    failed?: number;
    /**
     * "24h", "7d", "30d"
     */
    label?: string;
    pending?: number;
    running?: number;
    totalErrors?: number;
    totalFiles?: number;
    totalRuns?: number;
};

export type HandlersStoreAllocation = {
    distance?: number;
    items?: Array<HandlersItemPriceInfo>;
    storeId?: string;
    storeTotal?: number;
    visitOrder?: number;
};

export type HandlersStorePrice = {
    anchorPrice?: number;
    brand?: string;
    currentPrice?: number;
    discountEnd?: string;
    discountPrice?: number;
    discountStart?: string;
    inStock?: boolean;
    itemExternalId?: string;
    itemName?: string;
    lastSeenAt?: string;
    lowestPrice30d?: number;
    previousPrice?: number;
    priceSignature?: string;
    retailerItemId?: string;
    unit?: string;
    unitPrice?: number;
    unitPriceBaseQuantity?: string;
    unitPriceBaseUnit?: string;
    unitQuantity?: string;
};

export type GetInternalBasketCacheHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/internal/basket/cache/health';
};

export type GetInternalBasketCacheHealthErrors = {
    /**
     * Cache not initialized
     */
    503: {
        [key: string]: string;
    };
};

export type GetInternalBasketCacheHealthError = GetInternalBasketCacheHealthErrors[keyof GetInternalBasketCacheHealthErrors];

export type GetInternalBasketCacheHealthResponses = {
    /**
     * Cache health status
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetInternalBasketCacheHealthResponse = GetInternalBasketCacheHealthResponses[keyof GetInternalBasketCacheHealthResponses];

export type PostInternalBasketCacheRefreshByChainSlugData = {
    body?: never;
    path: {
        /**
         * Chain slug identifier
         */
        chainSlug: string;
    };
    query?: never;
    url: '/internal/basket/cache/refresh/{chainSlug}';
};

export type PostInternalBasketCacheRefreshByChainSlugErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
    /**
     * Cache not initialized
     */
    503: {
        [key: string]: string;
    };
};

export type PostInternalBasketCacheRefreshByChainSlugError = PostInternalBasketCacheRefreshByChainSlugErrors[keyof PostInternalBasketCacheRefreshByChainSlugErrors];

export type PostInternalBasketCacheRefreshByChainSlugResponses = {
    /**
     * Cache refreshed
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostInternalBasketCacheRefreshByChainSlugResponse = PostInternalBasketCacheRefreshByChainSlugResponses[keyof PostInternalBasketCacheRefreshByChainSlugResponses];

export type PostInternalBasketCacheWarmupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/internal/basket/cache/warmup';
};

export type PostInternalBasketCacheWarmupErrors = {
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
    /**
     * Cache not initialized
     */
    503: {
        [key: string]: string;
    };
};

export type PostInternalBasketCacheWarmupError = PostInternalBasketCacheWarmupErrors[keyof PostInternalBasketCacheWarmupErrors];

export type PostInternalBasketCacheWarmupResponses = {
    /**
     * Cache warmed up
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostInternalBasketCacheWarmupResponse = PostInternalBasketCacheWarmupResponses[keyof PostInternalBasketCacheWarmupResponses];

export type PostInternalBasketOptimizeMultiData = {
    /**
     * Optimization request
     */
    body: HandlersOptimizeRequest;
    path?: never;
    query?: never;
    url: '/internal/basket/optimize/multi';
};

export type PostInternalBasketOptimizeMultiErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
    /**
     * Cache unavailable
     */
    503: {
        [key: string]: string;
    };
    /**
     * Optimization timed out
     */
    504: {
        [key: string]: string;
    };
};

export type PostInternalBasketOptimizeMultiError = PostInternalBasketOptimizeMultiErrors[keyof PostInternalBasketOptimizeMultiErrors];

export type PostInternalBasketOptimizeMultiResponses = {
    /**
     * OK
     */
    200: HandlersMultiStoreResult;
};

export type PostInternalBasketOptimizeMultiResponse = PostInternalBasketOptimizeMultiResponses[keyof PostInternalBasketOptimizeMultiResponses];

export type PostInternalBasketOptimizeSingleData = {
    /**
     * Optimization request
     */
    body: HandlersOptimizeRequest;
    path?: never;
    query?: never;
    url: '/internal/basket/optimize/single';
};

export type PostInternalBasketOptimizeSingleErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
    /**
     * Cache unavailable
     */
    503: {
        [key: string]: string;
    };
};

export type PostInternalBasketOptimizeSingleError = PostInternalBasketOptimizeSingleErrors[keyof PostInternalBasketOptimizeSingleErrors];

export type PostInternalBasketOptimizeSingleResponses = {
    /**
     * Optimization results
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostInternalBasketOptimizeSingleResponse = PostInternalBasketOptimizeSingleResponses[keyof PostInternalBasketOptimizeSingleResponses];

export type GetInternalIngestionRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by chain slug
         */
        chainSlug?: string;
        /**
         * Filter by status
         */
        status?: 'pending' | 'running' | 'completed' | 'failed';
        /**
         * Number of items to return
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/internal/ingestion/runs';
};

export type GetInternalIngestionRunsErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type GetInternalIngestionRunsError = GetInternalIngestionRunsErrors[keyof GetInternalIngestionRunsErrors];

export type GetInternalIngestionRunsResponses = {
    /**
     * OK
     */
    200: HandlersListRunsResponse;
};

export type GetInternalIngestionRunsResponse = GetInternalIngestionRunsResponses[keyof GetInternalIngestionRunsResponses];

export type DeleteInternalIngestionRunsByRunIdData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        runId: string;
    };
    query?: never;
    url: '/internal/ingestion/runs/{runId}';
};

export type DeleteInternalIngestionRunsByRunIdErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Run not found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type DeleteInternalIngestionRunsByRunIdError = DeleteInternalIngestionRunsByRunIdErrors[keyof DeleteInternalIngestionRunsByRunIdErrors];

export type DeleteInternalIngestionRunsByRunIdResponses = {
    /**
     * Run deleted
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteInternalIngestionRunsByRunIdResponse = DeleteInternalIngestionRunsByRunIdResponses[keyof DeleteInternalIngestionRunsByRunIdResponses];

export type GetInternalIngestionRunsByRunIdData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        runId: string;
    };
    query?: never;
    url: '/internal/ingestion/runs/{runId}';
};

export type GetInternalIngestionRunsByRunIdErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Run not found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type GetInternalIngestionRunsByRunIdError = GetInternalIngestionRunsByRunIdErrors[keyof GetInternalIngestionRunsByRunIdErrors];

export type GetInternalIngestionRunsByRunIdResponses = {
    /**
     * OK
     */
    200: HandlersIngestionRun;
};

export type GetInternalIngestionRunsByRunIdResponse = GetInternalIngestionRunsByRunIdResponses[keyof GetInternalIngestionRunsByRunIdResponses];

export type GetInternalIngestionRunsByRunIdErrorsData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        runId: string;
    };
    query?: {
        /**
         * Number of items to return
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/internal/ingestion/runs/{runId}/errors';
};

export type GetInternalIngestionRunsByRunIdErrorsErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type GetInternalIngestionRunsByRunIdErrorsError = GetInternalIngestionRunsByRunIdErrorsErrors[keyof GetInternalIngestionRunsByRunIdErrorsErrors];

export type GetInternalIngestionRunsByRunIdErrorsResponses = {
    /**
     * OK
     */
    200: HandlersListErrorsResponse;
};

export type GetInternalIngestionRunsByRunIdErrorsResponse = GetInternalIngestionRunsByRunIdErrorsResponses[keyof GetInternalIngestionRunsByRunIdErrorsResponses];

export type GetInternalIngestionRunsByRunIdFilesData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        runId: string;
    };
    query?: {
        /**
         * Number of items to return
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/internal/ingestion/runs/{runId}/files';
};

export type GetInternalIngestionRunsByRunIdFilesErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type GetInternalIngestionRunsByRunIdFilesError = GetInternalIngestionRunsByRunIdFilesErrors[keyof GetInternalIngestionRunsByRunIdFilesErrors];

export type GetInternalIngestionRunsByRunIdFilesResponses = {
    /**
     * OK
     */
    200: HandlersListFilesResponse;
};

export type GetInternalIngestionRunsByRunIdFilesResponse = GetInternalIngestionRunsByRunIdFilesResponses[keyof GetInternalIngestionRunsByRunIdFilesResponses];

export type PostInternalIngestionRunsByRunIdRerunData = {
    /**
     * Rerun request
     */
    body: HandlersRerunRunRequest;
    path: {
        /**
         * Original run ID
         */
        runId: string;
    };
    query?: never;
    url: '/internal/ingestion/runs/{runId}/rerun';
};

export type PostInternalIngestionRunsByRunIdRerunErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Run not found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type PostInternalIngestionRunsByRunIdRerunError = PostInternalIngestionRunsByRunIdRerunErrors[keyof PostInternalIngestionRunsByRunIdRerunErrors];

export type PostInternalIngestionRunsByRunIdRerunResponses = {
    /**
     * Rerun created
     */
    201: {
        [key: string]: unknown;
    };
};

export type PostInternalIngestionRunsByRunIdRerunResponse = PostInternalIngestionRunsByRunIdRerunResponses[keyof PostInternalIngestionRunsByRunIdRerunResponses];

export type GetInternalIngestionStatsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Start date (RFC3339 format)
         */
        from: string;
        /**
         * End date (RFC3339 format)
         */
        to: string;
    };
    url: '/internal/ingestion/stats';
};

export type GetInternalIngestionStatsErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type GetInternalIngestionStatsError = GetInternalIngestionStatsErrors[keyof GetInternalIngestionStatsErrors];

export type GetInternalIngestionStatsResponses = {
    /**
     * OK
     */
    200: HandlersGetStatsResponse;
};

export type GetInternalIngestionStatsResponse = GetInternalIngestionStatsResponses[keyof GetInternalIngestionStatsResponses];

export type GetInternalItemsSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search query (min 3 chars)
         */
        q: string;
        /**
         * Filter by chain slug
         */
        chainSlug?: string;
        /**
         * Number of items to return
         */
        limit?: number;
    };
    url: '/internal/items/search';
};

export type GetInternalItemsSearchErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type GetInternalItemsSearchError = GetInternalItemsSearchErrors[keyof GetInternalItemsSearchErrors];

export type GetInternalItemsSearchResponses = {
    /**
     * OK
     */
    200: HandlersSearchItemsResponse;
};

export type GetInternalItemsSearchResponse = GetInternalItemsSearchResponses[keyof GetInternalItemsSearchResponses];

export type GetInternalPricesByChainSlugByStoreIdData = {
    body?: never;
    path: {
        /**
         * Chain slug identifier
         */
        chainSlug: string;
        /**
         * Store ID
         */
        storeId: string;
    };
    query?: {
        /**
         * Number of items to return
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/internal/prices/{chainSlug}/{storeId}';
};

export type GetInternalPricesByChainSlugByStoreIdErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type GetInternalPricesByChainSlugByStoreIdError = GetInternalPricesByChainSlugByStoreIdErrors[keyof GetInternalPricesByChainSlugByStoreIdErrors];

export type GetInternalPricesByChainSlugByStoreIdResponses = {
    /**
     * OK
     */
    200: HandlersGetStorePricesResponse;
};

export type GetInternalPricesByChainSlugByStoreIdResponse = GetInternalPricesByChainSlugByStoreIdResponses[keyof GetInternalPricesByChainSlugByStoreIdResponses];
