// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zHandlersBasketItem = z.object({
    itemId: z.string(),
    name: z.string(),
    quantity: z.int().gte(1)
});

export const zHandlersIngestionError = z.object({
    chunkId: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    entryId: z.optional(z.string()),
    errorDetails: z.optional(z.string()),
    errorMessage: z.optional(z.string()),
    errorType: z.optional(z.string()),
    fileId: z.optional(z.string()),
    id: z.optional(z.string()),
    runId: z.optional(z.string()),
    severity: z.optional(z.string())
});

export const zHandlersIngestionFile = z.object({
    chunkSize: z.optional(z.int()),
    createdAt: z.optional(z.string()),
    entryCount: z.optional(z.int()),
    fileHash: z.optional(z.string()),
    fileSize: z.optional(z.int()),
    fileType: z.optional(z.string()),
    filename: z.optional(z.string()),
    id: z.optional(z.string()),
    metadata: z.optional(z.string()),
    processedAt: z.optional(z.string()),
    processedChunks: z.optional(z.int()),
    runId: z.optional(z.string()),
    status: z.optional(z.string()),
    totalChunks: z.optional(z.int())
});

export const zHandlersIngestionRun = z.object({
    chainSlug: z.optional(z.string()),
    completedAt: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    errorCount: z.optional(z.int()),
    id: z.optional(z.string()),
    metadata: z.optional(z.string()),
    processedEntries: z.optional(z.int()),
    processedFiles: z.optional(z.int()),
    source: z.optional(z.string()),
    startedAt: z.optional(z.string()),
    status: z.optional(z.string()),
    totalEntries: z.optional(z.int()),
    totalFiles: z.optional(z.int())
});

export const zHandlersItemPriceInfo = z.object({
    basePrice: z.optional(z.int()),
    discountPrice: z.optional(z.int()),
    effectivePrice: z.optional(z.int()),
    hasDiscount: z.optional(z.boolean()),
    itemId: z.optional(z.string()),
    itemName: z.optional(z.string()),
    lineTotal: z.optional(z.int()),
    quantity: z.optional(z.int())
});

export const zHandlersListErrorsResponse = z.object({
    errors: z.optional(z.array(zHandlersIngestionError)),
    total: z.optional(z.int())
});

export const zHandlersListFilesResponse = z.object({
    files: z.optional(z.array(zHandlersIngestionFile)),
    total: z.optional(z.int())
});

export const zHandlersListRunsResponse = z.object({
    runs: z.optional(z.array(zHandlersIngestionRun)),
    total: z.optional(z.int())
});

export const zHandlersLocation = z.object({
    latitude: z.number().gte(-90).lte(90),
    longitude: z.number().gte(-180).lte(180)
});

export const zHandlersMissingItem = z.object({
    isOptional: z.optional(z.boolean()),
    itemId: z.optional(z.string()),
    itemName: z.optional(z.string()),
    penalty: z.optional(z.int())
});

export const zHandlersOptimizeRequest = z.object({
    basketItems: z.array(zHandlersBasketItem).min(1).max(100),
    chainSlug: z.string(),
    location: z.optional(zHandlersLocation),
    maxDistance: z.optional(z.number()),
    maxStores: z.optional(z.int())
});

export const zHandlersRerunRunRequest = z.object({
    rerunType: z.string(),
    targetId: z.string()
});

export const zHandlersSearchItem = z.object({
    avgPrice: z.optional(z.int()),
    brand: z.optional(z.string()),
    category: z.optional(z.string()),
    chainSlug: z.optional(z.string()),
    description: z.optional(z.string()),
    externalId: z.optional(z.string()),
    id: z.optional(z.string()),
    imageUrl: z.optional(z.string()),
    name: z.optional(z.string()),
    storeCount: z.optional(z.int()),
    subcategory: z.optional(z.string()),
    unit: z.optional(z.string()),
    unitQuantity: z.optional(z.string())
});

export const zHandlersSearchItemsResponse = z.object({
    items: z.optional(z.array(zHandlersSearchItem)),
    query: z.optional(z.string()),
    total: z.optional(z.int())
});

export const zHandlersStatsBucket = z.object({
    completed: z.optional(z.int()),
    failed: z.optional(z.int()),
    label: z.optional(z.string()),
    pending: z.optional(z.int()),
    running: z.optional(z.int()),
    totalErrors: z.optional(z.int()),
    totalFiles: z.optional(z.int()),
    totalRuns: z.optional(z.int())
});

export const zHandlersGetStatsResponse = z.object({
    buckets: z.optional(z.array(zHandlersStatsBucket))
});

export const zHandlersStoreAllocation = z.object({
    distance: z.optional(z.number()),
    items: z.optional(z.array(zHandlersItemPriceInfo)),
    storeId: z.optional(z.string()),
    storeTotal: z.optional(z.int()),
    visitOrder: z.optional(z.int())
});

export const zHandlersMultiStoreResult = z.object({
    algorithmUsed: z.optional(z.string()),
    combinedTotal: z.optional(z.int()),
    coverageRatio: z.optional(z.number()),
    stores: z.optional(z.array(zHandlersStoreAllocation)),
    unassignedItems: z.optional(z.array(zHandlersMissingItem))
});

export const zHandlersStorePrice = z.object({
    anchorPrice: z.optional(z.int()),
    brand: z.optional(z.string()),
    currentPrice: z.optional(z.int()),
    discountEnd: z.optional(z.string()),
    discountPrice: z.optional(z.int()),
    discountStart: z.optional(z.string()),
    inStock: z.optional(z.boolean()),
    itemExternalId: z.optional(z.string()),
    itemName: z.optional(z.string()),
    lastSeenAt: z.optional(z.string()),
    lowestPrice30d: z.optional(z.int()),
    previousPrice: z.optional(z.int()),
    priceSignature: z.optional(z.string()),
    retailerItemId: z.optional(z.string()),
    unit: z.optional(z.string()),
    unitPrice: z.optional(z.int()),
    unitPriceBaseQuantity: z.optional(z.string()),
    unitPriceBaseUnit: z.optional(z.string()),
    unitQuantity: z.optional(z.string())
});

export const zHandlersGetStorePricesResponse = z.object({
    prices: z.optional(z.array(zHandlersStorePrice)),
    total: z.optional(z.int())
});

export const zGetInternalBasketCacheHealthData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Cache health status
 */
export const zGetInternalBasketCacheHealthResponse = z.record(z.string(), z.unknown());

export const zPostInternalBasketCacheRefreshByChainSlugData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        chainSlug: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Cache refreshed
 */
export const zPostInternalBasketCacheRefreshByChainSlugResponse = z.record(z.string(), z.unknown());

export const zPostInternalBasketCacheWarmupData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Cache warmed up
 */
export const zPostInternalBasketCacheWarmupResponse = z.record(z.string(), z.unknown());

export const zPostInternalBasketOptimizeMultiData = z.object({
    body: zHandlersOptimizeRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostInternalBasketOptimizeMultiResponse = zHandlersMultiStoreResult;

export const zPostInternalBasketOptimizeSingleData = z.object({
    body: zHandlersOptimizeRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Optimization results
 */
export const zPostInternalBasketOptimizeSingleResponse = z.record(z.string(), z.unknown());

export const zGetInternalIngestionRunsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        chainSlug: z.optional(z.string()),
        status: z.optional(z.enum([
            'pending',
            'running',
            'completed',
            'failed'
        ])),
        limit: z.optional(z.int().gte(1).lte(100)).default(20),
        offset: z.optional(z.int().gte(0)).default(0)
    }))
});

/**
 * OK
 */
export const zGetInternalIngestionRunsResponse = zHandlersListRunsResponse;

export const zDeleteInternalIngestionRunsByRunIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        runId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Run deleted
 */
export const zDeleteInternalIngestionRunsByRunIdResponse = z.record(z.string(), z.unknown());

export const zGetInternalIngestionRunsByRunIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        runId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetInternalIngestionRunsByRunIdResponse = zHandlersIngestionRun;

export const zGetInternalIngestionRunsByRunIdErrorsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        runId: z.string()
    }),
    query: z.optional(z.object({
        limit: z.optional(z.int().gte(1).lte(100)).default(50),
        offset: z.optional(z.int().gte(0)).default(0)
    }))
});

/**
 * OK
 */
export const zGetInternalIngestionRunsByRunIdErrorsResponse = zHandlersListErrorsResponse;

export const zGetInternalIngestionRunsByRunIdFilesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        runId: z.string()
    }),
    query: z.optional(z.object({
        limit: z.optional(z.int().gte(1).lte(100)).default(50),
        offset: z.optional(z.int().gte(0)).default(0)
    }))
});

/**
 * OK
 */
export const zGetInternalIngestionRunsByRunIdFilesResponse = zHandlersListFilesResponse;

export const zPostInternalIngestionRunsByRunIdRerunData = z.object({
    body: zHandlersRerunRunRequest,
    path: z.object({
        runId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Rerun created
 */
export const zPostInternalIngestionRunsByRunIdRerunResponse = z.record(z.string(), z.unknown());

export const zGetInternalIngestionStatsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        from: z.string(),
        to: z.string()
    })
});

/**
 * OK
 */
export const zGetInternalIngestionStatsResponse = zHandlersGetStatsResponse;

export const zGetInternalItemsSearchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        q: z.string().min(3),
        chainSlug: z.optional(z.string()),
        limit: z.optional(z.int().gte(1).lte(100)).default(20)
    })
});

/**
 * OK
 */
export const zGetInternalItemsSearchResponse = zHandlersSearchItemsResponse;

export const zGetInternalPricesByChainSlugByStoreIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        chainSlug: z.string(),
        storeId: z.string()
    }),
    query: z.optional(z.object({
        limit: z.optional(z.int().gte(1).lte(500)).default(100),
        offset: z.optional(z.int().gte(0)).default(0)
    }))
});

/**
 * OK
 */
export const zGetInternalPricesByChainSlugByStoreIdResponse = zHandlersGetStorePricesResponse;
