import { defineConfig } from "@hey-api/openapi-ts";

export default defineConfig({
	// Use local swagger.json file - generated by `mise run swag` in the Go service
	input: "./services/price-service/docs/swagger.json",
	output: {
		path: "src/lib/go-api",
		format: "prettier",
	},
	plugins: [
		"@hey-api/typescript",
		"@hey-api/sdk",
		{
			name: "zod",
			exportFromIndex: true,
		},
	],
});
