// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package jsonb

type ArchiveMetadataJson struct {
	// Encoding corresponds to the JSON schema field "encoding".
	Encoding *string `json:"encoding,omitempty" yaml:"encoding,omitempty" mapstructure:"encoding,omitempty"`

	// ExtractedFiles corresponds to the JSON schema field "extractedFiles".
	ExtractedFiles []string `json:"extractedFiles,omitempty" yaml:"extractedFiles,omitempty" mapstructure:"extractedFiles,omitempty"`

	// OriginalFilename corresponds to the JSON schema field "originalFilename".
	OriginalFilename *string `json:"originalFilename,omitempty" yaml:"originalFilename,omitempty" mapstructure:"originalFilename,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CronJobPayloadJson struct {
	// ChainSlug corresponds to the JSON schema field "chainSlug".
	ChainSlug *string `json:"chainSlug,omitempty" yaml:"chainSlug,omitempty" mapstructure:"chainSlug,omitempty"`

	// TaskType corresponds to the JSON schema field "taskType".
	TaskType *string `json:"taskType,omitempty" yaml:"taskType,omitempty" mapstructure:"taskType,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CronRunMetadataJson struct {
	// CompletedAt corresponds to the JSON schema field "completedAt".
	CompletedAt *string `json:"completedAt,omitempty" yaml:"completedAt,omitempty" mapstructure:"completedAt,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty" yaml:"error,omitempty" mapstructure:"error,omitempty"`

	// StartedAt corresponds to the JSON schema field "startedAt".
	StartedAt *string `json:"startedAt,omitempty" yaml:"startedAt,omitempty" mapstructure:"startedAt,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ValidationErrorsJson []struct {
	// Code corresponds to the JSON schema field "code".
	Code *string `json:"code,omitempty" yaml:"code,omitempty" mapstructure:"code,omitempty"`

	// Field corresponds to the JSON schema field "field".
	Field *string `json:"field,omitempty" yaml:"field,omitempty" mapstructure:"field,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message" yaml:"message" mapstructure:"message"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value,omitempty" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}
