import { isNotNull, sql } from "drizzle-orm";
import { stores } from "../src/db/schema";
import { getDatabase } from "../src/db";

const CITY_NORMALIZATIONS: Record<string, string | null> = {
  "10430 samobor": "Samobor",
  "banjole": "Banjole",
  "beli manastir": "Beli Manastir",
  "belišće": "Belišće",
  "benkovac": "Benkovac",
  "bibinje sukosan": "Bibinje",
  "bilje": "Bilje",
  "biograd": "Biograd na Moru",
  "biograd na moru": "Biograd na Moru",
  "bjelovar": "Bjelovar",
  "brckovljani": "Brckovljani",
  "buje": "Buje",
  "buzet": "Buzet",
  "cakovec": "Čakovec",
  "čakovec": "Čakovec",
  "cakovec galerija": "Čakovec",
  "cakovec jug": "Čakovec",
  "cavle": "Cavle",
  "cazma": "Čazma",
  "čazma": "Čazma",
  "cepeljin": "Čepin",
  "cepin": "Čepin",
  "čepin": "Čepin",
  "cibaca": "Čibača",
  "čibača": "Čibača",
  "cista provo": "Cista Provo",
  "cres": "Cres",
  "crikvenica": "Crikvenica",
  "dakovo": "Đakovo",
  "đakovo": "Đakovo",
  "ðakovo": "Đakovo",
  "daruvar": "Daruvar",
  "delnice": "Delnice",
  "donja stubica": "Donja Stubica",
  "donji kneginec": "Donji Knežinec",
  "donji miholjac": "Donji Miholjac",
  "drniš": "Drniš",
  "dubrovnik": "Dubrovnik",
  "duga resa": "Duga Resa",
  "dugopolje": "Dugopolje",
  "dugo selo": "Dugo Selo",
  "đurđevac": "Đurđevac",
  "fazana": "Fažana",
  "fažana": "Fažana",
  "funtana": "Funtana",
  "garešnica": "Garešnica",
  "gospic": "Gospić",
  "gospić": "Gospić",
  "grohote": "Grohote",
  "grubišno polje": "Grubišno Polje",
  "g samobor": "Samobor",
  "hipermarket": null,
  "hum na sutli": "Hum na Sutli",
  "hvar": "Hvar",
  "ilok": "Ilok",
  "imotski": "Imotski",
  "ivance": "Ivanec",
  "ivanec": "Ivanec",
  "ivanic grad": "Ivanić-Grad",
  "ivanić-grad": "Ivanić-Grad",
  "ivanić grad": "Ivanić-Grad",
  "jablanovec": "Jablanovec",
  "jalzabet": "Jalžabet",
  "jalžabet": "Jalžabet",
  "jastrebarsko": "Jastrebarsko",
  "jelsa": "Jelsa",
  "kali": "Kali",
  "karlovac": "Karlovac",
  "karlovac kresimira": "Karlovac",
  "kastav": "Kastav",
  "kaštela": "Kaštela",
  "kastel stafilic": "Kaštel Stafilć",
  "kaštel stafilć": "Kaštel Stafilć",
  "kastel sucurac": "Kaštel Sućurac",
  "kaštel sućurac": "Kaštel Sućurac",
  "kc kolodvorska": "Koprivnica",
  "knin": "Knin",
  "komiža": "Komiža",
  "koprivnica": "Koprivnica",
  "korcula": "Korčula",
  "korčula": "Korčula",
  "korenica": "Korenica",
  "kostrena": "Kostrena",
  "kotoriba": "Kotoriba",
  "krapina": "Krapina",
  "krapinske toplice": "Krapinske Toplice",
  "krizevci": "Križevci",
  "križevci": "Križevci",
  "krk": "Krk",
  "kukuljanovo": "Kukuljanovo",
  "kupari": "Kupari",
  "kutina": "Kutina",
  "labin": "Labin",
  "lepoglava": "Lepoglava",
  "lopar": "Lopar",
  "lovran": "Lovran",
  "lucko": "Lučko",
  "lučko": "Lučko",
  "ludbreg": "Ludbreg",
  "makarska": "Makarska",
  "mali lošinj": "Mali Lošinj",
  "malinska": "Malinska",
  "marija bistrica": "Marija Bistrica",
  "matulji": "Matulji",
  "medulin": "Medulin",
  "metkovic": "Metković",
  "metković": "Metković",
  "mlini": "Mlini",
  "močići": "Močići",
  "mursko središće": "Mursko Središće",
  "murter": "Murter",
  "nasice": "Našice",
  "našice": "Našice",
  "nedescina": "Nedeščina",
  "nedeščina": "Nedeščina",
  "nin": "Nin",
  "nova gradiska": "Nova Gradiška",
  "nova gradiška": "Nova Gradiška",
  "novalja": "Novalja",
  "novigrad(cittanova)": "Novigrad",
  "novigrad": "Novigrad",
  "novi marof": "Novi Marof",
  "novi vinodolski": "Novi Vinodolski",
  "novska": "Novska",
  "ogulin": "Ogulin",
  "omiš": "Omiš",
  "omišalj": "Omišalj",
  "opatija": "Opatija",
  "opuzen": "Opuzen",
  "orahovica": "Orahovica",
  "orebic": "Orebić",
  "orebić": "Orebić",
  "oriovac": "Oriovac",
  "os centar": "Osijek",
  "osijek": "Osijek",
  "osijek strossmayerova": "Osijek",
  "os portanova": "Osijek",
  "os svilajska": "Osijek",
  "os trpimirova": "Osijek",
  "otocac": "Otočac",
  "otočac": "Otočac",
  "otok": "Otok",
  "ozalj": "Ozalj",
  "ozalj karlovacka": "Ozalj",
  "pag": "Pag",
  "pakostane": "Pakoštane",
  "pakoštane": "Pakoštane",
  "pakrac": "Pakrac",
  "pakrac 2": "Pakrac",
  "pasman": "Pašman",
  "pašman": "Pašman",
  "pazin": "Pazin",
  "petrinja": "Petrinja",
  "pirovac": "Pirovac",
  "pitomaca": "Pitomača",
  "pitomača": "Pitomača",
  "pleternica": "Pleternica",
  "ploce": "Ploče",
  "ploče": "Ploče",
  "pomer": "Pomer",
  "popovaca": "Popovača",
  "popovača": "Popovača",
  "porec": "Poreč",
  "poreč": "Poreč",
  "posedarje": "Posedarje",
  "pozega": "Požega",
  "požega": "Požega",
  "pregrada": "Pregrada",
  "prelog": "Prelog",
  "primošten": "Primošten",
  "privlaka": "Privlaka",
  "pu city mall": "Pula",
  "pula": "Pula",
  "pula santoriova": "Pula",
  "rab": "Rab",
  "razine": "Razine",
  "rijeka": "Rijeka",
  "rijeka candekova": "Rijeka",
  "rijeka kastav": "Rijeka",
  "rijeka martinkovac": "Rijeka",
  "rijeka osjecka": "Rijeka",
  "ri krnjevo": "Rijeka",
  "ri kukuljanovo": "Rijeka",
  "ri riva boduli": "Rijeka",
  "ri rujevica": "Rijeka",
  "ri tower": "Rijeka",
  "rogoznica": "Rogoznica",
  "rovinj": "Rovinj",
  "rubeši": "Rubeši",
  "samobor": "Samobor",
  "sb supernova": "Slavonski Brod",
  "sb svaciceva": "Slavonski Brod",
  "selce": "Selce",
  "senj": "Senj",
  "sesvete": "Sesvete",
  "sesvetski kraljevec": "Sesvetski Kraljevec",
  "sibenik": "Šibenik",
  "šibenik": "Šibenik",
  "sibenik supernova": "Šibenik",
  "sinj": "Sinj",
  "sisak": "Sisak",
  "slatina": "Slatina",
  "slavonski brod": "Slavonski Brod",
  "slunj": "Slunj",
  "solin": "Solin",
  "split": "Split",
  "split boskoviceva": "Split",
  "split licka": "Split",
  "split poljicka 2": "Split",
  "split spinciceva": "Split",
  "split subiceva": "Split",
  "sredisce": "Središće",
  "središće": "Središće",
  "st mos": "Split",
  "ston": "Ston",
  "strmec": "Strmec",
  "suhopolje": "Suhopolje",
  "sukosan": "Sukošan",
  "sukošan": "Sukošan",
  "supetar": "Supetar",
  "sveta klara": "Zagreb",
  "sveta nedelja": "Sveta Nedelja",
  "sveti filip i jakov": "Sveti Filip i Jakov",
  "sv. ivan zelina": "Sveti Ivan Zelina",
  "sveti ivan zelina": "Sveti Ivan Zelina",
  "sv ivan zelina": "Sveti Ivan Zelina",
  "sv kriz zacretje": "Sveti Križ Začretje",
  "sveti križ začretje": "Sveti Križ Začretje",
  "tar": "Tar",
  "tribunj": "Tribunj",
  "trnovec bartolovečki": "Trnovec Bartolovečki",
  "trogir": "Trogir",
  "umag": "Umag",
  "umag-umago": "Umag",
  "valpovo": "Valpovo",
  "valpovo stc": "Valpovo",
  "varazdin": "Varaždin",
  "varaždin": "Varaždin",
  "varazdinske toplice": "Varaždinske Toplice",
  "varaždinske toplice": "Varaždinske Toplice",
  "varazdin supernova": "Varaždin",
  "velika gorica": "Velika Gorica",
  "veliko trgovišće": "Veliko Trgovišće",
  "vg kresimira": "Velika Gorica",
  "vg matice hrvatske": "Velika Gorica",
  "vinkovci": "Vinkovci",
  "vinkovci a. b. simica": "Vinkovci",
  "vir": "Vir",
  "virovitica": "Virovitica",
  "vis": "Vis",
  "viskovo": "Viškovo",
  "viškovo": "Viškovo",
  "vodice": "Vodice",
  "vodnjan": "Vodnjan",
  "volosko": "Volosko",
  "vrbovec": "Vrbovec",
  "vrsar": "Vrsar",
  "vukovar": "Vukovar",
  "vz mederala": "Varaždin",
  "vz medimurska": "Varaždin",
  "vz zagrebacka": "Varaždin",
  "zabok": "Zabok",
  "zacretje": "Zabok",
  "zadar": "Zadar",
  "zadar city galleria": "Zadar",
  "zadar supernova": "Zadar",
  "zagreb": "Zagreb",
  "zagreb blato": "Zagreb",
  "zagreb dubec": "Zagreb",
  "zagreb - sesvete": "Sesvete",
  "zaostrog": "Zaostrog",
  "zapresic": "Zaprešić",
  "zaprešić": "Zaprešić",
  "zaprešic": "Zaprešić",
  "zaton": "Zaton",
  "zd starceviceva": "Zadar",
  "zg ante t. mimare": "Zagreb",
  "zg arena centar": "Zagreb",
  "zg argentinska": "Zagreb",
  "zg av. dubrovnik": "Zagreb",
  "zg bakiceva": "Zagreb",
  "zg banjavciceva 13": "Zagreb",
  "zg bijenicka": "Zagreb",
  "zg borongajska": "Zagreb",
  "zg branimirova": "Zagreb",
  "zg branimirova 2": "Zagreb",
  "zg buzin": "Zagreb",
  "zg cco east": "Zagreb",
  "zg cco west": "Zagreb",
  "zg dankovecka": "Zagreb",
  "zg dobroniceva": "Zagreb",
  "zg dubrava 45": "Zagreb",
  "zg emmez stup": "Zagreb",
  "zg erlichova": "Zagreb",
  "zg garden dub.": "Zagreb",
  "zg gospodska": "Zagreb",
  "zg gracani": "Zagreb",
  "zg grada mainza": "Zagreb",
  "zg gruska": "Zagreb",
  "zg horvatovac": "Zagreb",
  "zg i.b. mazuranic": "Zagreb",
  "zg jordanovac": "Zagreb",
  "zg jurisiceva": "Zagreb",
  "zg kingcross": "Zagreb",
  "zg kovacica": "Zagreb",
  "zg macanovica": "Zagreb",
  "zg magovceva": "Zagreb",
  "zg marticeva": "Zagreb",
  "zg mlinovi": "Zagreb",
  "zg oranice": "Zagreb",
  "zg petrovaradinska": "Zagreb",
  "zg picmanova": "Zagreb",
  "zg pomoraca": "Zagreb",
  "zg retkovec": "Zagreb",
  "zg savska": "Zagreb",
  "zg seferova": "Zagreb",
  "zg siblova": "Zagreb",
  "zg sr njemacke": "Zagreb",
  "zg trg zrt. fasizma": "Zagreb",
  "zg trnsko": "Zagreb",
  "zg tuskanac": "Zagreb",
  "zg ujevica": "Zagreb",
  "zg varicaka": "Zagreb",
  "zg vincenta": "Zagreb",
  "zg vlaska": "Zagreb",
  "zg zagrebacka": "Zagreb",
  "zg zerjaviceva": "Zagreb",
  "zlatar": "Zlatar",
  "zlatar bistrica": "Zlatar Bistrica",
  "zminj": "Žminj",
  "žminj": "Žminj",
  "zupanja": "Županja",
  "županja": "Županja",
  "cco split": "Split",
  "riječka": "Rijeka",
  "karlovačka": "Karlovac",
  "zagrebačka": "Zagreb",
  "osječka": "Osijek",
};

function normalizeCity(city: string | null): string | null {
  if (!city) return null;
  const normalized = city.toLowerCase().trim();
  if (normalized in CITY_NORMALIZATIONS) {
    return CITY_NORMALIZATIONS[normalized] ?? null;
  }
  const capitalized = city
    .toLowerCase()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
  return capitalized;
}

async function main() {
  const db = getDatabase();

  const allStores = await db
    .select({ id: stores.id, city: stores.city })
    .from(stores)
    .where(isNotNull(stores.city));

  console.log(`Found ${allStores.length} stores with cities`);

  const updates: Array<[string, string]> = [];

  for (const store of allStores) {
    if (!store.city) continue;
    const normalized = normalizeCity(store.city);
    if (normalized && normalized !== store.city) {
      updates.push([store.id, normalized]);
    }
  }

  console.log(`Need to update ${updates.length} stores`);

  const batchSize = 500;
  for (let i = 0; i < updates.length; i += batchSize) {
    const batch = updates.slice(i, i + batchSize);
    const values = sql.join(
      batch.map(([id, city]) => sql`(${id}, ${city})`),
      sql`, `,
    );

    await db.execute(sql`
      UPDATE stores AS s
      SET city = src.city,
          updated_at = NOW()
      FROM (VALUES ${values}) AS src(id, city)
      WHERE s.id = src.id
    `);
    console.log(
      `Updated batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(updates.length / batchSize)}`,
    );
  }

  console.log("Done!");
}

main().catch(console.error);
