import { getConfigInfo } from "./admin";
import {
	getCategories,
	getStoresByChain,
	listCatalogPrices,
} from "./catalog-prices";
import {
	deleteRun,
	deleteRuns,
	getChunk,
	getFile,
	getRun,
	getStats,
	listChunks,
	listErrors,
	listFiles,
	listRuns,
	rerunChunk,
	rerunFile,
	rerunRun,
	triggerChain,
} from "./ingestion";
import { getSettings, updateSettings } from "./settings";
import {
	approveStore,
	createPhysicalStore,
	getEnrichmentTasks,
	getLinkedPhysicalStores,
	getPendingStores,
	getStore,
	getVirtualStoresForLinking,
	linkPriceSource,
	listPhysicalStores,
	listStores,
	listVirtualStores,
	mergeStores,
	rejectStore,
	triggerEnrichment,
	unlinkPriceSource,
	updateStore,
	verifyEnrichment,
} from "./stores";
import { addTodo, listTodos } from "./todos";
import {
	banUser,
	deleteUser,
	getUser,
	listUsers,
	updateUserRole,
} from "./users";

export default {
	listTodos,
	addTodo,
	admin: {
		getConfigInfo,
		users: {
			list: listUsers,
			get: getUser,
			updateRole: updateUserRole,
			delete: deleteUser,
			ban: banUser,
		},
		settings: {
			get: getSettings,
			update: updateSettings,
		},
		ingestion: {
			listRuns,
			getRun,
			listFiles,
			getFile,
			listChunks,
			getChunk,
			listErrors,
			getStats,
			rerunRun,
			rerunFile,
			rerunChunk,
			triggerChain,
			deleteRun,
			deleteRuns,
		},
		stores: {
			list: listStores,
			listVirtual: listVirtualStores,
			listPhysical: listPhysicalStores,
			getVirtualStoresForLinking: getVirtualStoresForLinking,
			get: getStore,
			create: createPhysicalStore,
			update: updateStore,
			approve: approveStore,
			reject: rejectStore,
			merge: mergeStores,
			linkPriceSource: linkPriceSource,
			unlinkPriceSource: unlinkPriceSource,
			getPending: getPendingStores,
			getLinkedPhysical: getLinkedPhysicalStores,
			triggerEnrichment: triggerEnrichment,
			getEnrichmentTasks: getEnrichmentTasks,
			verifyEnrichment: verifyEnrichment,
		},
		catalogPrices: {
			list: listCatalogPrices,
			getStoresByChain: getStoresByChain,
			getCategories: getCategories,
		},
	},
};
