import { getConfigInfo } from "./admin";
import * as basket from "./basket";
import {
	getCategories,
	getStoresByChain,
	listCatalogPrices,
} from "./catalog-prices";
import * as clickhouse from "./clickhouse";
import * as cron from "./cron";
import * as ingestion from "./ingestion";
import * as prices from "./prices";
import {
	approveMatch,
	bulkApprove,
	getPendingMatchCount,
	getPendingMatches,
	getStats,
	rejectMatch,
	resolveSuspicious,
	searchProducts,
	triggerBarcodeMatching,
	triggerTrigramMatching,
} from "./products";
import { getSettings, updateSettings } from "./settings";
import {
	approveStore,
	bulkApproveStores,
	bulkRejectStores,
	createPhysicalStore,
	forceApproveStore,
	getEnrichmentTasks,
	getLinkedPhysicalStores,
	getPendingStores,
	getStore,
	getStoreDetail,
	getVirtualStoresForLinking,
	linkPriceSource,
	listPhysicalStores,
	listStores,
	listVirtualStores,
	mergeStores,
	rejectStore,
	triggerEnrichment,
	unlinkPriceSource,
	updateStore,
	verifyEnrichment,
} from "./stores";
import * as taskQueue from "./task-queue";
import { addTodo, listTodos } from "./todos";
import {
	banUser,
	deleteUser,
	getUser,
	listUsers,
	updateUserRole,
} from "./users";

export default {
	listTodos,
	addTodo,
	basket: {
		optimizeSingle: basket.optimizeSingle,
		optimizeMulti: basket.optimizeMulti,
		cacheWarmup: basket.cacheWarmup,
		cacheRefresh: basket.cacheRefresh,
		cacheHealth: basket.cacheHealth,
	},
	prices: {
		getStorePrices: prices.getStorePrices,
		searchItems: prices.searchItems,
	},
	admin: {
		getConfigInfo,
		users: {
			list: listUsers,
			get: getUser,
			updateRole: updateUserRole,
			delete: deleteUser,
			ban: banUser,
		},
		settings: {
			get: getSettings,
			update: updateSettings,
		},
		clickhouse: {
			loadAll: clickhouse.loadAll,
			loadMissing: clickhouse.loadMissing,
			status: clickhouse.status,
		},
		ingestion: {
			listRuns: ingestion.listRuns,
			getRun: ingestion.getRun,
			listFiles: ingestion.listFiles,
			listErrors: ingestion.listErrors,
			listRunStoreStats: ingestion.listRunStoreStats,
			getStats: ingestion.getStats,
			triggerChain: ingestion.triggerChain,
			rerunRun: ingestion.rerunRun,
			deleteRun: ingestion.deleteRun,
			getFile: ingestion.getFile,
			listChunks: ingestion.listChunks,
			rerunFile: ingestion.rerunFile,
			rerunChunk: ingestion.rerunChunk,
			listFileErrors: ingestion.listFileErrors,
			listFileStoreStats: ingestion.listFileStoreStats,
		},
		stores: {
			list: listStores,
			listVirtual: listVirtualStores,
			listPhysical: listPhysicalStores,
			getVirtualStoresForLinking: getVirtualStoresForLinking,
			get: getStore,
			getDetail: getStoreDetail,
			create: createPhysicalStore,
			update: updateStore,
			approve: approveStore,
			reject: rejectStore,
			merge: mergeStores,
			bulkApprove: bulkApproveStores,
			bulkReject: bulkRejectStores,
			forceApprove: forceApproveStore,
			linkPriceSource: linkPriceSource,
			unlinkPriceSource: unlinkPriceSource,
			getPending: getPendingStores,
			getLinkedPhysical: getLinkedPhysicalStores,
			triggerEnrichment: triggerEnrichment,
			getEnrichmentTasks: getEnrichmentTasks,
			verifyEnrichment: verifyEnrichment,
		},
		catalogPrices: {
			list: listCatalogPrices,
			getStoresByChain: getStoresByChain,
			getCategories: getCategories,
		},
		products: {
			getPendingMatches,
			getPendingMatchCount,
			approveMatch,
			rejectMatch,
			bulkApprove,
			resolveSuspicious,
			searchProducts,
			getStats,
			triggerBarcodeMatching,
			triggerTrigramMatching,
		},
		cron: {
			list: cron.list,
			get: cron.get,
			listRuns: cron.listRuns,
			trigger: cron.trigger,
			toggle: cron.toggle,
			health: cron.health,
			getRun: cron.getRun,
		},
		taskQueue: {
			stats: taskQueue.stats,
			list: taskQueue.list,
			get: taskQueue.get,
			cancel: taskQueue.cancel,
			requeue: taskQueue.requeue,
			reschedule: taskQueue.reschedule,
			recoverOrphaned: taskQueue.recoverOrphaned,
			cleanupCompleted: taskQueue.cleanupCompleted,
		},
	},
};
