import { logLlmDecision } from "@/lib/llm-observability";
import { createLogger } from "@/utils/logger";
import type { EnsembleModelConfig } from "./config";
import {
	type GenerateCandidateGroupsOptions,
	generateCandidateGroups,
} from "./blocking";
import { decideListwiseCascade } from "./listwise/ensemble";
import { loadListwiseModelConfigs, processGroupWithLLM } from "./listwise/llm-call";
import { fetchMedianPrices } from "./listwise/price-fetch";
import type { CandidateGroup, ListwiseLLMResult } from "./listwise/types";
import { persistAcceptedGrouping } from "./listwise/pipeline";

const log = createLogger("matching");

export interface RunUnifiedMatchingOptions {
	/** Max groups to process. */
	limit?: number;
	/** Dry run — skip persistence. */
	dryRun?: boolean;
	/** Min confidence from primary model before escalation. */
	minPrimaryConfidence?: number;
	/** Primary LLM model id from ensemble config. */
	primaryModelId?: string;
	/** Secondary LLM model id for cascade escalation. */
	secondaryModelId?: string;
	/** Blocking options for candidate group generation. */
	blocking?: GenerateCandidateGroupsOptions;
}

export interface RunUnifiedMatchingResult {
	/** Total groups generated by blocking. */
	candidateGroups: number;
	/** Groups processed through LLM. */
	processedGroups: number;
	/** Groups skipped (singleton or too small). */
	skippedGroups: number;
	/** Groups escalated to secondary model. */
	escalatedGroups: number;
	/** Canonical SKUs created. */
	createdSkus: number;
	/** Items linked to SKUs. */
	linkedItems: number;
	/** Groups with LLM errors. */
	errorGroups: number;
	/** Blocking stats. */
	blockingStats: {
		barcodeGroups: number;
		deterministicGroups: number;
		embeddingGroups: number;
		lexicalGroups: number;
		totalItems: number;
	};
}

function parsePositiveInt(value: unknown, fallback: number): number {
	const parsed =
		typeof value === "string" ? Number.parseInt(value, 10) : Number(value);
	return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function pickModel(
	configs: EnsembleModelConfig[],
	modelId: string,
): EnsembleModelConfig {
	const found = configs.find((config) => config.id === modelId);
	if (!found) {
		throw new Error(`Missing model config: ${modelId}`);
	}
	return found;
}

/** Split large groups into sub-groups by brand for focused LLM prompts. */
function splitGroupByBrand(
	group: CandidateGroup,
	maxSize: number,
): CandidateGroup[] {
	if (group.items.length <= maxSize) return [group];

	const byBrand = new Map<string, typeof group.items>();
	for (const item of group.items) {
		const key = (item.brand ?? "__no_brand__").toLowerCase();
		if (!byBrand.has(key)) byBrand.set(key, []);
		byBrand.get(key)?.push(item);
	}

	const subGroups: CandidateGroup[] = [];
	let idx = 0;
	for (const [brand, items] of byBrand.entries()) {
		// Further split if still too large
		for (let offset = 0; offset < items.length; offset += maxSize) {
			const chunk = items.slice(offset, offset + maxSize);
			if (chunk.length < 2) continue;
			subGroups.push({
				groupId: `${group.groupId}_sub${idx}`,
				seedKey: `${group.seedKey}|brand:${brand}|chunk:${idx}`,
				items: chunk,
				category: group.category,
				brand: brand === "__no_brand__" ? null : brand,
			});
			idx += 1;
		}
	}

	return subGroups.length > 0 ? subGroups : [group];
}

export async function runUnifiedMatching(
	options: RunUnifiedMatchingOptions = {},
): Promise<RunUnifiedMatchingResult> {
	const limit =
		options.limit ??
		parsePositiveInt(process.env.UNIFIED_MATCHING_LIMIT, 50);
	const dryRun = options.dryRun ?? process.env.UNIFIED_MATCHING_DRY_RUN === "1";

	const modelConfigs = loadListwiseModelConfigs();
	const primaryModelId =
		options.primaryModelId ??
		process.env.LISTWISE_PRIMARY_MODEL_ID ??
		"qwen";
	const secondaryModelId =
		options.secondaryModelId ??
		process.env.LISTWISE_SECONDARY_MODEL_ID ??
		"ministral";

	const primaryModel = pickModel(modelConfigs, primaryModelId);
	const secondaryModel = pickModel(modelConfigs, secondaryModelId);

	// Stage 2: BLOCK — generate candidate groups
	log.info("Unified matching: generating candidate groups", {
		limit,
		dryRun,
		primaryModel: primaryModelId,
		secondaryModel: secondaryModelId,
	});

	const blocking = await generateCandidateGroups(options.blocking);

	// Expand large groups into brand-scoped sub-groups
	const maxGroupSize = 30;
	const expandedGroups: CandidateGroup[] = [];
	for (const group of blocking.groups) {
		expandedGroups.push(...splitGroupByBrand(group, maxGroupSize));
	}

	// Limit total groups to process
	const groupsToProcess = expandedGroups.slice(0, limit);

	// Prefetch prices for all items
	const allItemIds = groupsToProcess.flatMap((group) =>
		group.items.map((item) => item.retailerItemId),
	);
	const prices = await fetchMedianPrices(allItemIds);

	let processedGroups = 0;
	let skippedGroups = 0;
	let escalatedGroups = 0;
	let createdSkus = 0;
	let linkedItems = 0;
	let errorGroups = 0;

	// Stage 3: RESOLVE + Stage 4: PERSIST
	for (const group of groupsToProcess) {
		const groupItemCount = group.items.length;

		// Skip singleton groups
		if (groupItemCount < 2) {
			skippedGroups += 1;
			continue;
		}

		processedGroups += 1;

		log.info("Unified matching: processing group", {
			groupId: group.groupId,
			seedKey: group.seedKey,
			itemCount: groupItemCount,
			primaryModel: primaryModel.id,
			dryRun,
		});

		try {
			// Run LLM extraction + clustering
			const primary = await processGroupWithLLM(primaryModel, group, prices);
			const cascade = decideListwiseCascade({
				primary,
				primaryModel,
				secondaryModel,
				itemCount: groupItemCount,
				minPrimaryConfidence: options.minPrimaryConfidence,
			});

			await logLlmDecision({
				taskType: "unified_matching",
				input: {
					groupId: group.groupId,
					seedKey: group.seedKey,
					itemCount: groupItemCount,
					items: group.items.map((item) => ({
						id: item.retailerItemId,
						rawName: item.rawName,
						chainSlug: item.chainSlug,
					})),
				},
				output: {
					decision: cascade.shouldEscalate ? "escalate" : "accept",
					reason: cascade.reason,
					primary: {
						modelId: primary.modelId,
						provider: primary.provider,
						confidence: primary.clustering.confidence,
						baseProducts: primary.clustering.baseProducts.length,
						unclassified: primary.clustering.unclassified.length,
						missing: primary.clustering.missingItemIds.length,
						duplicates: primary.clustering.duplicateItemIds.length,
					},
				},
				modelId: primary.modelId,
				provider: primary.provider,
				verdict: cascade.shouldEscalate ? "ESCALATE" : "ACCEPT",
				confidence: primary.clustering.confidence,
				reasoning: cascade.reason,
				latencyMs: primary.totalLatencyMs,
				tokenCount: primary.tokenEstimates.total,
			});

			let accepted: ListwiseLLMResult;
			if (cascade.shouldEscalate) {
				escalatedGroups += 1;
				const secondary = await processGroupWithLLM(
					secondaryModel,
					group,
					prices,
				);
				accepted = secondary;

				await logLlmDecision({
					taskType: "unified_matching_verify",
					input: {
						groupId: group.groupId,
						seedKey: group.seedKey,
						reason: cascade.reason,
					},
					output: {
						primary: {
							modelId: primary.modelId,
							confidence: primary.clustering.confidence,
							baseProducts: primary.clustering.baseProducts.length,
						},
						secondary: {
							modelId: secondary.modelId,
							confidence: secondary.clustering.confidence,
							baseProducts: secondary.clustering.baseProducts.length,
						},
					},
					modelId: secondary.modelId,
					provider: secondary.provider,
					verdict: "VERIFIED",
					confidence: secondary.clustering.confidence,
					reasoning: "Secondary model verification",
					latencyMs: secondary.totalLatencyMs,
					tokenCount: secondary.tokenEstimates.total,
				});
			} else {
				accepted = primary;
			}

			// Persist results
			const persisted = await persistAcceptedGrouping({
				group,
				llm: accepted,
				dryRun,
			});
			createdSkus += persisted.createdSkus;
			linkedItems += persisted.linkedItems;
		} catch (error) {
			errorGroups += 1;
			log.error("Unified matching: group processing failed", {
				groupId: group.groupId,
				seedKey: group.seedKey,
				error,
			});
		}
	}

	const result: RunUnifiedMatchingResult = {
		candidateGroups: blocking.groups.length,
		processedGroups,
		skippedGroups,
		escalatedGroups,
		createdSkus,
		linkedItems,
		errorGroups,
		blockingStats: {
			barcodeGroups: blocking.stats.barcodeGroups,
			deterministicGroups: blocking.stats.deterministicGroups,
			embeddingGroups: blocking.stats.embeddingGroups,
			lexicalGroups: blocking.stats.lexicalGroups,
			totalItems: blocking.stats.totalItems,
		},
	};

	log.info("Unified matching completed", { ...result, dryRun });

	return result;
}
