import { logLlmDecision } from "@/lib/llm-observability";
import { createLogger } from "@/utils/logger";
import {
	type GenerateCandidateGroupsOptions,
	generateCandidateGroups,
} from "./blocking";
import type { EnsembleModelConfig } from "./config";
import { decideListwiseCascade } from "./listwise/ensemble";
import {
	loadListwiseModelConfigs,
	processGroupsWithLLM,
	processGroupWithLLM,
} from "./listwise/llm-call";
import { persistAcceptedGrouping } from "./listwise/pipeline";
import { fetchMedianPrices } from "./listwise/price-fetch";
import type { CandidateGroup, ListwiseLLMResult } from "./listwise/types";

const log = createLogger("matching");

export interface RunUnifiedMatchingOptions {
	/** Max groups to process. */
	limit?: number;
	/** Dry run — skip persistence. */
	dryRun?: boolean;
	/** Min confidence from primary model before escalation. */
	minPrimaryConfidence?: number;
	/** Primary LLM model id from ensemble config. */
	primaryModelId?: string;
	/** Secondary LLM model id for cascade escalation. */
	secondaryModelId?: string;
	/** Blocking options for candidate group generation. */
	blocking?: GenerateCandidateGroupsOptions;
	/** Max items per LLM prompt (large groups are split by brand). */
	maxGroupSize?: number;
	/** How many candidate groups to pack into one LLM request (bulk listwise). */
	groupsPerCall?: number;
}

export interface RunUnifiedMatchingResult {
	/** Total groups generated by blocking. */
	candidateGroups: number;
	/** Groups processed through LLM. */
	processedGroups: number;
	/** Groups skipped (singleton or too small). */
	skippedGroups: number;
	/** Groups escalated to secondary model. */
	escalatedGroups: number;
	/** Canonical SKUs created. */
	createdSkus: number;
	/** Items linked to SKUs. */
	linkedItems: number;
	/** Groups with LLM errors. */
	errorGroups: number;
	/** Blocking stats. */
	blockingStats: {
		barcodeGroups: number;
		deterministicGroups: number;
		embeddingGroups: number;
		lexicalGroups: number;
		totalItems: number;
	};
}

function parsePositiveInt(value: unknown, fallback: number): number {
	const parsed =
		typeof value === "string" ? Number.parseInt(value, 10) : Number(value);
	return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function parsePositiveIntEnv(name: string, fallback: number): number {
	const raw = process.env[name];
	if (!raw) return fallback;
	return parsePositiveInt(raw, fallback);
}

function pickModel(
	configs: EnsembleModelConfig[],
	modelId: string,
): EnsembleModelConfig {
	const found = configs.find((config) => config.id === modelId);
	if (!found) {
		throw new Error(`Missing model config: ${modelId}`);
	}
	return found;
}

/** Split large groups into sub-groups by brand for focused LLM prompts. */
function splitGroupByBrand(
	group: CandidateGroup,
	maxSize: number,
): CandidateGroup[] {
	if (group.items.length <= maxSize) return [group];

	const byBrand = new Map<string, typeof group.items>();
	for (const item of group.items) {
		const key = (item.brand ?? "__no_brand__").toLowerCase();
		if (!byBrand.has(key)) byBrand.set(key, []);
		byBrand.get(key)?.push(item);
	}

	const subGroups: CandidateGroup[] = [];
	let idx = 0;
	for (const [brand, items] of byBrand.entries()) {
		// Further split if still too large
		for (let offset = 0; offset < items.length; offset += maxSize) {
			const chunk = items.slice(offset, offset + maxSize);
			if (chunk.length < 2) continue;
			subGroups.push({
				groupId: `${group.groupId}_sub${idx}`,
				seedKey: `${group.seedKey}|brand:${brand}|chunk:${idx}`,
				items: chunk,
				category: group.category,
				brand: brand === "__no_brand__" ? null : brand,
			});
			idx += 1;
		}
	}

	return subGroups.length > 0 ? subGroups : [group];
}

export async function runUnifiedMatching(
	options: RunUnifiedMatchingOptions = {},
): Promise<RunUnifiedMatchingResult> {
	const limit =
		options.limit ?? parsePositiveInt(process.env.UNIFIED_MATCHING_LIMIT, 50);
	const dryRun = options.dryRun ?? process.env.UNIFIED_MATCHING_DRY_RUN === "1";

	const modelConfigs = loadListwiseModelConfigs();
	const primaryModelId =
		options.primaryModelId ?? process.env.LISTWISE_PRIMARY_MODEL_ID ?? "qwen";
	const secondaryModelId =
		options.secondaryModelId ??
		process.env.LISTWISE_SECONDARY_MODEL_ID ??
		"ministral";

	const primaryModel = pickModel(modelConfigs, primaryModelId);
	const secondaryModel = pickModel(modelConfigs, secondaryModelId);

	// Stage 2: BLOCK — generate candidate groups
	log.info("Unified matching: generating candidate groups", {
		limit,
		dryRun,
		primaryModel: primaryModelId,
		secondaryModel: secondaryModelId,
	});

	const blocking = await generateCandidateGroups(options.blocking);

	// Expand large groups into brand-scoped sub-groups
	const maxGroupSize =
		options.maxGroupSize ??
		parsePositiveIntEnv("UNIFIED_MATCHING_MAX_GROUP_SIZE", 45);
	const expandedGroups: CandidateGroup[] = [];
	for (const group of blocking.groups) {
		expandedGroups.push(...splitGroupByBrand(group, maxGroupSize));
	}

	// Limit total groups to process
	const groupsToProcess = expandedGroups.slice(0, limit);

	const groupsPerCall =
		options.groupsPerCall ??
		parsePositiveIntEnv("UNIFIED_MATCHING_GROUPS_PER_CALL", 3);

	// Prefetch prices for all items
	const allItemIds = groupsToProcess.flatMap((group) =>
		group.items.map((item) => item.retailerItemId),
	);
	const prices = await fetchMedianPrices(allItemIds);

	let processedGroups = 0;
	let skippedGroups = 0;
	let escalatedGroups = 0;
	let createdSkus = 0;
	let linkedItems = 0;
	let errorGroups = 0;

	const processableGroups = groupsToProcess.filter((group) => {
		if (group.items.length < 2) {
			skippedGroups += 1;
			return false;
		}
		return true;
	});

	const maxGroupsPerCall = Math.max(1, Math.min(20, groupsPerCall));

	async function safeProcessBatch(
		model: EnsembleModelConfig,
		groups: readonly CandidateGroup[],
	): Promise<Map<string, ListwiseLLMResult>> {
		try {
			const results = await processGroupsWithLLM(model, groups, prices);
			return new Map(results.map((result) => [result.groupId, result] as const));
		} catch (error) {
			const errorMessage =
				error instanceof Error ? error.message : String(error);
			if (/\\bHTTP\\s+(401|403)\\b/.test(errorMessage)) {
				log.error(
					"Unified matching: LLM authentication failed; aborting run",
					{
						modelId: model.id,
						groupCount: groups.length,
						errorMessage,
					},
				);
				throw error instanceof Error ? error : new Error(errorMessage);
			}

			log.warn("Unified matching: bulk LLM call failed; falling back to per-group", {
				modelId: model.id,
				groupCount: groups.length,
				error:
					error instanceof Error
						? { name: error.name, message: error.message }
						: { unknownError: String(error) },
			});

			const map = new Map<string, ListwiseLLMResult>();
			for (const group of groups) {
				try {
					const result = await processGroupWithLLM(model, group, prices);
					map.set(group.groupId, result);
				} catch (groupError) {
					const groupErrorMessage =
						groupError instanceof Error ? groupError.message : String(groupError);
					if (/\\bHTTP\\s+(401|403)\\b/.test(groupErrorMessage)) {
						log.error(
							"Unified matching: LLM authentication failed; aborting run",
							{
								modelId: model.id,
								groupId: group.groupId,
								errorMessage: groupErrorMessage,
							},
						);
						throw groupError instanceof Error
							? groupError
							: new Error(groupErrorMessage);
					}

					errorGroups += 1;
					log.error("Unified matching: group LLM processing failed", {
						groupId: group.groupId,
						seedKey: group.seedKey,
						modelId: model.id,
						error:
							groupError instanceof Error
								? {
										name: groupError.name,
										message: groupError.message,
										stack: groupError.stack,
									}
								: { unknownError: String(groupError) },
					});
				}
			}
			return map;
		}
	}

	type GroupResolution = {
		group: CandidateGroup;
		primary: ListwiseLLMResult;
		cascade: ReturnType<typeof decideListwiseCascade>;
		accepted: ListwiseLLMResult;
	};

	// Stage 3: RESOLVE (primary) + Stage 4: PERSIST (after possible escalation)
	for (let offset = 0; offset < processableGroups.length; offset += maxGroupsPerCall) {
		const batch = processableGroups.slice(offset, offset + maxGroupsPerCall);
		processedGroups += batch.length;

		log.info("Unified matching: processing batch", {
			batchIndex: Math.floor(offset / maxGroupsPerCall) + 1,
			batchSize: batch.length,
			primaryModel: primaryModel.id,
			dryRun,
		});

		const primaryByGroupId = await safeProcessBatch(primaryModel, batch);
		const resolutions: GroupResolution[] = [];
		const escalations: CandidateGroup[] = [];
		const escalationCascadeById = new Map<string, ReturnType<typeof decideListwiseCascade>>();
		const primaryResultById = new Map<string, ListwiseLLMResult>();

		for (const group of batch) {
			const primary = primaryByGroupId.get(group.groupId);
			if (!primary) {
				errorGroups += 1;
				continue;
			}

			const groupItemCount = group.items.length;
			const cascade = decideListwiseCascade({
				primary,
				primaryModel,
				secondaryModel,
				itemCount: groupItemCount,
				minPrimaryConfidence: options.minPrimaryConfidence,
			});

			primaryResultById.set(group.groupId, primary);

			await logLlmDecision({
				taskType: "unified_matching",
				input: {
					groupId: group.groupId,
					seedKey: group.seedKey,
					itemCount: groupItemCount,
					items: group.items.map((item) => ({
						id: item.retailerItemId,
						rawName: item.rawName,
						chainSlug: item.chainSlug,
					})),
				},
				output: {
					decision: cascade.shouldEscalate ? "escalate" : "accept",
					reason: cascade.reason,
					primary: {
						modelId: primary.modelId,
						provider: primary.provider,
						confidence: primary.clustering.confidence,
						baseProducts: primary.clustering.baseProducts.length,
						unclassified: primary.clustering.unclassified.length,
						missing: primary.clustering.missingItemIds.length,
						duplicates: primary.clustering.duplicateItemIds.length,
					},
				},
				modelId: primary.modelId,
				provider: primary.provider,
				verdict: cascade.shouldEscalate ? "ESCALATE" : "ACCEPT",
				confidence: primary.clustering.confidence,
				reasoning: cascade.reason,
				latencyMs: primary.totalLatencyMs,
				tokenCount: primary.tokenEstimates.total,
			});

			if (cascade.shouldEscalate) {
				escalatedGroups += 1;
				escalations.push(group);
				escalationCascadeById.set(group.groupId, cascade);
			} else {
				resolutions.push({
					group,
					primary,
					cascade,
					accepted: primary,
				});
			}
		}

		// Secondary verification (batched)
		for (let i = 0; i < escalations.length; i += maxGroupsPerCall) {
			const escalationBatch = escalations.slice(i, i + maxGroupsPerCall);
			log.info("Unified matching: verifying escalation batch", {
				batchIndex: Math.floor(i / maxGroupsPerCall) + 1,
				batchSize: escalationBatch.length,
				secondaryModel: secondaryModel.id,
				dryRun,
			});

			const secondaryByGroupId = await safeProcessBatch(
				secondaryModel,
				escalationBatch,
			);

			for (const group of escalationBatch) {
				const primary = primaryResultById.get(group.groupId);
				const cascade = escalationCascadeById.get(group.groupId);
				const secondary = secondaryByGroupId.get(group.groupId);
				if (!primary || !cascade || !secondary) {
					errorGroups += 1;
					continue;
				}

				await logLlmDecision({
					taskType: "unified_matching_verify",
					input: {
						groupId: group.groupId,
						seedKey: group.seedKey,
						reason: cascade.reason,
					},
					output: {
						primary: {
							modelId: primary.modelId,
							confidence: primary.clustering.confidence,
							baseProducts: primary.clustering.baseProducts.length,
						},
						secondary: {
							modelId: secondary.modelId,
							confidence: secondary.clustering.confidence,
							baseProducts: secondary.clustering.baseProducts.length,
						},
					},
					modelId: secondary.modelId,
					provider: secondary.provider,
					verdict: "VERIFIED",
					confidence: secondary.clustering.confidence,
					reasoning: "Secondary model verification",
					latencyMs: secondary.totalLatencyMs,
					tokenCount: secondary.tokenEstimates.total,
				});

				resolutions.push({
					group,
					primary,
					cascade,
					accepted: secondary,
				});
			}
		}

		// Persist all accepted groupings
		for (const resolution of resolutions) {
			try {
				const persisted = await persistAcceptedGrouping({
					group: resolution.group,
					llm: resolution.accepted,
					dryRun,
				});
				createdSkus += persisted.createdSkus;
				linkedItems += persisted.linkedItems;
			} catch (error) {
				errorGroups += 1;
				log.error("Unified matching: persistence failed", {
					groupId: resolution.group.groupId,
					seedKey: resolution.group.seedKey,
					error:
						error instanceof Error
							? {
									name: error.name,
									message: error.message,
									stack: error.stack,
								}
							: { unknownError: String(error) },
				});
			}
		}
	}

	const result: RunUnifiedMatchingResult = {
		candidateGroups: blocking.groups.length,
		processedGroups,
		skippedGroups,
		escalatedGroups,
		createdSkus,
		linkedItems,
		errorGroups,
		blockingStats: {
			barcodeGroups: blocking.stats.barcodeGroups,
			deterministicGroups: blocking.stats.deterministicGroups,
			embeddingGroups: blocking.stats.embeddingGroups,
			lexicalGroups: blocking.stats.lexicalGroups,
			totalItems: blocking.stats.totalItems,
		},
	};

	log.info("Unified matching completed", { ...result, dryRun });

	return result;
}
