/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as PublicStoresRouteImport } from './routes/_public.stores'
import { Route as PublicSearchRouteImport } from './routes/_public.search'
import { Route as PublicProfileRouteImport } from './routes/_public.profile'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicBasketRouteImport } from './routes/_public.basket'
import { Route as PublicAlertsRouteImport } from './routes/_public.alerts'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as PublicProductProductIdRouteImport } from './routes/_public.product.$productId'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminTaskQueueRouteImport } from './routes/_admin.admin.task-queue'
import { Route as AdminAdminStoresRouteImport } from './routes/_admin.admin.stores'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminMatchingRouteImport } from './routes/_admin.admin.matching'
import { Route as AdminAdminLlmEndpointsRouteImport } from './routes/_admin.admin.llm-endpoints'
import { Route as AdminAdminLlmDecisionsRouteImport } from './routes/_admin.admin.llm-decisions'
import { Route as AdminAdminIngestionRouteImport } from './routes/_admin.admin.ingestion'
import { Route as AdminAdminCronRouteImport } from './routes/_admin.admin.cron'
import { Route as AdminAdminClickhouseRouteImport } from './routes/_admin.admin.clickhouse'
import { Route as AdminAdminCategorizationRouteImport } from './routes/_admin.admin.categorization'
import { Route as AdminAdminCatalogPricesRouteImport } from './routes/_admin.admin.catalog-prices'
import { Route as AdminAdminBarcodeTriageRouteImport } from './routes/_admin.admin.barcode-triage'
import { Route as AdminAdminStoresIndexRouteImport } from './routes/_admin.admin.stores.index'
import { Route as AdminAdminIngestionIndexRouteImport } from './routes/_admin.admin.ingestion.index'
import { Route as AdminAdminConfigIndexRouteImport } from './routes/_admin.admin.config.index'
import { Route as AdminAdminStoresPendingRouteImport } from './routes/_admin.admin.stores.pending'
import { Route as AdminAdminStoresStoreIdRouteImport } from './routes/_admin.admin.stores.$storeId'
import { Route as AdminAdminIngestionRunIdRouteImport } from './routes/_admin.admin.ingestion.$runId'
import { Route as AdminAdminIngestionRunIdFileIdRouteImport } from './routes/_admin.admin.ingestion.$runId.$fileId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicStoresRoute = PublicStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBasketRoute = PublicBasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAlertsRoute = PublicAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProductProductIdRoute = PublicProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTaskQueueRoute = AdminAdminTaskQueueRouteImport.update({
  id: '/task-queue',
  path: '/task-queue',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStoresRoute = AdminAdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMatchingRoute = AdminAdminMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLlmEndpointsRoute = AdminAdminLlmEndpointsRouteImport.update({
  id: '/llm-endpoints',
  path: '/llm-endpoints',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLlmDecisionsRoute = AdminAdminLlmDecisionsRouteImport.update({
  id: '/llm-decisions',
  path: '/llm-decisions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminIngestionRoute = AdminAdminIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCronRoute = AdminAdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminClickhouseRoute = AdminAdminClickhouseRouteImport.update({
  id: '/clickhouse',
  path: '/clickhouse',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCategorizationRoute =
  AdminAdminCategorizationRouteImport.update({
    id: '/categorization',
    path: '/categorization',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminCatalogPricesRoute = AdminAdminCatalogPricesRouteImport.update({
  id: '/catalog-prices',
  path: '/catalog-prices',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBarcodeTriageRoute = AdminAdminBarcodeTriageRouteImport.update({
  id: '/barcode-triage',
  path: '/barcode-triage',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStoresIndexRoute = AdminAdminStoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminStoresRoute,
} as any)
const AdminAdminIngestionIndexRoute =
  AdminAdminIngestionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminIngestionRoute,
  } as any)
const AdminAdminConfigIndexRoute = AdminAdminConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStoresPendingRoute = AdminAdminStoresPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminAdminStoresRoute,
} as any)
const AdminAdminStoresStoreIdRoute = AdminAdminStoresStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => AdminAdminStoresRoute,
} as any)
const AdminAdminIngestionRunIdRoute =
  AdminAdminIngestionRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AdminAdminIngestionRoute,
  } as any)
const AdminAdminIngestionRunIdFileIdRoute =
  AdminAdminIngestionRunIdFileIdRouteImport.update({
    id: '/$fileId',
    path: '/$fileId',
    getParentRoute: () => AdminAdminIngestionRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/alerts': typeof PublicAlertsRoute
  '/basket': typeof PublicBasketRoute
  '/faq': typeof PublicFaqRoute
  '/privacy': typeof PublicPrivacyRoute
  '/profile': typeof PublicProfileRoute
  '/search': typeof PublicSearchRoute
  '/stores': typeof PublicStoresRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/barcode-triage': typeof AdminAdminBarcodeTriageRoute
  '/admin/catalog-prices': typeof AdminAdminCatalogPricesRoute
  '/admin/categorization': typeof AdminAdminCategorizationRoute
  '/admin/clickhouse': typeof AdminAdminClickhouseRoute
  '/admin/cron': typeof AdminAdminCronRoute
  '/admin/ingestion': typeof AdminAdminIngestionRouteWithChildren
  '/admin/llm-decisions': typeof AdminAdminLlmDecisionsRoute
  '/admin/llm-endpoints': typeof AdminAdminLlmEndpointsRoute
  '/admin/matching': typeof AdminAdminMatchingRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/stores': typeof AdminAdminStoresRouteWithChildren
  '/admin/task-queue': typeof AdminAdminTaskQueueRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/product/$productId': typeof PublicProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/ingestion/$runId': typeof AdminAdminIngestionRunIdRouteWithChildren
  '/admin/stores/$storeId': typeof AdminAdminStoresStoreIdRoute
  '/admin/stores/pending': typeof AdminAdminStoresPendingRoute
  '/admin/config/': typeof AdminAdminConfigIndexRoute
  '/admin/ingestion/': typeof AdminAdminIngestionIndexRoute
  '/admin/stores/': typeof AdminAdminStoresIndexRoute
  '/admin/ingestion/$runId/$fileId': typeof AdminAdminIngestionRunIdFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/about': typeof PublicAboutRoute
  '/alerts': typeof PublicAlertsRoute
  '/basket': typeof PublicBasketRoute
  '/faq': typeof PublicFaqRoute
  '/privacy': typeof PublicPrivacyRoute
  '/profile': typeof PublicProfileRoute
  '/search': typeof PublicSearchRoute
  '/stores': typeof PublicStoresRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/barcode-triage': typeof AdminAdminBarcodeTriageRoute
  '/admin/catalog-prices': typeof AdminAdminCatalogPricesRoute
  '/admin/categorization': typeof AdminAdminCategorizationRoute
  '/admin/clickhouse': typeof AdminAdminClickhouseRoute
  '/admin/cron': typeof AdminAdminCronRoute
  '/admin/llm-decisions': typeof AdminAdminLlmDecisionsRoute
  '/admin/llm-endpoints': typeof AdminAdminLlmEndpointsRoute
  '/admin/matching': typeof AdminAdminMatchingRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/task-queue': typeof AdminAdminTaskQueueRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/product/$productId': typeof PublicProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/ingestion/$runId': typeof AdminAdminIngestionRunIdRouteWithChildren
  '/admin/stores/$storeId': typeof AdminAdminStoresStoreIdRoute
  '/admin/stores/pending': typeof AdminAdminStoresPendingRoute
  '/admin/config': typeof AdminAdminConfigIndexRoute
  '/admin/ingestion': typeof AdminAdminIngestionIndexRoute
  '/admin/stores': typeof AdminAdminStoresIndexRoute
  '/admin/ingestion/$runId/$fileId': typeof AdminAdminIngestionRunIdFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/alerts': typeof PublicAlertsRoute
  '/_public/basket': typeof PublicBasketRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/profile': typeof PublicProfileRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/stores': typeof PublicStoresRoute
  '/api/$': typeof ApiSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/barcode-triage': typeof AdminAdminBarcodeTriageRoute
  '/_admin/admin/catalog-prices': typeof AdminAdminCatalogPricesRoute
  '/_admin/admin/categorization': typeof AdminAdminCategorizationRoute
  '/_admin/admin/clickhouse': typeof AdminAdminClickhouseRoute
  '/_admin/admin/cron': typeof AdminAdminCronRoute
  '/_admin/admin/ingestion': typeof AdminAdminIngestionRouteWithChildren
  '/_admin/admin/llm-decisions': typeof AdminAdminLlmDecisionsRoute
  '/_admin/admin/llm-endpoints': typeof AdminAdminLlmEndpointsRoute
  '/_admin/admin/matching': typeof AdminAdminMatchingRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/stores': typeof AdminAdminStoresRouteWithChildren
  '/_admin/admin/task-queue': typeof AdminAdminTaskQueueRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_public/product/$productId': typeof PublicProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/ingestion/$runId': typeof AdminAdminIngestionRunIdRouteWithChildren
  '/_admin/admin/stores/$storeId': typeof AdminAdminStoresStoreIdRoute
  '/_admin/admin/stores/pending': typeof AdminAdminStoresPendingRoute
  '/_admin/admin/config/': typeof AdminAdminConfigIndexRoute
  '/_admin/admin/ingestion/': typeof AdminAdminIngestionIndexRoute
  '/_admin/admin/stores/': typeof AdminAdminStoresIndexRoute
  '/_admin/admin/ingestion/$runId/$fileId': typeof AdminAdminIngestionRunIdFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/admin'
    | '/about'
    | '/alerts'
    | '/basket'
    | '/faq'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/stores'
    | '/api/$'
    | '/admin/barcode-triage'
    | '/admin/catalog-prices'
    | '/admin/categorization'
    | '/admin/clickhouse'
    | '/admin/cron'
    | '/admin/ingestion'
    | '/admin/llm-decisions'
    | '/admin/llm-endpoints'
    | '/admin/matching'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/task-queue'
    | '/admin/users'
    | '/product/$productId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/'
    | '/admin/ingestion/$runId'
    | '/admin/stores/$storeId'
    | '/admin/stores/pending'
    | '/admin/config/'
    | '/admin/ingestion/'
    | '/admin/stores/'
    | '/admin/ingestion/$runId/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/about'
    | '/alerts'
    | '/basket'
    | '/faq'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/stores'
    | '/api/$'
    | '/admin/barcode-triage'
    | '/admin/catalog-prices'
    | '/admin/categorization'
    | '/admin/clickhouse'
    | '/admin/cron'
    | '/admin/llm-decisions'
    | '/admin/llm-endpoints'
    | '/admin/matching'
    | '/admin/settings'
    | '/admin/task-queue'
    | '/admin/users'
    | '/product/$productId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin'
    | '/admin/ingestion/$runId'
    | '/admin/stores/$storeId'
    | '/admin/stores/pending'
    | '/admin/config'
    | '/admin/ingestion'
    | '/admin/stores'
    | '/admin/ingestion/$runId/$fileId'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/login'
    | '/setup'
    | '/_admin/admin'
    | '/_public/about'
    | '/_public/alerts'
    | '/_public/basket'
    | '/_public/faq'
    | '/_public/privacy'
    | '/_public/profile'
    | '/_public/search'
    | '/_public/stores'
    | '/api/$'
    | '/_public/'
    | '/_admin/admin/barcode-triage'
    | '/_admin/admin/catalog-prices'
    | '/_admin/admin/categorization'
    | '/_admin/admin/clickhouse'
    | '/_admin/admin/cron'
    | '/_admin/admin/ingestion'
    | '/_admin/admin/llm-decisions'
    | '/_admin/admin/llm-endpoints'
    | '/_admin/admin/matching'
    | '/_admin/admin/settings'
    | '/_admin/admin/stores'
    | '/_admin/admin/task-queue'
    | '/_admin/admin/users'
    | '/_public/product/$productId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_admin/admin/'
    | '/_admin/admin/ingestion/$runId'
    | '/_admin/admin/stores/$storeId'
    | '/_admin/admin/stores/pending'
    | '/_admin/admin/config/'
    | '/_admin/admin/ingestion/'
    | '/_admin/admin/stores/'
    | '/_admin/admin/ingestion/$runId/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/stores': {
      id: '/_public/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof PublicStoresRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/profile': {
      id: '/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/basket': {
      id: '/_public/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof PublicBasketRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/alerts': {
      id: '/_public/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof PublicAlertsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/product/$productId': {
      id: '/_public/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof PublicProductProductIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/task-queue': {
      id: '/_admin/admin/task-queue'
      path: '/task-queue'
      fullPath: '/admin/task-queue'
      preLoaderRoute: typeof AdminAdminTaskQueueRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/stores': {
      id: '/_admin/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminAdminStoresRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/matching': {
      id: '/_admin/admin/matching'
      path: '/matching'
      fullPath: '/admin/matching'
      preLoaderRoute: typeof AdminAdminMatchingRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/llm-endpoints': {
      id: '/_admin/admin/llm-endpoints'
      path: '/llm-endpoints'
      fullPath: '/admin/llm-endpoints'
      preLoaderRoute: typeof AdminAdminLlmEndpointsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/llm-decisions': {
      id: '/_admin/admin/llm-decisions'
      path: '/llm-decisions'
      fullPath: '/admin/llm-decisions'
      preLoaderRoute: typeof AdminAdminLlmDecisionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/ingestion': {
      id: '/_admin/admin/ingestion'
      path: '/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminAdminIngestionRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/cron': {
      id: '/_admin/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AdminAdminCronRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/clickhouse': {
      id: '/_admin/admin/clickhouse'
      path: '/clickhouse'
      fullPath: '/admin/clickhouse'
      preLoaderRoute: typeof AdminAdminClickhouseRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/categorization': {
      id: '/_admin/admin/categorization'
      path: '/categorization'
      fullPath: '/admin/categorization'
      preLoaderRoute: typeof AdminAdminCategorizationRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/catalog-prices': {
      id: '/_admin/admin/catalog-prices'
      path: '/catalog-prices'
      fullPath: '/admin/catalog-prices'
      preLoaderRoute: typeof AdminAdminCatalogPricesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/barcode-triage': {
      id: '/_admin/admin/barcode-triage'
      path: '/barcode-triage'
      fullPath: '/admin/barcode-triage'
      preLoaderRoute: typeof AdminAdminBarcodeTriageRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/stores/': {
      id: '/_admin/admin/stores/'
      path: '/'
      fullPath: '/admin/stores/'
      preLoaderRoute: typeof AdminAdminStoresIndexRouteImport
      parentRoute: typeof AdminAdminStoresRoute
    }
    '/_admin/admin/ingestion/': {
      id: '/_admin/admin/ingestion/'
      path: '/'
      fullPath: '/admin/ingestion/'
      preLoaderRoute: typeof AdminAdminIngestionIndexRouteImport
      parentRoute: typeof AdminAdminIngestionRoute
    }
    '/_admin/admin/config/': {
      id: '/_admin/admin/config/'
      path: '/config'
      fullPath: '/admin/config/'
      preLoaderRoute: typeof AdminAdminConfigIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/stores/pending': {
      id: '/_admin/admin/stores/pending'
      path: '/pending'
      fullPath: '/admin/stores/pending'
      preLoaderRoute: typeof AdminAdminStoresPendingRouteImport
      parentRoute: typeof AdminAdminStoresRoute
    }
    '/_admin/admin/stores/$storeId': {
      id: '/_admin/admin/stores/$storeId'
      path: '/$storeId'
      fullPath: '/admin/stores/$storeId'
      preLoaderRoute: typeof AdminAdminStoresStoreIdRouteImport
      parentRoute: typeof AdminAdminStoresRoute
    }
    '/_admin/admin/ingestion/$runId': {
      id: '/_admin/admin/ingestion/$runId'
      path: '/$runId'
      fullPath: '/admin/ingestion/$runId'
      preLoaderRoute: typeof AdminAdminIngestionRunIdRouteImport
      parentRoute: typeof AdminAdminIngestionRoute
    }
    '/_admin/admin/ingestion/$runId/$fileId': {
      id: '/_admin/admin/ingestion/$runId/$fileId'
      path: '/$fileId'
      fullPath: '/admin/ingestion/$runId/$fileId'
      preLoaderRoute: typeof AdminAdminIngestionRunIdFileIdRouteImport
      parentRoute: typeof AdminAdminIngestionRunIdRoute
    }
  }
}

interface AdminAdminIngestionRunIdRouteChildren {
  AdminAdminIngestionRunIdFileIdRoute: typeof AdminAdminIngestionRunIdFileIdRoute
}

const AdminAdminIngestionRunIdRouteChildren: AdminAdminIngestionRunIdRouteChildren =
  {
    AdminAdminIngestionRunIdFileIdRoute: AdminAdminIngestionRunIdFileIdRoute,
  }

const AdminAdminIngestionRunIdRouteWithChildren =
  AdminAdminIngestionRunIdRoute._addFileChildren(
    AdminAdminIngestionRunIdRouteChildren,
  )

interface AdminAdminIngestionRouteChildren {
  AdminAdminIngestionRunIdRoute: typeof AdminAdminIngestionRunIdRouteWithChildren
  AdminAdminIngestionIndexRoute: typeof AdminAdminIngestionIndexRoute
}

const AdminAdminIngestionRouteChildren: AdminAdminIngestionRouteChildren = {
  AdminAdminIngestionRunIdRoute: AdminAdminIngestionRunIdRouteWithChildren,
  AdminAdminIngestionIndexRoute: AdminAdminIngestionIndexRoute,
}

const AdminAdminIngestionRouteWithChildren =
  AdminAdminIngestionRoute._addFileChildren(AdminAdminIngestionRouteChildren)

interface AdminAdminStoresRouteChildren {
  AdminAdminStoresStoreIdRoute: typeof AdminAdminStoresStoreIdRoute
  AdminAdminStoresPendingRoute: typeof AdminAdminStoresPendingRoute
  AdminAdminStoresIndexRoute: typeof AdminAdminStoresIndexRoute
}

const AdminAdminStoresRouteChildren: AdminAdminStoresRouteChildren = {
  AdminAdminStoresStoreIdRoute: AdminAdminStoresStoreIdRoute,
  AdminAdminStoresPendingRoute: AdminAdminStoresPendingRoute,
  AdminAdminStoresIndexRoute: AdminAdminStoresIndexRoute,
}

const AdminAdminStoresRouteWithChildren =
  AdminAdminStoresRoute._addFileChildren(AdminAdminStoresRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminBarcodeTriageRoute: typeof AdminAdminBarcodeTriageRoute
  AdminAdminCatalogPricesRoute: typeof AdminAdminCatalogPricesRoute
  AdminAdminCategorizationRoute: typeof AdminAdminCategorizationRoute
  AdminAdminClickhouseRoute: typeof AdminAdminClickhouseRoute
  AdminAdminCronRoute: typeof AdminAdminCronRoute
  AdminAdminIngestionRoute: typeof AdminAdminIngestionRouteWithChildren
  AdminAdminLlmDecisionsRoute: typeof AdminAdminLlmDecisionsRoute
  AdminAdminLlmEndpointsRoute: typeof AdminAdminLlmEndpointsRoute
  AdminAdminMatchingRoute: typeof AdminAdminMatchingRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminStoresRoute: typeof AdminAdminStoresRouteWithChildren
  AdminAdminTaskQueueRoute: typeof AdminAdminTaskQueueRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminConfigIndexRoute: typeof AdminAdminConfigIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminBarcodeTriageRoute: AdminAdminBarcodeTriageRoute,
  AdminAdminCatalogPricesRoute: AdminAdminCatalogPricesRoute,
  AdminAdminCategorizationRoute: AdminAdminCategorizationRoute,
  AdminAdminClickhouseRoute: AdminAdminClickhouseRoute,
  AdminAdminCronRoute: AdminAdminCronRoute,
  AdminAdminIngestionRoute: AdminAdminIngestionRouteWithChildren,
  AdminAdminLlmDecisionsRoute: AdminAdminLlmDecisionsRoute,
  AdminAdminLlmEndpointsRoute: AdminAdminLlmEndpointsRoute,
  AdminAdminMatchingRoute: AdminAdminMatchingRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminStoresRoute: AdminAdminStoresRouteWithChildren,
  AdminAdminTaskQueueRoute: AdminAdminTaskQueueRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminConfigIndexRoute: AdminAdminConfigIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAlertsRoute: typeof PublicAlertsRoute
  PublicBasketRoute: typeof PublicBasketRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicProfileRoute: typeof PublicProfileRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicStoresRoute: typeof PublicStoresRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProductProductIdRoute: typeof PublicProductProductIdRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAlertsRoute: PublicAlertsRoute,
  PublicBasketRoute: PublicBasketRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicProfileRoute: PublicProfileRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicStoresRoute: PublicStoresRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProductProductIdRoute: PublicProductProductIdRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
