/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminStoresRouteImport } from './routes/_admin.admin.stores'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminIngestionRouteImport } from './routes/_admin.admin.ingestion'
import { Route as AdminAdminCatalogPricesRouteImport } from './routes/_admin.admin.catalog-prices'
import { Route as AdminAdminStoresIndexRouteImport } from './routes/_admin.admin.stores.index'
import { Route as AdminAdminIngestionIndexRouteImport } from './routes/_admin.admin.ingestion.index'
import { Route as AdminAdminConfigIndexRouteImport } from './routes/_admin.admin.config.index'
import { Route as AdminAdminStoresPendingRouteImport } from './routes/_admin.admin.stores.pending'
import { Route as AdminAdminStoresStoreIdRouteImport } from './routes/_admin.admin.stores.$storeId'
import { Route as AdminAdminIngestionRunIdRouteImport } from './routes/_admin.admin.ingestion.$runId'
import { Route as AdminAdminIngestionRunIdFileIdRouteImport } from './routes/_admin.admin.ingestion.$runId.$fileId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStoresRoute = AdminAdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminIngestionRoute = AdminAdminIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCatalogPricesRoute = AdminAdminCatalogPricesRouteImport.update({
  id: '/catalog-prices',
  path: '/catalog-prices',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStoresIndexRoute = AdminAdminStoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminStoresRoute,
} as any)
const AdminAdminIngestionIndexRoute =
  AdminAdminIngestionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminIngestionRoute,
  } as any)
const AdminAdminConfigIndexRoute = AdminAdminConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStoresPendingRoute = AdminAdminStoresPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminAdminStoresRoute,
} as any)
const AdminAdminStoresStoreIdRoute = AdminAdminStoresStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => AdminAdminStoresRoute,
} as any)
const AdminAdminIngestionRunIdRoute =
  AdminAdminIngestionRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AdminAdminIngestionRoute,
  } as any)
const AdminAdminIngestionRunIdFileIdRoute =
  AdminAdminIngestionRunIdFileIdRouteImport.update({
    id: '/$fileId',
    path: '/$fileId',
    getParentRoute: () => AdminAdminIngestionRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/admin/catalog-prices': typeof AdminAdminCatalogPricesRoute
  '/admin/ingestion': typeof AdminAdminIngestionRouteWithChildren
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/stores': typeof AdminAdminStoresRouteWithChildren
  '/admin/users': typeof AdminAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/ingestion/$runId': typeof AdminAdminIngestionRunIdRouteWithChildren
  '/admin/stores/$storeId': typeof AdminAdminStoresStoreIdRoute
  '/admin/stores/pending': typeof AdminAdminStoresPendingRoute
  '/admin/config': typeof AdminAdminConfigIndexRoute
  '/admin/ingestion/': typeof AdminAdminIngestionIndexRoute
  '/admin/stores/': typeof AdminAdminStoresIndexRoute
  '/admin/ingestion/$runId/$fileId': typeof AdminAdminIngestionRunIdFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/catalog-prices': typeof AdminAdminCatalogPricesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/ingestion/$runId': typeof AdminAdminIngestionRunIdRouteWithChildren
  '/admin/stores/$storeId': typeof AdminAdminStoresStoreIdRoute
  '/admin/stores/pending': typeof AdminAdminStoresPendingRoute
  '/admin/config': typeof AdminAdminConfigIndexRoute
  '/admin/ingestion': typeof AdminAdminIngestionIndexRoute
  '/admin/stores': typeof AdminAdminStoresIndexRoute
  '/admin/ingestion/$runId/$fileId': typeof AdminAdminIngestionRunIdFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_admin/admin/catalog-prices': typeof AdminAdminCatalogPricesRoute
  '/_admin/admin/ingestion': typeof AdminAdminIngestionRouteWithChildren
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/stores': typeof AdminAdminStoresRouteWithChildren
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/ingestion/$runId': typeof AdminAdminIngestionRunIdRouteWithChildren
  '/_admin/admin/stores/$storeId': typeof AdminAdminStoresStoreIdRoute
  '/_admin/admin/stores/pending': typeof AdminAdminStoresPendingRoute
  '/_admin/admin/config/': typeof AdminAdminConfigIndexRoute
  '/_admin/admin/ingestion/': typeof AdminAdminIngestionIndexRoute
  '/_admin/admin/stores/': typeof AdminAdminStoresIndexRoute
  '/_admin/admin/ingestion/$runId/$fileId': typeof AdminAdminIngestionRunIdFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/admin'
    | '/api/$'
    | '/admin/catalog-prices'
    | '/admin/ingestion'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/'
    | '/admin/ingestion/$runId'
    | '/admin/stores/$storeId'
    | '/admin/stores/pending'
    | '/admin/config'
    | '/admin/ingestion/'
    | '/admin/stores/'
    | '/admin/ingestion/$runId/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/api/$'
    | '/admin/catalog-prices'
    | '/admin/settings'
    | '/admin/users'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin'
    | '/admin/ingestion/$runId'
    | '/admin/stores/$storeId'
    | '/admin/stores/pending'
    | '/admin/config'
    | '/admin/ingestion'
    | '/admin/stores'
    | '/admin/ingestion/$runId/$fileId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/setup'
    | '/_admin/admin'
    | '/api/$'
    | '/_admin/admin/catalog-prices'
    | '/_admin/admin/ingestion'
    | '/_admin/admin/settings'
    | '/_admin/admin/stores'
    | '/_admin/admin/users'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_admin/admin/'
    | '/_admin/admin/ingestion/$runId'
    | '/_admin/admin/stores/$storeId'
    | '/_admin/admin/stores/pending'
    | '/_admin/admin/config/'
    | '/_admin/admin/ingestion/'
    | '/_admin/admin/stores/'
    | '/_admin/admin/ingestion/$runId/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/stores': {
      id: '/_admin/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminAdminStoresRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/ingestion': {
      id: '/_admin/admin/ingestion'
      path: '/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminAdminIngestionRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/catalog-prices': {
      id: '/_admin/admin/catalog-prices'
      path: '/catalog-prices'
      fullPath: '/admin/catalog-prices'
      preLoaderRoute: typeof AdminAdminCatalogPricesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/stores/': {
      id: '/_admin/admin/stores/'
      path: '/'
      fullPath: '/admin/stores/'
      preLoaderRoute: typeof AdminAdminStoresIndexRouteImport
      parentRoute: typeof AdminAdminStoresRoute
    }
    '/_admin/admin/ingestion/': {
      id: '/_admin/admin/ingestion/'
      path: '/'
      fullPath: '/admin/ingestion/'
      preLoaderRoute: typeof AdminAdminIngestionIndexRouteImport
      parentRoute: typeof AdminAdminIngestionRoute
    }
    '/_admin/admin/config/': {
      id: '/_admin/admin/config/'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminAdminConfigIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/stores/pending': {
      id: '/_admin/admin/stores/pending'
      path: '/pending'
      fullPath: '/admin/stores/pending'
      preLoaderRoute: typeof AdminAdminStoresPendingRouteImport
      parentRoute: typeof AdminAdminStoresRoute
    }
    '/_admin/admin/stores/$storeId': {
      id: '/_admin/admin/stores/$storeId'
      path: '/$storeId'
      fullPath: '/admin/stores/$storeId'
      preLoaderRoute: typeof AdminAdminStoresStoreIdRouteImport
      parentRoute: typeof AdminAdminStoresRoute
    }
    '/_admin/admin/ingestion/$runId': {
      id: '/_admin/admin/ingestion/$runId'
      path: '/$runId'
      fullPath: '/admin/ingestion/$runId'
      preLoaderRoute: typeof AdminAdminIngestionRunIdRouteImport
      parentRoute: typeof AdminAdminIngestionRoute
    }
    '/_admin/admin/ingestion/$runId/$fileId': {
      id: '/_admin/admin/ingestion/$runId/$fileId'
      path: '/$fileId'
      fullPath: '/admin/ingestion/$runId/$fileId'
      preLoaderRoute: typeof AdminAdminIngestionRunIdFileIdRouteImport
      parentRoute: typeof AdminAdminIngestionRunIdRoute
    }
  }
}

interface AdminAdminIngestionRunIdRouteChildren {
  AdminAdminIngestionRunIdFileIdRoute: typeof AdminAdminIngestionRunIdFileIdRoute
}

const AdminAdminIngestionRunIdRouteChildren: AdminAdminIngestionRunIdRouteChildren =
  {
    AdminAdminIngestionRunIdFileIdRoute: AdminAdminIngestionRunIdFileIdRoute,
  }

const AdminAdminIngestionRunIdRouteWithChildren =
  AdminAdminIngestionRunIdRoute._addFileChildren(
    AdminAdminIngestionRunIdRouteChildren,
  )

interface AdminAdminIngestionRouteChildren {
  AdminAdminIngestionRunIdRoute: typeof AdminAdminIngestionRunIdRouteWithChildren
  AdminAdminIngestionIndexRoute: typeof AdminAdminIngestionIndexRoute
}

const AdminAdminIngestionRouteChildren: AdminAdminIngestionRouteChildren = {
  AdminAdminIngestionRunIdRoute: AdminAdminIngestionRunIdRouteWithChildren,
  AdminAdminIngestionIndexRoute: AdminAdminIngestionIndexRoute,
}

const AdminAdminIngestionRouteWithChildren =
  AdminAdminIngestionRoute._addFileChildren(AdminAdminIngestionRouteChildren)

interface AdminAdminStoresRouteChildren {
  AdminAdminStoresStoreIdRoute: typeof AdminAdminStoresStoreIdRoute
  AdminAdminStoresPendingRoute: typeof AdminAdminStoresPendingRoute
  AdminAdminStoresIndexRoute: typeof AdminAdminStoresIndexRoute
}

const AdminAdminStoresRouteChildren: AdminAdminStoresRouteChildren = {
  AdminAdminStoresStoreIdRoute: AdminAdminStoresStoreIdRoute,
  AdminAdminStoresPendingRoute: AdminAdminStoresPendingRoute,
  AdminAdminStoresIndexRoute: AdminAdminStoresIndexRoute,
}

const AdminAdminStoresRouteWithChildren =
  AdminAdminStoresRoute._addFileChildren(AdminAdminStoresRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminCatalogPricesRoute: typeof AdminAdminCatalogPricesRoute
  AdminAdminIngestionRoute: typeof AdminAdminIngestionRouteWithChildren
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminStoresRoute: typeof AdminAdminStoresRouteWithChildren
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminConfigIndexRoute: typeof AdminAdminConfigIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminCatalogPricesRoute: AdminAdminCatalogPricesRoute,
  AdminAdminIngestionRoute: AdminAdminIngestionRouteWithChildren,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminStoresRoute: AdminAdminStoresRouteWithChildren,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminConfigIndexRoute: AdminAdminConfigIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
