// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/basket/cache/health": {
            "get": {
                "description": "Returns the health status and freshness information for all cached chains",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Get cache health",
                "responses": {
                    "200": {
                        "description": "Cache health status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Cache not initialized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/basket/cache/refresh/{chainSlug}": {
            "post": {
                "description": "Refreshes the price cache for a specific chain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Refresh chain cache",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain slug identifier",
                        "name": "chainSlug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cache refreshed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Cache not initialized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/basket/cache/warmup": {
            "post": {
                "description": "Triggers a full cache warmup for all chains",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Warm up price cache",
                "responses": {
                    "200": {
                        "description": "Cache warmed up",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Cache not initialized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/basket/optimize/multi": {
            "post": {
                "description": "Finds the optimal distribution of basket items across multiple stores",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "basket"
                ],
                "summary": "Optimize basket across multiple stores",
                "parameters": [
                    {
                        "description": "Optimization request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.OptimizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MultiStoreResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Cache unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "504": {
                        "description": "Optimization timed out",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/basket/optimize/single": {
            "post": {
                "description": "Finds the best single store for a basket of items based on price and coverage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "basket"
                ],
                "summary": "Optimize basket for single store",
                "parameters": [
                    {
                        "description": "Optimization request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.OptimizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Optimization results",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Cache unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/ingestion/runs": {
            "get": {
                "description": "Returns a paginated list of ingestion runs with optional chain and status filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "List ingestion runs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by chain slug",
                        "name": "chainSlug",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "pending",
                            "running",
                            "completed",
                            "failed"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListRunsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/ingestion/runs/{runId}": {
            "get": {
                "description": "Returns a single ingestion run by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Get ingestion run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.IngestionRun"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Run not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an ingestion run and all its associated files and errors",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Delete ingestion run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Run deleted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Run not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/ingestion/runs/{runId}/errors": {
            "get": {
                "description": "Returns a paginated list of errors for a specific ingestion run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "List ingestion errors",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListErrorsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/ingestion/runs/{runId}/files": {
            "get": {
                "description": "Returns a paginated list of files for a specific ingestion run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "List ingestion files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListFilesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/ingestion/runs/{runId}/rerun": {
            "post": {
                "description": "Creates a new run that reruns a specific file, chunk, or entry from an existing run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Rerun ingestion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Original run ID",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rerun request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RerunRunRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Rerun created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Run not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/ingestion/stats": {
            "get": {
                "description": "Returns aggregated statistics for ingestion runs within a time range (24h/7d/30d buckets)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Get ingestion stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (RFC3339 format)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date (RFC3339 format)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetStatsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/items/search": {
            "get": {
                "description": "Search for items by name with optional chain filter. Requires minimum 3 characters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Search items",
                "parameters": [
                    {
                        "minLength": 3,
                        "type": "string",
                        "description": "Search query (min 3 chars)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by chain slug",
                        "name": "chainSlug",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchItemsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/prices/{chainSlug}/{storeId}": {
            "get": {
                "description": "Returns paginated prices for a specific store in a chain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Get store prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain slug identifier",
                        "name": "chainSlug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "storeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 500,
                        "minimum": 1,
                        "type": "integer",
                        "default": 100,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetStorePricesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.BasketItem": {
            "type": "object",
            "required": [
                "itemId",
                "name",
                "quantity"
            ],
            "properties": {
                "itemId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "handlers.GetStatsResponse": {
            "type": "object",
            "properties": {
                "buckets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.StatsBucket"
                    }
                }
            }
        },
        "handlers.GetStorePricesResponse": {
            "type": "object",
            "properties": {
                "prices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.StorePrice"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.IngestionError": {
            "type": "object",
            "properties": {
                "chunkId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "entryId": {
                    "type": "string"
                },
                "errorDetails": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "errorType": {
                    "type": "string"
                },
                "fileId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "runId": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            }
        },
        "handlers.IngestionFile": {
            "type": "object",
            "properties": {
                "chunkSize": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "entryCount": {
                    "type": "integer"
                },
                "fileHash": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "fileType": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "processedAt": {
                    "type": "string"
                },
                "processedChunks": {
                    "type": "integer"
                },
                "runId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalChunks": {
                    "type": "integer"
                }
            }
        },
        "handlers.IngestionRun": {
            "type": "object",
            "properties": {
                "chainSlug": {
                    "type": "string"
                },
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "errorCount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "processedEntries": {
                    "type": "integer"
                },
                "processedFiles": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalEntries": {
                    "type": "integer"
                },
                "totalFiles": {
                    "type": "integer"
                }
            }
        },
        "handlers.ItemPriceInfo": {
            "type": "object",
            "properties": {
                "basePrice": {
                    "type": "integer"
                },
                "discountPrice": {
                    "type": "integer"
                },
                "effectivePrice": {
                    "type": "integer"
                },
                "hasDiscount": {
                    "type": "boolean"
                },
                "itemId": {
                    "type": "string"
                },
                "itemName": {
                    "type": "string"
                },
                "lineTotal": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "handlers.ListErrorsResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.IngestionError"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.ListFilesResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.IngestionFile"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.ListRunsResponse": {
            "type": "object",
            "properties": {
                "runs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.IngestionRun"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.Location": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                }
            }
        },
        "handlers.MissingItem": {
            "type": "object",
            "properties": {
                "isOptional": {
                    "type": "boolean"
                },
                "itemId": {
                    "type": "string"
                },
                "itemName": {
                    "type": "string"
                },
                "penalty": {
                    "type": "integer"
                }
            }
        },
        "handlers.MultiStoreResult": {
            "type": "object",
            "properties": {
                "algorithmUsed": {
                    "type": "string"
                },
                "combinedTotal": {
                    "type": "integer"
                },
                "coverageRatio": {
                    "type": "number"
                },
                "stores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.StoreAllocation"
                    }
                },
                "unassignedItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.MissingItem"
                    }
                }
            }
        },
        "handlers.OptimizeRequest": {
            "type": "object",
            "required": [
                "basketItems",
                "chainSlug"
            ],
            "properties": {
                "basketItems": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/handlers.BasketItem"
                    }
                },
                "chainSlug": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/handlers.Location"
                },
                "maxDistance": {
                    "type": "number"
                },
                "maxStores": {
                    "type": "integer"
                }
            }
        },
        "handlers.RerunRunRequest": {
            "type": "object",
            "required": [
                "rerunType",
                "targetId"
            ],
            "properties": {
                "rerunType": {
                    "description": "\"file\", \"chunk\", \"entry\"",
                    "type": "string"
                },
                "targetId": {
                    "description": "ID of file/chunk/entry to rerun",
                    "type": "string"
                }
            }
        },
        "handlers.SearchItem": {
            "type": "object",
            "properties": {
                "avgPrice": {
                    "description": "Average price across stores",
                    "type": "integer"
                },
                "brand": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "chainSlug": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "externalId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "storeCount": {
                    "description": "Number of stores with this item",
                    "type": "integer"
                },
                "subcategory": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "unitQuantity": {
                    "type": "string"
                }
            }
        },
        "handlers.SearchItemsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SearchItem"
                    }
                },
                "query": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.StatsBucket": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "failed": {
                    "type": "integer"
                },
                "label": {
                    "description": "\"24h\", \"7d\", \"30d\"",
                    "type": "string"
                },
                "pending": {
                    "type": "integer"
                },
                "running": {
                    "type": "integer"
                },
                "totalErrors": {
                    "type": "integer"
                },
                "totalFiles": {
                    "type": "integer"
                },
                "totalRuns": {
                    "type": "integer"
                }
            }
        },
        "handlers.StoreAllocation": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ItemPriceInfo"
                    }
                },
                "storeId": {
                    "type": "string"
                },
                "storeTotal": {
                    "type": "integer"
                },
                "visitOrder": {
                    "type": "integer"
                }
            }
        },
        "handlers.StorePrice": {
            "type": "object",
            "properties": {
                "anchorPrice": {
                    "type": "integer"
                },
                "brand": {
                    "type": "string"
                },
                "currentPrice": {
                    "type": "integer"
                },
                "discountEnd": {
                    "type": "string"
                },
                "discountPrice": {
                    "type": "integer"
                },
                "discountStart": {
                    "type": "string"
                },
                "inStock": {
                    "type": "boolean"
                },
                "itemExternalId": {
                    "type": "string"
                },
                "itemName": {
                    "type": "string"
                },
                "lastSeenAt": {
                    "type": "string"
                },
                "lowestPrice30d": {
                    "type": "integer"
                },
                "previousPrice": {
                    "type": "integer"
                },
                "priceSignature": {
                    "type": "string"
                },
                "retailerItemId": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "unitPrice": {
                    "type": "integer"
                },
                "unitPriceBaseQuantity": {
                    "type": "string"
                },
                "unitPriceBaseUnit": {
                    "type": "string"
                },
                "unitQuantity": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/internal",
	Schemes:          []string{},
	Title:            "Price Service API",
	Description:      "Internal API for price data management, ingestion monitoring, and basket optimization.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
