// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: archives.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArchiveByChecksum = `-- name: GetArchiveByChecksum :one
SELECT id, chain_slug, source_url, filename, original_format,
    archive_path, archive_type, content_type, file_size,
    compressed_size, checksum, downloaded_at, metadata,
    created_at, updated_at
FROM archives
WHERE checksum = $1
LIMIT 1
`

func (q *Queries) GetArchiveByChecksum(ctx context.Context, checksum string) (Archive, error) {
	row := q.db.QueryRow(ctx, getArchiveByChecksum, checksum)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.SourceUrl,
		&i.Filename,
		&i.OriginalFormat,
		&i.ArchivePath,
		&i.ArchiveType,
		&i.ContentType,
		&i.FileSize,
		&i.CompressedSize,
		&i.Checksum,
		&i.DownloadedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArchiveById = `-- name: GetArchiveById :one
SELECT id, chain_slug, source_url, filename, original_format,
    archive_path, archive_type, content_type, file_size,
    compressed_size, checksum, downloaded_at, metadata,
    created_at, updated_at
FROM archives
WHERE id = $1
`

func (q *Queries) GetArchiveById(ctx context.Context, id string) (Archive, error) {
	row := q.db.QueryRow(ctx, getArchiveById, id)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.SourceUrl,
		&i.Filename,
		&i.OriginalFormat,
		&i.ArchivePath,
		&i.ArchiveType,
		&i.ContentType,
		&i.FileSize,
		&i.CompressedSize,
		&i.Checksum,
		&i.DownloadedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkArchiveToRun = `-- name: LinkArchiveToRun :exec
UPDATE ingestion_runs
SET archive_id = $1,
    source_url = (
        SELECT source_url FROM archives WHERE archives.id = $1
    )
WHERE ingestion_runs.id = $2
`

type LinkArchiveToRunParams struct {
	ArchiveID pgtype.Text `db:"archive_id" json:"archive_id"`
	ID        string      `db:"id" json:"id"`
}

func (q *Queries) LinkArchiveToRun(ctx context.Context, arg LinkArchiveToRunParams) error {
	_, err := q.db.Exec(ctx, linkArchiveToRun, arg.ArchiveID, arg.ID)
	return err
}

const listArchivesByChain = `-- name: ListArchivesByChain :many
SELECT id, chain_slug, source_url, filename, original_format,
    archive_path, archive_type, content_type, file_size,
    compressed_size, checksum, downloaded_at, metadata,
    created_at, updated_at
FROM archives
WHERE chain_slug = $1
ORDER BY downloaded_at DESC
LIMIT $2 OFFSET $3
`

type ListArchivesByChainParams struct {
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListArchivesByChain(ctx context.Context, arg ListArchivesByChainParams) ([]Archive, error) {
	rows, err := q.db.Query(ctx, listArchivesByChain, arg.ChainSlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Archive{}
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.SourceUrl,
			&i.Filename,
			&i.OriginalFormat,
			&i.ArchivePath,
			&i.ArchiveType,
			&i.ContentType,
			&i.FileSize,
			&i.CompressedSize,
			&i.Checksum,
			&i.DownloadedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArchive = `-- name: UpsertArchive :exec
INSERT INTO archives (
    id, chain_slug, source_url, filename, original_format,
    archive_path, archive_type, content_type, file_size,
    compressed_size, checksum, downloaded_at, metadata,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (id) DO UPDATE SET
    source_url = EXCLUDED.source_url,
    filename = EXCLUDED.filename,
    archive_path = EXCLUDED.archive_path,
    original_format = EXCLUDED.original_format,
    archive_type = EXCLUDED.archive_type,
    content_type = EXCLUDED.content_type,
    file_size = EXCLUDED.file_size,
    compressed_size = EXCLUDED.compressed_size,
    checksum = EXCLUDED.checksum,
    downloaded_at = EXCLUDED.downloaded_at,
    metadata = EXCLUDED.metadata,
    updated_at = EXCLUDED.updated_at
`

type UpsertArchiveParams struct {
	ID             string             `db:"id" json:"id"`
	ChainSlug      string             `db:"chain_slug" json:"chain_slug"`
	SourceUrl      string             `db:"source_url" json:"source_url"`
	Filename       string             `db:"filename" json:"filename"`
	OriginalFormat string             `db:"original_format" json:"original_format"`
	ArchivePath    string             `db:"archive_path" json:"archive_path"`
	ArchiveType    string             `db:"archive_type" json:"archive_type"`
	ContentType    pgtype.Text        `db:"content_type" json:"content_type"`
	FileSize       pgtype.Int8        `db:"file_size" json:"file_size"`
	CompressedSize pgtype.Int8        `db:"compressed_size" json:"compressed_size"`
	Checksum       string             `db:"checksum" json:"checksum"`
	DownloadedAt   pgtype.Timestamptz `db:"downloaded_at" json:"downloaded_at"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertArchive(ctx context.Context, arg UpsertArchiveParams) error {
	_, err := q.db.Exec(ctx, upsertArchive,
		arg.ID,
		arg.ChainSlug,
		arg.SourceUrl,
		arg.Filename,
		arg.OriginalFormat,
		arg.ArchivePath,
		arg.ArchiveType,
		arg.ContentType,
		arg.FileSize,
		arg.CompressedSize,
		arg.Checksum,
		arg.DownloadedAt,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
