// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chunks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIngestionChunksByFileID = `-- name: CountIngestionChunksByFileID :one
SELECT COUNT(*)
FROM ingestion_chunks
WHERE file_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type CountIngestionChunksByFileIDParams struct {
	FileID int64       `db:"file_id" json:"file_id"`
	Status pgtype.Text `db:"status" json:"status"`
}

func (q *Queries) CountIngestionChunksByFileID(ctx context.Context, arg CountIngestionChunksByFileIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestionChunksByFileID, arg.FileID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listIngestionChunksByFileID = `-- name: ListIngestionChunksByFileID :many
SELECT id, file_id, chunk_index, start_row, end_row, row_count, status,
       r2_key, persisted_count, error_count, processed_at, created_at
FROM ingestion_chunks
WHERE file_id = $1
  AND ($4::text IS NULL OR status = $4)
ORDER BY chunk_index ASC
LIMIT $2 OFFSET $3
`

type ListIngestionChunksByFileIDParams struct {
	FileID int64       `db:"file_id" json:"file_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
	Status pgtype.Text `db:"status" json:"status"`
}

func (q *Queries) ListIngestionChunksByFileID(ctx context.Context, arg ListIngestionChunksByFileIDParams) ([]IngestionChunk, error) {
	rows, err := q.db.Query(ctx, listIngestionChunksByFileID,
		arg.FileID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionChunk{}
	for rows.Next() {
		var i IngestionChunk
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.ChunkIndex,
			&i.StartRow,
			&i.EndRow,
			&i.RowCount,
			&i.Status,
			&i.R2Key,
			&i.PersistedCount,
			&i.ErrorCount,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
