// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOldAuditLogs = `-- name: CountOldAuditLogs :one
SELECT COUNT(*) FROM product_match_audit WHERE created_at < $1
`

func (q *Queries) CountOldAuditLogs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countOldAuditLogs, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOldCandidates = `-- name: CountOldCandidates :one
SELECT COUNT(*) FROM product_match_candidates WHERE created_at < $1
`

func (q *Queries) CountOldCandidates(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countOldCandidates, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaleQueueItems = `-- name: CountStaleQueueItems :one
SELECT COUNT(*) FROM product_match_queue WHERE status = 'pending' AND created_at < $1
`

func (q *Queries) CountStaleQueueItems(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countStaleQueueItems, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :execrows
DELETE FROM product_match_audit
WHERE created_at < $1
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAuditLogs, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldCandidates = `-- name: DeleteOldCandidates :execrows

DELETE FROM product_match_candidates
WHERE created_at < $1
`

// Cleanup job queries
func (q *Queries) DeleteOldCandidates(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldCandidates, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markStaleQueueItemsSkipped = `-- name: MarkStaleQueueItemsSkipped :execrows
UPDATE product_match_queue
SET status = 'skipped',
    reviewed_at = now()
WHERE status = 'pending'
AND created_at < $1
`

func (q *Queries) MarkStaleQueueItemsSkipped(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleQueueItemsSkipped, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
