// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: errors.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countErrorsByDateRange = `-- name: CountErrorsByDateRange :one
SELECT COUNT(*)
FROM ingestion_errors
WHERE created_at >= $1 AND created_at <= $2
`

type CountErrorsByDateRangeParams struct {
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `db:"created_at_2" json:"created_at_2"`
}

func (q *Queries) CountErrorsByDateRange(ctx context.Context, arg CountErrorsByDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countErrorsByDateRange, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIngestionErrors = `-- name: CountIngestionErrors :one
SELECT COUNT(*) FROM ingestion_errors WHERE run_id = $1
`

func (q *Queries) CountIngestionErrors(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestionErrors, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIngestionErrorsByFileID = `-- name: CountIngestionErrorsByFileID :one
SELECT COUNT(*) FROM ingestion_errors WHERE file_id = $1
`

func (q *Queries) CountIngestionErrorsByFileID(ctx context.Context, fileID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestionErrorsByFileID, fileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngestionError = `-- name: CreateIngestionError :exec
INSERT INTO ingestion_errors (
    run_id, file_id, chunk_id, entry_id, error_type, error_message,
    error_details, severity, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
`

type CreateIngestionErrorParams struct {
	RunID        string      `db:"run_id" json:"run_id"`
	FileID       pgtype.Int8 `db:"file_id" json:"file_id"`
	ChunkID      pgtype.Text `db:"chunk_id" json:"chunk_id"`
	EntryID      pgtype.Text `db:"entry_id" json:"entry_id"`
	ErrorType    string      `db:"error_type" json:"error_type"`
	ErrorMessage string      `db:"error_message" json:"error_message"`
	ErrorDetails pgtype.Text `db:"error_details" json:"error_details"`
	Severity     string      `db:"severity" json:"severity"`
}

func (q *Queries) CreateIngestionError(ctx context.Context, arg CreateIngestionErrorParams) error {
	_, err := q.db.Exec(ctx, createIngestionError,
		arg.RunID,
		arg.FileID,
		arg.ChunkID,
		arg.EntryID,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.ErrorDetails,
		arg.Severity,
	)
	return err
}

const listIngestionErrors = `-- name: ListIngestionErrors :many
SELECT id, run_id, file_id, chunk_id, entry_id, error_type, error_message,
       error_details, severity, created_at
FROM ingestion_errors
WHERE run_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListIngestionErrorsParams struct {
	RunID  string `db:"run_id" json:"run_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListIngestionErrors(ctx context.Context, arg ListIngestionErrorsParams) ([]IngestionError, error) {
	rows, err := q.db.Query(ctx, listIngestionErrors, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionError{}
	for rows.Next() {
		var i IngestionError
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FileID,
			&i.ChunkID,
			&i.EntryID,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.Severity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestionErrorsByFileID = `-- name: ListIngestionErrorsByFileID :many
SELECT id, run_id, file_id, chunk_id, entry_id, error_type, error_message,
       error_details, severity, created_at
FROM ingestion_errors
WHERE file_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListIngestionErrorsByFileIDParams struct {
	FileID pgtype.Int8 `db:"file_id" json:"file_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListIngestionErrorsByFileID(ctx context.Context, arg ListIngestionErrorsByFileIDParams) ([]IngestionError, error) {
	rows, err := q.db.Query(ctx, listIngestionErrorsByFileID, arg.FileID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionError{}
	for rows.Next() {
		var i IngestionError
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FileID,
			&i.ChunkID,
			&i.EntryID,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.Severity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
