// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: error_summary.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getErrorSummaryByChain = `-- name: GetErrorSummaryByChain :many
SELECT
    chain_slug,
    COUNT(*) as total_rows,
    COUNT(*) as failed_rows,
    MIN(failed_at) as first_failed,
    MAX(failed_at) as last_failed
FROM retailer_items_failed
WHERE failed_at >= $1
GROUP BY chain_slug
`

type GetErrorSummaryByChainRow struct {
	ChainSlug   string      `db:"chain_slug" json:"chain_slug"`
	TotalRows   int64       `db:"total_rows" json:"total_rows"`
	FailedRows  int64       `db:"failed_rows" json:"failed_rows"`
	FirstFailed interface{} `db:"first_failed" json:"first_failed"`
	LastFailed  interface{} `db:"last_failed" json:"last_failed"`
}

func (q *Queries) GetErrorSummaryByChain(ctx context.Context, failedAt pgtype.Timestamp) ([]GetErrorSummaryByChainRow, error) {
	rows, err := q.db.Query(ctx, getErrorSummaryByChain, failedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetErrorSummaryByChainRow{}
	for rows.Next() {
		var i GetErrorSummaryByChainRow
		if err := rows.Scan(
			&i.ChainSlug,
			&i.TotalRows,
			&i.FailedRows,
			&i.FirstFailed,
			&i.LastFailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
