// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failed_rows.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kosarica/price-service/internal/jsonb"
)

const countFailedRows = `-- name: CountFailedRows :one
SELECT COUNT(*) FROM retailer_items_failed
WHERE chain_slug = $1
`

func (q *Queries) CountFailedRows(ctx context.Context, chainSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedRows, chainSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFailedRow = `-- name: CreateFailedRow :exec
INSERT INTO retailer_items_failed (
    id, chain_slug, run_id, file_id, store_identifier, row_number,
    raw_data, validation_errors, failed_at, reprocessable
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), true)
`

type CreateFailedRowParams struct {
	ID               string                 `db:"id" json:"id"`
	ChainSlug        string                 `db:"chain_slug" json:"chain_slug"`
	RunID            pgtype.Text            `db:"run_id" json:"run_id"`
	FileID           pgtype.Int8            `db:"file_id" json:"file_id"`
	StoreIdentifier  pgtype.Text            `db:"store_identifier" json:"store_identifier"`
	RowNumber        pgtype.Int4            `db:"row_number" json:"row_number"`
	RawData          string                 `db:"raw_data" json:"raw_data"`
	ValidationErrors jsonb.ValidationErrors `db:"validation_errors" json:"validation_errors"`
}

func (q *Queries) CreateFailedRow(ctx context.Context, arg CreateFailedRowParams) error {
	_, err := q.db.Exec(ctx, createFailedRow,
		arg.ID,
		arg.ChainSlug,
		arg.RunID,
		arg.FileID,
		arg.StoreIdentifier,
		arg.RowNumber,
		arg.RawData,
		arg.ValidationErrors,
	)
	return err
}

const getFailedRowsForReprocessing = `-- name: GetFailedRowsForReprocessing :many
SELECT
    id,
    chain_slug,
    run_id,
    file_id,
    store_identifier,
    row_number,
    raw_data,
    validation_errors
FROM retailer_items_failed
WHERE id = ANY($1::text[]) AND reprocessable = true
`

type GetFailedRowsForReprocessingRow struct {
	ID               string                 `db:"id" json:"id"`
	ChainSlug        string                 `db:"chain_slug" json:"chain_slug"`
	RunID            pgtype.Text            `db:"run_id" json:"run_id"`
	FileID           pgtype.Int8            `db:"file_id" json:"file_id"`
	StoreIdentifier  pgtype.Text            `db:"store_identifier" json:"store_identifier"`
	RowNumber        pgtype.Int4            `db:"row_number" json:"row_number"`
	RawData          string                 `db:"raw_data" json:"raw_data"`
	ValidationErrors jsonb.ValidationErrors `db:"validation_errors" json:"validation_errors"`
}

func (q *Queries) GetFailedRowsForReprocessing(ctx context.Context, dollar_1 []string) ([]GetFailedRowsForReprocessingRow, error) {
	rows, err := q.db.Query(ctx, getFailedRowsForReprocessing, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFailedRowsForReprocessingRow{}
	for rows.Next() {
		var i GetFailedRowsForReprocessingRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RunID,
			&i.FileID,
			&i.StoreIdentifier,
			&i.RowNumber,
			&i.RawData,
			&i.ValidationErrors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedRows = `-- name: ListFailedRows :many
SELECT
    id,
    chain_slug,
    run_id,
    file_id,
    store_identifier,
    row_number,
    raw_data,
    validation_errors,
    failed_at,
    reviewed,
    reviewed_by,
    review_notes,
    reprocessable,
    reprocessed_at
FROM retailer_items_failed
WHERE chain_slug = $1
ORDER BY failed_at DESC
LIMIT $2 OFFSET $3
`

type ListFailedRowsParams struct {
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListFailedRows(ctx context.Context, arg ListFailedRowsParams) ([]RetailerItemsFailed, error) {
	rows, err := q.db.Query(ctx, listFailedRows, arg.ChainSlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetailerItemsFailed{}
	for rows.Next() {
		var i RetailerItemsFailed
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RunID,
			&i.FileID,
			&i.StoreIdentifier,
			&i.RowNumber,
			&i.RawData,
			&i.ValidationErrors,
			&i.FailedAt,
			&i.Reviewed,
			&i.ReviewedBy,
			&i.ReviewNotes,
			&i.Reprocessable,
			&i.ReprocessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRowAsReprocessed = `-- name: MarkRowAsReprocessed :exec
UPDATE retailer_items_failed
SET
    reprocessed_at = NOW(),
    reprocessable = false
WHERE id = $1
`

func (q *Queries) MarkRowAsReprocessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRowAsReprocessed, id)
	return err
}

const updateFailedRowNotes = `-- name: UpdateFailedRowNotes :one
UPDATE retailer_items_failed
SET
    review_notes = $1,
    reviewed = $2,
    reviewed_by = 'admin'
WHERE id = $3
RETURNING id
`

type UpdateFailedRowNotesParams struct {
	ReviewNotes pgtype.Text `db:"review_notes" json:"review_notes"`
	Reviewed    pgtype.Bool `db:"reviewed" json:"reviewed"`
	ID          string      `db:"id" json:"id"`
}

func (q *Queries) UpdateFailedRowNotes(ctx context.Context, arg UpdateFailedRowNotesParams) (string, error) {
	row := q.db.QueryRow(ctx, updateFailedRowNotes, arg.ReviewNotes, arg.Reviewed, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}
