// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: files.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIngestionFiles = `-- name: CountIngestionFiles :one
SELECT COUNT(*) FROM ingestion_files WHERE run_id = $1
`

func (q *Queries) CountIngestionFiles(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestionFiles, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngestionFile = `-- name: CreateIngestionFile :exec
INSERT INTO ingestion_files (
    id, run_id, filename, file_type, file_size, file_hash,
    status, entry_count, total_chunks, chunk_size, metadata, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, 'processing', $7, 1, $7, $8, NOW()
)
`

type CreateIngestionFileParams struct {
	ID         int64       `db:"id" json:"id"`
	RunID      string      `db:"run_id" json:"run_id"`
	Filename   string      `db:"filename" json:"filename"`
	FileType   string      `db:"file_type" json:"file_type"`
	FileSize   pgtype.Int4 `db:"file_size" json:"file_size"`
	FileHash   pgtype.Text `db:"file_hash" json:"file_hash"`
	EntryCount pgtype.Int4 `db:"entry_count" json:"entry_count"`
	Metadata   pgtype.Text `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateIngestionFile(ctx context.Context, arg CreateIngestionFileParams) error {
	_, err := q.db.Exec(ctx, createIngestionFile,
		arg.ID,
		arg.RunID,
		arg.Filename,
		arg.FileType,
		arg.FileSize,
		arg.FileHash,
		arg.EntryCount,
		arg.Metadata,
	)
	return err
}

const createIngestionFilePlaceholder = `-- name: CreateIngestionFilePlaceholder :exec
INSERT INTO ingestion_files (
    id, run_id, filename, file_type, status, metadata, created_at
) VALUES (
    $1, $2, $3, $4, 'processing', $5, NOW()
)
`

type CreateIngestionFilePlaceholderParams struct {
	ID       int64       `db:"id" json:"id"`
	RunID    string      `db:"run_id" json:"run_id"`
	Filename string      `db:"filename" json:"filename"`
	FileType string      `db:"file_type" json:"file_type"`
	Metadata pgtype.Text `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateIngestionFilePlaceholder(ctx context.Context, arg CreateIngestionFilePlaceholderParams) error {
	_, err := q.db.Exec(ctx, createIngestionFilePlaceholder,
		arg.ID,
		arg.RunID,
		arg.Filename,
		arg.FileType,
		arg.Metadata,
	)
	return err
}

const getIngestionFileByID = `-- name: GetIngestionFileByID :one
WITH file_stats AS (
    SELECT
        file_id,
        SUM(row_count) AS row_count,
        SUM(persisted_count) AS persisted_count,
        SUM(price_changes) AS price_changes,
        SUM(failed_rows) AS failed_rows,
        SUM(warning_rows) AS warning_rows,
        COUNT(DISTINCT store_id) AS store_count
    FROM ingestion_store_stats
    WHERE file_id = $1
    GROUP BY file_id
)
SELECT
    f.id, f.run_id, f.filename, f.file_type, f.file_size, f.file_hash, f.status,
    f.status_reason, f.status_severity, f.status_type, f.entry_count, f.processed_at,
    f.metadata, f.total_chunks, f.processed_chunks, f.chunk_size, f.created_at,
    fs.row_count, fs.persisted_count, fs.price_changes, fs.failed_rows, fs.warning_rows, fs.store_count
FROM ingestion_files f
LEFT JOIN file_stats fs ON fs.file_id = f.id
WHERE f.id = $1
`

type GetIngestionFileByIDRow struct {
	ID              int64            `db:"id" json:"id"`
	RunID           string           `db:"run_id" json:"run_id"`
	Filename        string           `db:"filename" json:"filename"`
	FileType        string           `db:"file_type" json:"file_type"`
	FileSize        pgtype.Int4      `db:"file_size" json:"file_size"`
	FileHash        pgtype.Text      `db:"file_hash" json:"file_hash"`
	Status          string           `db:"status" json:"status"`
	StatusReason    pgtype.Text      `db:"status_reason" json:"status_reason"`
	StatusSeverity  pgtype.Text      `db:"status_severity" json:"status_severity"`
	StatusType      pgtype.Text      `db:"status_type" json:"status_type"`
	EntryCount      pgtype.Int4      `db:"entry_count" json:"entry_count"`
	ProcessedAt     pgtype.Timestamp `db:"processed_at" json:"processed_at"`
	Metadata        pgtype.Text      `db:"metadata" json:"metadata"`
	TotalChunks     pgtype.Int4      `db:"total_chunks" json:"total_chunks"`
	ProcessedChunks pgtype.Int4      `db:"processed_chunks" json:"processed_chunks"`
	ChunkSize       pgtype.Int4      `db:"chunk_size" json:"chunk_size"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	RowCount        pgtype.Int8      `db:"row_count" json:"row_count"`
	PersistedCount  pgtype.Int8      `db:"persisted_count" json:"persisted_count"`
	PriceChanges    pgtype.Int8      `db:"price_changes" json:"price_changes"`
	FailedRows      pgtype.Int8      `db:"failed_rows" json:"failed_rows"`
	WarningRows     pgtype.Int8      `db:"warning_rows" json:"warning_rows"`
	StoreCount      pgtype.Int8      `db:"store_count" json:"store_count"`
}

func (q *Queries) GetIngestionFileByID(ctx context.Context, id int64) (GetIngestionFileByIDRow, error) {
	row := q.db.QueryRow(ctx, getIngestionFileByID, id)
	var i GetIngestionFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Filename,
		&i.FileType,
		&i.FileSize,
		&i.FileHash,
		&i.Status,
		&i.StatusReason,
		&i.StatusSeverity,
		&i.StatusType,
		&i.EntryCount,
		&i.ProcessedAt,
		&i.Metadata,
		&i.TotalChunks,
		&i.ProcessedChunks,
		&i.ChunkSize,
		&i.CreatedAt,
		&i.RowCount,
		&i.PersistedCount,
		&i.PriceChanges,
		&i.FailedRows,
		&i.WarningRows,
		&i.StoreCount,
	)
	return i, err
}

const listIngestionFiles = `-- name: ListIngestionFiles :many
WITH file_stats AS (
    SELECT
        file_id,
        SUM(row_count) AS row_count,
        SUM(persisted_count) AS persisted_count,
        SUM(price_changes) AS price_changes,
        SUM(failed_rows) AS failed_rows,
        SUM(warning_rows) AS warning_rows,
        COUNT(DISTINCT store_id) AS store_count
    FROM ingestion_store_stats
    WHERE run_id = $1
    GROUP BY file_id
)
SELECT
    f.id, f.run_id, f.filename, f.file_type, f.file_size, f.file_hash, f.status,
    f.status_reason, f.status_severity, f.status_type, f.entry_count, f.processed_at,
    f.metadata, f.total_chunks, f.processed_chunks, f.chunk_size, f.created_at,
    fs.row_count, fs.persisted_count, fs.price_changes, fs.failed_rows, fs.warning_rows, fs.store_count
FROM ingestion_files f
LEFT JOIN file_stats fs ON fs.file_id = f.id
WHERE f.run_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListIngestionFilesParams struct {
	RunID  string `db:"run_id" json:"run_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type ListIngestionFilesRow struct {
	ID              int64            `db:"id" json:"id"`
	RunID           string           `db:"run_id" json:"run_id"`
	Filename        string           `db:"filename" json:"filename"`
	FileType        string           `db:"file_type" json:"file_type"`
	FileSize        pgtype.Int4      `db:"file_size" json:"file_size"`
	FileHash        pgtype.Text      `db:"file_hash" json:"file_hash"`
	Status          string           `db:"status" json:"status"`
	StatusReason    pgtype.Text      `db:"status_reason" json:"status_reason"`
	StatusSeverity  pgtype.Text      `db:"status_severity" json:"status_severity"`
	StatusType      pgtype.Text      `db:"status_type" json:"status_type"`
	EntryCount      pgtype.Int4      `db:"entry_count" json:"entry_count"`
	ProcessedAt     pgtype.Timestamp `db:"processed_at" json:"processed_at"`
	Metadata        pgtype.Text      `db:"metadata" json:"metadata"`
	TotalChunks     pgtype.Int4      `db:"total_chunks" json:"total_chunks"`
	ProcessedChunks pgtype.Int4      `db:"processed_chunks" json:"processed_chunks"`
	ChunkSize       pgtype.Int4      `db:"chunk_size" json:"chunk_size"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	RowCount        pgtype.Int8      `db:"row_count" json:"row_count"`
	PersistedCount  pgtype.Int8      `db:"persisted_count" json:"persisted_count"`
	PriceChanges    pgtype.Int8      `db:"price_changes" json:"price_changes"`
	FailedRows      pgtype.Int8      `db:"failed_rows" json:"failed_rows"`
	WarningRows     pgtype.Int8      `db:"warning_rows" json:"warning_rows"`
	StoreCount      pgtype.Int8      `db:"store_count" json:"store_count"`
}

func (q *Queries) ListIngestionFiles(ctx context.Context, arg ListIngestionFilesParams) ([]ListIngestionFilesRow, error) {
	rows, err := q.db.Query(ctx, listIngestionFiles, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngestionFilesRow{}
	for rows.Next() {
		var i ListIngestionFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Filename,
			&i.FileType,
			&i.FileSize,
			&i.FileHash,
			&i.Status,
			&i.StatusReason,
			&i.StatusSeverity,
			&i.StatusType,
			&i.EntryCount,
			&i.ProcessedAt,
			&i.Metadata,
			&i.TotalChunks,
			&i.ProcessedChunks,
			&i.ChunkSize,
			&i.CreatedAt,
			&i.RowCount,
			&i.PersistedCount,
			&i.PriceChanges,
			&i.FailedRows,
			&i.WarningRows,
			&i.StoreCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestionFileAfterParse = `-- name: UpdateIngestionFileAfterParse :exec
UPDATE ingestion_files
SET entry_count = $1,
    total_chunks = $2,
    chunk_size = $3,
    metadata = $4
WHERE id = $5
`

type UpdateIngestionFileAfterParseParams struct {
	EntryCount  pgtype.Int4 `db:"entry_count" json:"entry_count"`
	TotalChunks pgtype.Int4 `db:"total_chunks" json:"total_chunks"`
	ChunkSize   pgtype.Int4 `db:"chunk_size" json:"chunk_size"`
	Metadata    pgtype.Text `db:"metadata" json:"metadata"`
	ID          int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateIngestionFileAfterParse(ctx context.Context, arg UpdateIngestionFileAfterParseParams) error {
	_, err := q.db.Exec(ctx, updateIngestionFileAfterParse,
		arg.EntryCount,
		arg.TotalChunks,
		arg.ChunkSize,
		arg.Metadata,
		arg.ID,
	)
	return err
}

const updateIngestionFileCompleted = `-- name: UpdateIngestionFileCompleted :exec
UPDATE ingestion_files
SET status = 'completed',
    processed_chunks = $1,
    processed_at = NOW()
WHERE id = $2
`

type UpdateIngestionFileCompletedParams struct {
	ProcessedChunks pgtype.Int4 `db:"processed_chunks" json:"processed_chunks"`
	ID              int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateIngestionFileCompleted(ctx context.Context, arg UpdateIngestionFileCompletedParams) error {
	_, err := q.db.Exec(ctx, updateIngestionFileCompleted, arg.ProcessedChunks, arg.ID)
	return err
}

const updateIngestionFileCompletedWithStatus = `-- name: UpdateIngestionFileCompletedWithStatus :exec
UPDATE ingestion_files
SET status = 'completed',
    processed_chunks = $1,
    processed_at = NOW(),
    status_reason = $2,
    status_severity = $3,
    status_type = $4
WHERE id = $5
`

type UpdateIngestionFileCompletedWithStatusParams struct {
	ProcessedChunks pgtype.Int4 `db:"processed_chunks" json:"processed_chunks"`
	StatusReason    pgtype.Text `db:"status_reason" json:"status_reason"`
	StatusSeverity  pgtype.Text `db:"status_severity" json:"status_severity"`
	StatusType      pgtype.Text `db:"status_type" json:"status_type"`
	ID              int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateIngestionFileCompletedWithStatus(ctx context.Context, arg UpdateIngestionFileCompletedWithStatusParams) error {
	_, err := q.db.Exec(ctx, updateIngestionFileCompletedWithStatus,
		arg.ProcessedChunks,
		arg.StatusReason,
		arg.StatusSeverity,
		arg.StatusType,
		arg.ID,
	)
	return err
}

const updateIngestionFileFailed = `-- name: UpdateIngestionFileFailed :exec
UPDATE ingestion_files
SET status = 'failed',
    processed_at = NOW(),
    status_reason = $1,
    status_severity = $2,
    status_type = $3
WHERE id = $4
`

type UpdateIngestionFileFailedParams struct {
	StatusReason   pgtype.Text `db:"status_reason" json:"status_reason"`
	StatusSeverity pgtype.Text `db:"status_severity" json:"status_severity"`
	StatusType     pgtype.Text `db:"status_type" json:"status_type"`
	ID             int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateIngestionFileFailed(ctx context.Context, arg UpdateIngestionFileFailedParams) error {
	_, err := q.db.Exec(ctx, updateIngestionFileFailed,
		arg.StatusReason,
		arg.StatusSeverity,
		arg.StatusType,
		arg.ID,
	)
	return err
}

const updateIngestionFileFetchInfo = `-- name: UpdateIngestionFileFetchInfo :exec
UPDATE ingestion_files
SET file_size = $1,
    file_hash = $2
WHERE id = $3
`

type UpdateIngestionFileFetchInfoParams struct {
	FileSize pgtype.Int4 `db:"file_size" json:"file_size"`
	FileHash pgtype.Text `db:"file_hash" json:"file_hash"`
	ID       int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateIngestionFileFetchInfo(ctx context.Context, arg UpdateIngestionFileFetchInfoParams) error {
	_, err := q.db.Exec(ctx, updateIngestionFileFetchInfo, arg.FileSize, arg.FileHash, arg.ID)
	return err
}

const listPendingFilesForResume = `-- name: ListPendingFilesForResume :many
SELECT id, filename, file_type, file_hash
FROM ingestion_files
WHERE run_id = $1
  AND status IN ('pending', 'processing')
ORDER BY created_at ASC
`

type ListPendingFilesForResumeRow struct {
	ID       int64       `db:"id" json:"id"`
	Filename string      `db:"filename" json:"filename"`
	FileType string      `db:"file_type" json:"file_type"`
	FileHash pgtype.Text `db:"file_hash" json:"file_hash"`
}

func (q *Queries) ListPendingFilesForResume(ctx context.Context, runID string) ([]ListPendingFilesForResumeRow, error) {
	rows, err := q.db.Query(ctx, listPendingFilesForResume, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingFilesForResumeRow{}
	for rows.Next() {
		var i ListPendingFilesForResumeRow
		if err := rows.Scan(&i.ID, &i.Filename, &i.FileType, &i.FileHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetProcessingFilesToPending = `-- name: ResetProcessingFilesToPending :exec
UPDATE ingestion_files
SET status = 'pending'
WHERE run_id = $1
  AND status = 'processing'
`

func (q *Queries) ResetProcessingFilesToPending(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, resetProcessingFilesToPending, runID)
	return err
}
