// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIngestionFiles = `-- name: CountIngestionFiles :one
SELECT COUNT(*) FROM ingestion_files WHERE run_id = $1
`

func (q *Queries) CountIngestionFiles(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestionFiles, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngestionFile = `-- name: CreateIngestionFile :exec
INSERT INTO ingestion_files (
    id, run_id, filename, file_type, file_size, file_hash,
    status, entry_count, total_chunks, chunk_size, metadata, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, 'processing', $7, 1, $7, $8, NOW()
)
`

type CreateIngestionFileParams struct {
	ID         int64       `db:"id" json:"id"`
	RunID      string      `db:"run_id" json:"run_id"`
	Filename   string      `db:"filename" json:"filename"`
	FileType   string      `db:"file_type" json:"file_type"`
	FileSize   pgtype.Int4 `db:"file_size" json:"file_size"`
	FileHash   pgtype.Text `db:"file_hash" json:"file_hash"`
	EntryCount pgtype.Int4 `db:"entry_count" json:"entry_count"`
	Metadata   pgtype.Text `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateIngestionFile(ctx context.Context, arg CreateIngestionFileParams) error {
	_, err := q.db.Exec(ctx, createIngestionFile,
		arg.ID,
		arg.RunID,
		arg.Filename,
		arg.FileType,
		arg.FileSize,
		arg.FileHash,
		arg.EntryCount,
		arg.Metadata,
	)
	return err
}

const listIngestionFiles = `-- name: ListIngestionFiles :many
SELECT id, run_id, filename, file_type, file_size, file_hash, status,
       entry_count, processed_at, metadata, total_chunks, processed_chunks,
       chunk_size, created_at
FROM ingestion_files
WHERE run_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListIngestionFilesParams struct {
	RunID  string `db:"run_id" json:"run_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListIngestionFiles(ctx context.Context, arg ListIngestionFilesParams) ([]IngestionFile, error) {
	rows, err := q.db.Query(ctx, listIngestionFiles, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionFile{}
	for rows.Next() {
		var i IngestionFile
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Filename,
			&i.FileType,
			&i.FileSize,
			&i.FileHash,
			&i.Status,
			&i.EntryCount,
			&i.ProcessedAt,
			&i.Metadata,
			&i.TotalChunks,
			&i.ProcessedChunks,
			&i.ChunkSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestionFileCompleted = `-- name: UpdateIngestionFileCompleted :exec
UPDATE ingestion_files
SET status = 'completed',
    processed_chunks = $1,
    processed_at = NOW()
WHERE id = $2
`

type UpdateIngestionFileCompletedParams struct {
	ProcessedChunks pgtype.Int4 `db:"processed_chunks" json:"processed_chunks"`
	ID              int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateIngestionFileCompleted(ctx context.Context, arg UpdateIngestionFileCompletedParams) error {
	_, err := q.db.Exec(ctx, updateIngestionFileCompleted, arg.ProcessedChunks, arg.ID)
	return err
}
