// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ingestion.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngestionRun = `-- name: CreateIngestionRun :one
INSERT INTO ingestion_runs (
  id, chain_slug, source, status, started_at, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, chain_slug, source, status, started_at, completed_at, total_files, processed_files, total_entries, processed_entries, error_count, metadata, parent_run_id, rerun_type, rerun_target_id, created_at, archive_id, source_url, status_reason, status_severity, status_type
`

type CreateIngestionRunParams struct {
	ID        string           `db:"id" json:"id"`
	ChainSlug string           `db:"chain_slug" json:"chain_slug"`
	Source    string           `db:"source" json:"source"`
	Status    string           `db:"status" json:"status"`
	StartedAt pgtype.Timestamp `db:"started_at" json:"started_at"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateIngestionRun(ctx context.Context, arg CreateIngestionRunParams) (IngestionRun, error) {
	row := q.db.QueryRow(ctx, createIngestionRun,
		arg.ID,
		arg.ChainSlug,
		arg.Source,
		arg.Status,
		arg.StartedAt,
		arg.CreatedAt,
	)
	var i IngestionRun
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.Source,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.TotalEntries,
		&i.ProcessedEntries,
		&i.ErrorCount,
		&i.Metadata,
		&i.ParentRunID,
		&i.RerunType,
		&i.RerunTargetID,
		&i.CreatedAt,
		&i.ArchiveID,
		&i.SourceUrl,
		&i.StatusReason,
		&i.StatusSeverity,
		&i.StatusType,
	)
	return i, err
}

const getIngestionRun = `-- name: GetIngestionRun :one
SELECT id, chain_slug, source, status, started_at, completed_at, total_files, processed_files, total_entries, processed_entries, error_count, metadata, parent_run_id, rerun_type, rerun_target_id, created_at, archive_id, source_url, status_reason, status_severity, status_type FROM ingestion_runs WHERE id = $1
`

func (q *Queries) GetIngestionRun(ctx context.Context, id string) (IngestionRun, error) {
	row := q.db.QueryRow(ctx, getIngestionRun, id)
	var i IngestionRun
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.Source,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.TotalEntries,
		&i.ProcessedEntries,
		&i.ErrorCount,
		&i.Metadata,
		&i.ParentRunID,
		&i.RerunType,
		&i.RerunTargetID,
		&i.CreatedAt,
		&i.ArchiveID,
		&i.SourceUrl,
		&i.StatusReason,
		&i.StatusSeverity,
		&i.StatusType,
	)
	return i, err
}

const listIngestionRuns = `-- name: ListIngestionRuns :many
SELECT id, chain_slug, source, status, started_at, completed_at, total_files, processed_files, total_entries, processed_entries, error_count, metadata, parent_run_id, rerun_type, rerun_target_id, created_at, archive_id, source_url, status_reason, status_severity, status_type FROM ingestion_runs
WHERE ($3::text IS NULL OR chain_slug = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListIngestionRunsParams struct {
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
	ChainSlug pgtype.Text `db:"chain_slug" json:"chain_slug"`
}

func (q *Queries) ListIngestionRuns(ctx context.Context, arg ListIngestionRunsParams) ([]IngestionRun, error) {
	rows, err := q.db.Query(ctx, listIngestionRuns, arg.Limit, arg.Offset, arg.ChainSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionRun{}
	for rows.Next() {
		var i IngestionRun
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.Source,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TotalFiles,
			&i.ProcessedFiles,
			&i.TotalEntries,
			&i.ProcessedEntries,
			&i.ErrorCount,
			&i.Metadata,
			&i.ParentRunID,
			&i.RerunType,
			&i.RerunTargetID,
			&i.CreatedAt,
			&i.ArchiveID,
			&i.SourceUrl,
			&i.StatusReason,
			&i.StatusSeverity,
			&i.StatusType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestionRunsByChain = `-- name: ListIngestionRunsByChain :many
SELECT id, chain_slug, source, status, started_at, completed_at, total_files, processed_files, total_entries, processed_entries, error_count, metadata, parent_run_id, rerun_type, rerun_target_id, created_at, archive_id, source_url, status_reason, status_severity, status_type FROM ingestion_runs
WHERE chain_slug = $1 AND source = 'api'
ORDER BY started_at DESC
LIMIT $2
`

type ListIngestionRunsByChainParams struct {
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	Limit     int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListIngestionRunsByChain(ctx context.Context, arg ListIngestionRunsByChainParams) ([]IngestionRun, error) {
	rows, err := q.db.Query(ctx, listIngestionRunsByChain, arg.ChainSlug, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionRun{}
	for rows.Next() {
		var i IngestionRun
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.Source,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TotalFiles,
			&i.ProcessedFiles,
			&i.TotalEntries,
			&i.ProcessedEntries,
			&i.ErrorCount,
			&i.Metadata,
			&i.ParentRunID,
			&i.RerunType,
			&i.RerunTargetID,
			&i.CreatedAt,
			&i.ArchiveID,
			&i.SourceUrl,
			&i.StatusReason,
			&i.StatusSeverity,
			&i.StatusType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestionRunFailed = `-- name: UpdateIngestionRunFailed :exec
UPDATE ingestion_runs
SET status = 'failed',
    completed_at = NOW(),
    metadata = $2
WHERE id = $1
`

type UpdateIngestionRunFailedParams struct {
	ID       string      `db:"id" json:"id"`
	Metadata pgtype.Text `db:"metadata" json:"metadata"`
}

func (q *Queries) UpdateIngestionRunFailed(ctx context.Context, arg UpdateIngestionRunFailedParams) error {
	_, err := q.db.Exec(ctx, updateIngestionRunFailed, arg.ID, arg.Metadata)
	return err
}

const updateIngestionRunStatus = `-- name: UpdateIngestionRunStatus :exec
UPDATE ingestion_runs
SET status = $2,
    completed_at = $3,
    processed_files = $4,
    processed_entries = $5
WHERE id = $1
`

type UpdateIngestionRunStatusParams struct {
	ID               string           `db:"id" json:"id"`
	Status           string           `db:"status" json:"status"`
	CompletedAt      pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	ProcessedFiles   pgtype.Int4      `db:"processed_files" json:"processed_files"`
	ProcessedEntries pgtype.Int4      `db:"processed_entries" json:"processed_entries"`
}

func (q *Queries) UpdateIngestionRunStatus(ctx context.Context, arg UpdateIngestionRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateIngestionRunStatus,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.ProcessedFiles,
		arg.ProcessedEntries,
	)
	return err
}
