// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matching.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkRejectionExists = `-- name: CheckRejectionExists :one
SELECT EXISTS(
    SELECT 1 FROM product_match_rejections
    WHERE retailer_item_id = $1 AND rejected_product_id = $2
)
`

type CheckRejectionExistsParams struct {
	RetailerItemID    string `db:"retailer_item_id" json:"retailer_item_id"`
	RejectedProductID string `db:"rejected_product_id" json:"rejected_product_id"`
}

func (q *Queries) CheckRejectionExists(ctx context.Context, arg CheckRejectionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkRejectionExists, arg.RetailerItemID, arg.RejectedProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countProductLinks = `-- name: CountProductLinks :one
SELECT COUNT(*) FROM product_links
`

func (q *Queries) CountProductLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductMatchCandidates = `-- name: CountProductMatchCandidates :one
SELECT COUNT(*) FROM product_match_candidates
`

func (q *Queries) CountProductMatchCandidates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductMatchCandidates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductMatchQueueByStatus = `-- name: CountProductMatchQueueByStatus :one
SELECT COUNT(*) FROM product_match_queue WHERE status = $1
`

func (q *Queries) CountProductMatchQueueByStatus(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countProductMatchQueueByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductLink = `-- name: CreateProductLink :exec
INSERT INTO product_links (id, product_id, retailer_item_id, confidence, created_at)
VALUES (gen_random_text(), $1, $2, $3, now())
ON CONFLICT (retailer_item_id) DO NOTHING
`

type CreateProductLinkParams struct {
	ProductID      string      `db:"product_id" json:"product_id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Confidence     pgtype.Text `db:"confidence" json:"confidence"`
}

func (q *Queries) CreateProductLink(ctx context.Context, arg CreateProductLinkParams) error {
	_, err := q.db.Exec(ctx, createProductLink, arg.ProductID, arg.RetailerItemID, arg.Confidence)
	return err
}

const getCanonicalBarcodeProductID = `-- name: GetCanonicalBarcodeProductID :one
SELECT product_id FROM canonical_barcodes WHERE barcode = $1
`

func (q *Queries) GetCanonicalBarcodeProductID(ctx context.Context, barcode string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getCanonicalBarcodeProductID, barcode)
	var product_id pgtype.Text
	err := row.Scan(&product_id)
	return product_id, err
}

const getMatchingStatus = `-- name: GetMatchingStatus :one
SELECT
    (SELECT COUNT(*) FROM product_match_queue WHERE status = 'pending') as pending_count,
    (SELECT COUNT(*) FROM product_match_queue WHERE status = 'approved') as approved_count,
    (SELECT COUNT(*) FROM product_match_queue WHERE status = 'rejected') as rejected_count,
    (SELECT COUNT(*) FROM product_match_candidates) as candidate_count,
    (SELECT COUNT(*) FROM product_links) as total_links
`

type GetMatchingStatusRow struct {
	PendingCount   int64 `db:"pending_count" json:"pending_count"`
	ApprovedCount  int64 `db:"approved_count" json:"approved_count"`
	RejectedCount  int64 `db:"rejected_count" json:"rejected_count"`
	CandidateCount int64 `db:"candidate_count" json:"candidate_count"`
	TotalLinks     int64 `db:"total_links" json:"total_links"`
}

func (q *Queries) GetMatchingStatus(ctx context.Context) (GetMatchingStatusRow, error) {
	row := q.db.QueryRow(ctx, getMatchingStatus)
	var i GetMatchingStatusRow
	err := row.Scan(
		&i.PendingCount,
		&i.ApprovedCount,
		&i.RejectedCount,
		&i.CandidateCount,
		&i.TotalLinks,
	)
	return i, err
}

const getProductInfo = `-- name: GetProductInfo :one
SELECT id, name, brand, category, unit, unit_quantity, image_url
FROM products WHERE id = $1
`

type GetProductInfoRow struct {
	ID           string      `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Brand        pgtype.Text `db:"brand" json:"brand"`
	Category     pgtype.Text `db:"category" json:"category"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
	ImageUrl     pgtype.Text `db:"image_url" json:"image_url"`
}

func (q *Queries) GetProductInfo(ctx context.Context, id string) (GetProductInfoRow, error) {
	row := q.db.QueryRow(ctx, getProductInfo, id)
	var i GetProductInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.Category,
		&i.Unit,
		&i.UnitQuantity,
		&i.ImageUrl,
	)
	return i, err
}

const getTrgmCandidates = `-- name: GetTrgmCandidates :many
SELECT p.id
FROM products p
WHERE similarity(lower(p.name), lower($1)) > 0.1
ORDER BY similarity(lower(p.name), lower($1)) DESC
LIMIT $2
`

type GetTrgmCandidatesParams struct {
	Lower string `db:"lower" json:"lower"`
	Limit int32  `db:"limit" json:"limit"`
}

func (q *Queries) GetTrgmCandidates(ctx context.Context, arg GetTrgmCandidatesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getTrgmCandidates, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnlinkedItemsWithBarcodes = `-- name: GetUnlinkedItemsWithBarcodes :many

SELECT DISTINCT
    rib.barcode,
    ri.id,
    ri.name,
    ri.brand,
    ri.unit,
    ri.unit_quantity,
    ri.category,
    ri.image_url,
    c.slug as chain_slug,
    ri.external_id
FROM retailer_item_barcodes rib
JOIN retailer_items ri ON ri.id = rib.retailer_item_id
JOIN chains c ON c.slug = ri.chain_slug
WHERE rib.barcode IS NOT NULL AND rib.barcode != ''
AND NOT EXISTS (
    SELECT 1 FROM product_links pl WHERE pl.retailer_item_id = ri.id
)
ORDER BY rib.barcode
`

type GetUnlinkedItemsWithBarcodesRow struct {
	Barcode      string      `db:"barcode" json:"barcode"`
	ID           string      `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Brand        pgtype.Text `db:"brand" json:"brand"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
	Category     pgtype.Text `db:"category" json:"category"`
	ImageUrl     pgtype.Text `db:"image_url" json:"image_url"`
	ChainSlug    string      `db:"chain_slug" json:"chain_slug"`
	ExternalID   pgtype.Text `db:"external_id" json:"external_id"`
}

// Barcode matching queries
func (q *Queries) GetUnlinkedItemsWithBarcodes(ctx context.Context) ([]GetUnlinkedItemsWithBarcodesRow, error) {
	rows, err := q.db.Query(ctx, getUnlinkedItemsWithBarcodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnlinkedItemsWithBarcodesRow{}
	for rows.Next() {
		var i GetUnlinkedItemsWithBarcodesRow
		if err := rows.Scan(
			&i.Barcode,
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Unit,
			&i.UnitQuantity,
			&i.Category,
			&i.ImageUrl,
			&i.ChainSlug,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnmatchedItemsForAI = `-- name: GetUnmatchedItemsForAI :many

SELECT
    ri.id,
    ri.name,
    ri.brand,
    ri.unit,
    ri.unit_quantity,
    ri.category,
    ri.image_url,
    c.slug as chain_slug
FROM retailer_items ri
JOIN chains c ON c.slug = ri.chain_slug
WHERE NOT EXISTS (
    SELECT 1 FROM product_links pl WHERE pl.retailer_item_id = ri.id
)
AND NOT EXISTS (
    SELECT 1 FROM product_match_queue pmq WHERE pmq.retailer_item_id = ri.id AND pmq.status = 'pending'
)
LIMIT $1
`

type GetUnmatchedItemsForAIRow struct {
	ID           string      `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Brand        pgtype.Text `db:"brand" json:"brand"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
	Category     pgtype.Text `db:"category" json:"category"`
	ImageUrl     pgtype.Text `db:"image_url" json:"image_url"`
	ChainSlug    string      `db:"chain_slug" json:"chain_slug"`
}

// AI matching queries
func (q *Queries) GetUnmatchedItemsForAI(ctx context.Context, limit int32) ([]GetUnmatchedItemsForAIRow, error) {
	rows, err := q.db.Query(ctx, getUnmatchedItemsForAI, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnmatchedItemsForAIRow{}
	for rows.Next() {
		var i GetUnmatchedItemsForAIRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Unit,
			&i.UnitQuantity,
			&i.Category,
			&i.ImageUrl,
			&i.ChainSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCandidateWithFlag = `-- name: InsertCandidateWithFlag :exec
INSERT INTO product_match_candidates (id, retailer_item_id, match_type, flags, created_at)
VALUES (gen_random_text(), $1, 'barcode', $2, now())
ON CONFLICT (retailer_item_id, candidate_product_id) DO NOTHING
`

type InsertCandidateWithFlagParams struct {
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Flags          pgtype.Text `db:"flags" json:"flags"`
}

func (q *Queries) InsertCandidateWithFlag(ctx context.Context, arg InsertCandidateWithFlagParams) error {
	_, err := q.db.Exec(ctx, insertCandidateWithFlag, arg.RetailerItemID, arg.Flags)
	return err
}

const insertCanonicalBarcode = `-- name: InsertCanonicalBarcode :exec
INSERT INTO canonical_barcodes (barcode, product_id)
VALUES ($1, $2)
`

type InsertCanonicalBarcodeParams struct {
	Barcode   string      `db:"barcode" json:"barcode"`
	ProductID pgtype.Text `db:"product_id" json:"product_id"`
}

func (q *Queries) InsertCanonicalBarcode(ctx context.Context, arg InsertCanonicalBarcodeParams) error {
	_, err := q.db.Exec(ctx, insertCanonicalBarcode, arg.Barcode, arg.ProductID)
	return err
}

const insertProductForBarcode = `-- name: InsertProductForBarcode :one
INSERT INTO products (id, name, brand, category, subcategory, unit, unit_quantity, image_url, created_at, updated_at)
VALUES (gen_random_text(), $1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id
`

type InsertProductForBarcodeParams struct {
	Name         string      `db:"name" json:"name"`
	Brand        pgtype.Text `db:"brand" json:"brand"`
	Category     pgtype.Text `db:"category" json:"category"`
	Subcategory  pgtype.Text `db:"subcategory" json:"subcategory"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
	ImageUrl     pgtype.Text `db:"image_url" json:"image_url"`
}

func (q *Queries) InsertProductForBarcode(ctx context.Context, arg InsertProductForBarcodeParams) (string, error) {
	row := q.db.QueryRow(ctx, insertProductForBarcode,
		arg.Name,
		arg.Brand,
		arg.Category,
		arg.Subcategory,
		arg.Unit,
		arg.UnitQuantity,
		arg.ImageUrl,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertProductLinkForBarcode = `-- name: InsertProductLinkForBarcode :exec
INSERT INTO product_links (id, product_id, retailer_item_id, confidence, created_at)
VALUES (gen_random_text(), $1, $2, 'auto', now())
ON CONFLICT (retailer_item_id) DO NOTHING
`

type InsertProductLinkForBarcodeParams struct {
	ProductID      string `db:"product_id" json:"product_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

func (q *Queries) InsertProductLinkForBarcode(ctx context.Context, arg InsertProductLinkForBarcodeParams) error {
	_, err := q.db.Exec(ctx, insertProductLinkForBarcode, arg.ProductID, arg.RetailerItemID)
	return err
}

const insertQueueForReview = `-- name: InsertQueueForReview :exec
INSERT INTO product_match_queue (id, retailer_item_id, status, created_at)
VALUES (gen_random_text(), $1, 'pending', now())
ON CONFLICT (retailer_item_id) DO NOTHING
`

func (q *Queries) InsertQueueForReview(ctx context.Context, retailerItemID string) error {
	_, err := q.db.Exec(ctx, insertQueueForReview, retailerItemID)
	return err
}

const storeCandidateMatch = `-- name: StoreCandidateMatch :exec
INSERT INTO product_match_candidates (
    id, retailer_item_id, candidate_product_id, similarity, match_type, rank,
    matching_run_id, model_version, normalized_text_hash, created_at
)
VALUES (
    gen_random_text(), $1, $2, $3::real, $4, $5, $6, $7, $8, now()
)
ON CONFLICT (retailer_item_id, candidate_product_id)
DO UPDATE SET
    similarity = EXCLUDED.similarity,
    rank = EXCLUDED.rank,
    matching_run_id = EXCLUDED.matching_run_id,
    model_version = EXCLUDED.model_version
`

type StoreCandidateMatchParams struct {
	RetailerItemID     string      `db:"retailer_item_id" json:"retailer_item_id"`
	CandidateProductID pgtype.Text `db:"candidate_product_id" json:"candidate_product_id"`
	Column3            float32     `db:"column_3" json:"column_3"`
	MatchType          string      `db:"match_type" json:"match_type"`
	Rank               pgtype.Int2 `db:"rank" json:"rank"`
	MatchingRunID      pgtype.Text `db:"matching_run_id" json:"matching_run_id"`
	ModelVersion       pgtype.Text `db:"model_version" json:"model_version"`
	NormalizedTextHash pgtype.Text `db:"normalized_text_hash" json:"normalized_text_hash"`
}

func (q *Queries) StoreCandidateMatch(ctx context.Context, arg StoreCandidateMatchParams) error {
	_, err := q.db.Exec(ctx, storeCandidateMatch,
		arg.RetailerItemID,
		arg.CandidateProductID,
		arg.Column3,
		arg.MatchType,
		arg.Rank,
		arg.MatchingRunID,
		arg.ModelVersion,
		arg.NormalizedTextHash,
	)
	return err
}
