// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matching.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductLinks = `-- name: CountProductLinks :one
SELECT COUNT(*) FROM product_links
`

func (q *Queries) CountProductLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductMatchCandidates = `-- name: CountProductMatchCandidates :one
SELECT COUNT(*) FROM product_match_candidates
`

func (q *Queries) CountProductMatchCandidates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductMatchCandidates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductMatchQueueByStatus = `-- name: CountProductMatchQueueByStatus :one
SELECT COUNT(*) FROM product_match_queue WHERE status = $1
`

func (q *Queries) CountProductMatchQueueByStatus(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countProductMatchQueueByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMatchingStatus = `-- name: GetMatchingStatus :one
SELECT
    (SELECT COUNT(*) FROM product_match_queue WHERE status = 'pending') as pending_count,
    (SELECT COUNT(*) FROM product_match_queue WHERE status = 'approved') as approved_count,
    (SELECT COUNT(*) FROM product_match_queue WHERE status = 'rejected') as rejected_count,
    (SELECT COUNT(*) FROM product_match_candidates) as candidate_count,
    (SELECT COUNT(*) FROM product_links) as total_links
`

type GetMatchingStatusRow struct {
	PendingCount   int64 `db:"pending_count" json:"pending_count"`
	ApprovedCount  int64 `db:"approved_count" json:"approved_count"`
	RejectedCount  int64 `db:"rejected_count" json:"rejected_count"`
	CandidateCount int64 `db:"candidate_count" json:"candidate_count"`
	TotalLinks     int64 `db:"total_links" json:"total_links"`
}

func (q *Queries) GetMatchingStatus(ctx context.Context) (GetMatchingStatusRow, error) {
	row := q.db.QueryRow(ctx, getMatchingStatus)
	var i GetMatchingStatusRow
	err := row.Scan(
		&i.PendingCount,
		&i.ApprovedCount,
		&i.RejectedCount,
		&i.CandidateCount,
		&i.TotalLinks,
	)
	return i, err
}
