// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kosarica/price-service/internal/jsonb"
)

type Account struct {
	ID                    string           `db:"id" json:"id"`
	AccountId             string           `db:"accountId" json:"accountId"`
	ProviderId            string           `db:"providerId" json:"providerId"`
	UserId                string           `db:"userId" json:"userId"`
	AccessToken           pgtype.Text      `db:"accessToken" json:"accessToken"`
	RefreshToken          pgtype.Text      `db:"refreshToken" json:"refreshToken"`
	IdToken               pgtype.Text      `db:"idToken" json:"idToken"`
	AccessTokenExpiresAt  pgtype.Timestamp `db:"accessTokenExpiresAt" json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt pgtype.Timestamp `db:"refreshTokenExpiresAt" json:"refreshTokenExpiresAt"`
	Scope                 pgtype.Text      `db:"scope" json:"scope"`
	Password              pgtype.Text      `db:"password" json:"password"`
	CreatedAt             pgtype.Timestamp `db:"createdAt" json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `db:"updatedAt" json:"updatedAt"`
}

type AppSetting struct {
	ID                       string           `db:"id" json:"id"`
	AppName                  pgtype.Text      `db:"appName" json:"appName"`
	RequireEmailVerification pgtype.Bool      `db:"requireEmailVerification" json:"requireEmailVerification"`
	MinPasswordLength        pgtype.Int4      `db:"minPasswordLength" json:"minPasswordLength"`
	MaxPasswordLength        pgtype.Int4      `db:"maxPasswordLength" json:"maxPasswordLength"`
	PasskeyEnabled           pgtype.Bool      `db:"passkeyEnabled" json:"passkeyEnabled"`
	UpdatedAt                pgtype.Timestamp `db:"updatedAt" json:"updatedAt"`
}

type Archive struct {
	ID             string                `db:"id" json:"id"`
	ChainSlug      string                `db:"chain_slug" json:"chain_slug"`
	SourceUrl      string                `db:"source_url" json:"source_url"`
	Filename       string                `db:"filename" json:"filename"`
	OriginalFormat string                `db:"original_format" json:"original_format"`
	ArchivePath    string                `db:"archive_path" json:"archive_path"`
	ArchiveType    string                `db:"archive_type" json:"archive_type"`
	ContentType    pgtype.Text           `db:"content_type" json:"content_type"`
	FileSize       pgtype.Int8           `db:"file_size" json:"file_size"`
	CompressedSize pgtype.Int8           `db:"compressed_size" json:"compressed_size"`
	Checksum       string                `db:"checksum" json:"checksum"`
	DownloadedAt   pgtype.Timestamptz    `db:"downloaded_at" json:"downloaded_at"`
	Metadata       jsonb.ArchiveMetadata `db:"metadata" json:"metadata"`
	CreatedAt      pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz    `db:"updated_at" json:"updated_at"`
	IsCompressed   pgtype.Bool           `db:"is_compressed" json:"is_compressed"`
}

type CanonicalBarcode struct {
	Barcode   string             `db:"barcode" json:"barcode"`
	ProductID pgtype.Text        `db:"product_id" json:"product_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Chain struct {
	Slug      string           `db:"slug" json:"slug"`
	Name      string           `db:"name" json:"name"`
	Website   pgtype.Text      `db:"website" json:"website"`
	LogoUrl   pgtype.Text      `db:"logo_url" json:"logo_url"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type CronJob struct {
	ID             string                `db:"id" json:"id"`
	Name           string                `db:"name" json:"name"`
	CronExpression string                `db:"cron_expression" json:"cron_expression"`
	Timezone       pgtype.Text           `db:"timezone" json:"timezone"`
	TaskType       string                `db:"task_type" json:"task_type"`
	TaskPayload    *jsonb.CronJobPayload `db:"task_payload" json:"task_payload"`
	Enabled        pgtype.Bool           `db:"enabled" json:"enabled"`
	NextRunAt      pgtype.Timestamptz    `db:"next_run_at" json:"next_run_at"`
	LastRunAt      pgtype.Timestamptz    `db:"last_run_at" json:"last_run_at"`
	LastRunStatus  pgtype.Text           `db:"last_run_status" json:"last_run_status"`
	CreatedAt      pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz    `db:"updated_at" json:"updated_at"`
}

type CronRun struct {
	ID             int64                  `db:"id" json:"id"`
	JobID          string                 `db:"job_id" json:"job_id"`
	IdempotencyKey string                 `db:"idempotency_key" json:"idempotency_key"`
	Status         string                 `db:"status" json:"status"`
	ScheduledFor   pgtype.Timestamptz     `db:"scheduled_for" json:"scheduled_for"`
	StartedAt      pgtype.Timestamptz     `db:"started_at" json:"started_at"`
	CompletedAt    pgtype.Timestamptz     `db:"completed_at" json:"completed_at"`
	ErrorMessage   pgtype.Text            `db:"error_message" json:"error_message"`
	ErrorDetails   pgtype.Text            `db:"error_details" json:"error_details"`
	TasksEnqueued  pgtype.Int4            `db:"tasks_enqueued" json:"tasks_enqueued"`
	Metadata       *jsonb.CronRunMetadata `db:"metadata" json:"metadata"`
	CreatedAt      pgtype.Timestamptz     `db:"created_at" json:"created_at"`
}

type DrizzleDrizzleMigration struct {
	ID        int32       `db:"id" json:"id"`
	Hash      string      `db:"hash" json:"hash"`
	CreatedAt pgtype.Int8 `db:"created_at" json:"created_at"`
}

type GroupPrice struct {
	PriceGroupID   string           `db:"price_group_id" json:"price_group_id"`
	RetailerItemID string           `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32            `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4      `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4      `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4      `db:"anchor_price" json:"anchor_price"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type IngestionChunk struct {
	ID             string           `db:"id" json:"id"`
	FileID         int64            `db:"file_id" json:"file_id"`
	ChunkIndex     int32            `db:"chunk_index" json:"chunk_index"`
	StartRow       int32            `db:"start_row" json:"start_row"`
	EndRow         int32            `db:"end_row" json:"end_row"`
	RowCount       int32            `db:"row_count" json:"row_count"`
	Status         string           `db:"status" json:"status"`
	R2Key          pgtype.Text      `db:"r2_key" json:"r2_key"`
	PersistedCount pgtype.Int4      `db:"persisted_count" json:"persisted_count"`
	ErrorCount     pgtype.Int4      `db:"error_count" json:"error_count"`
	ProcessedAt    pgtype.Timestamp `db:"processed_at" json:"processed_at"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type IngestionError struct {
	ID           int64            `db:"id" json:"id"`
	RunID        string           `db:"run_id" json:"run_id"`
	FileID       pgtype.Int8      `db:"file_id" json:"file_id"`
	ChunkID      pgtype.Text      `db:"chunk_id" json:"chunk_id"`
	EntryID      pgtype.Text      `db:"entry_id" json:"entry_id"`
	ErrorType    string           `db:"error_type" json:"error_type"`
	ErrorMessage string           `db:"error_message" json:"error_message"`
	ErrorDetails pgtype.Text      `db:"error_details" json:"error_details"`
	Severity     string           `db:"severity" json:"severity"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type IngestionFile struct {
	ID              int64            `db:"id" json:"id"`
	RunID           string           `db:"run_id" json:"run_id"`
	Filename        string           `db:"filename" json:"filename"`
	FileType        string           `db:"file_type" json:"file_type"`
	FileSize        pgtype.Int4      `db:"file_size" json:"file_size"`
	FileHash        pgtype.Text      `db:"file_hash" json:"file_hash"`
	Status          string           `db:"status" json:"status"`
	EntryCount      pgtype.Int4      `db:"entry_count" json:"entry_count"`
	ProcessedAt     pgtype.Timestamp `db:"processed_at" json:"processed_at"`
	Metadata        pgtype.Text      `db:"metadata" json:"metadata"`
	TotalChunks     pgtype.Int4      `db:"total_chunks" json:"total_chunks"`
	ProcessedChunks pgtype.Int4      `db:"processed_chunks" json:"processed_chunks"`
	ChunkSize       pgtype.Int4      `db:"chunk_size" json:"chunk_size"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	StatusReason    pgtype.Text      `db:"status_reason" json:"status_reason"`
	StatusSeverity  pgtype.Text      `db:"status_severity" json:"status_severity"`
	StatusType      pgtype.Text      `db:"status_type" json:"status_type"`
}

type IngestionFileEntry struct {
	ID              string           `db:"id" json:"id"`
	FileID          int64            `db:"file_id" json:"file_id"`
	RowNumber       pgtype.Int4      `db:"row_number" json:"row_number"`
	StoreIdentifier pgtype.Text      `db:"store_identifier" json:"store_identifier"`
	ItemExternalID  pgtype.Text      `db:"item_external_id" json:"item_external_id"`
	ItemName        pgtype.Text      `db:"item_name" json:"item_name"`
	Price           pgtype.Int4      `db:"price" json:"price"`
	DiscountPrice   pgtype.Int4      `db:"discount_price" json:"discount_price"`
	Barcode         pgtype.Text      `db:"barcode" json:"barcode"`
	RawData         pgtype.Text      `db:"raw_data" json:"raw_data"`
	Status          string           `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type IngestionRun struct {
	ID               string           `db:"id" json:"id"`
	ChainSlug        string           `db:"chain_slug" json:"chain_slug"`
	Source           string           `db:"source" json:"source"`
	Status           string           `db:"status" json:"status"`
	StartedAt        pgtype.Timestamp `db:"started_at" json:"started_at"`
	CompletedAt      pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	TotalFiles       pgtype.Int4      `db:"total_files" json:"total_files"`
	ProcessedFiles   pgtype.Int4      `db:"processed_files" json:"processed_files"`
	TotalEntries     pgtype.Int4      `db:"total_entries" json:"total_entries"`
	ProcessedEntries pgtype.Int4      `db:"processed_entries" json:"processed_entries"`
	ErrorCount       pgtype.Int4      `db:"error_count" json:"error_count"`
	Metadata         pgtype.Text      `db:"metadata" json:"metadata"`
	ParentRunID      pgtype.Text      `db:"parent_run_id" json:"parent_run_id"`
	RerunType        pgtype.Text      `db:"rerun_type" json:"rerun_type"`
	RerunTargetID    pgtype.Text      `db:"rerun_target_id" json:"rerun_target_id"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	ArchiveID        pgtype.Text      `db:"archive_id" json:"archive_id"`
	SourceUrl        pgtype.Text      `db:"source_url" json:"source_url"`
	StatusReason     pgtype.Text      `db:"status_reason" json:"status_reason"`
	StatusSeverity   pgtype.Text      `db:"status_severity" json:"status_severity"`
	StatusType       pgtype.Text      `db:"status_type" json:"status_type"`
}

type IngestionStoreStat struct {
	ID              int64            `db:"id" json:"id"`
	RunID           string           `db:"run_id" json:"run_id"`
	FileID          int64            `db:"file_id" json:"file_id"`
	StoreID         string           `db:"store_id" json:"store_id"`
	StoreIdentifier string           `db:"store_identifier" json:"store_identifier"`
	RowCount        int32            `db:"row_count" json:"row_count"`
	PersistedCount  int32            `db:"persisted_count" json:"persisted_count"`
	PriceChanges    int32            `db:"price_changes" json:"price_changes"`
	FailedRows      int32            `db:"failed_rows" json:"failed_rows"`
	WarningRows     int32            `db:"warning_rows" json:"warning_rows"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Passkey struct {
	ID           string           `db:"id" json:"id"`
	Name         pgtype.Text      `db:"name" json:"name"`
	PublicKey    string           `db:"publicKey" json:"publicKey"`
	UserId       string           `db:"userId" json:"userId"`
	CredentialID string           `db:"credentialID" json:"credentialID"`
	Counter      int32            `db:"counter" json:"counter"`
	DeviceType   string           `db:"deviceType" json:"deviceType"`
	BackedUp     bool             `db:"backedUp" json:"backedUp"`
	Transports   pgtype.Text      `db:"transports" json:"transports"`
	CreatedAt    pgtype.Timestamp `db:"createdAt" json:"createdAt"`
}

type PriceGroup struct {
	ID          string           `db:"id" json:"id"`
	ChainSlug   string           `db:"chain_slug" json:"chain_slug"`
	PriceHash   string           `db:"price_hash" json:"price_hash"`
	HashVersion int32            `db:"hash_version" json:"hash_version"`
	StoreCount  int32            `db:"store_count" json:"store_count"`
	ItemCount   int32            `db:"item_count" json:"item_count"`
	FirstSeenAt pgtype.Timestamp `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamp `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Product struct {
	ID           string           `db:"id" json:"id"`
	Name         string           `db:"name" json:"name"`
	Description  pgtype.Text      `db:"description" json:"description"`
	Category     pgtype.Text      `db:"category" json:"category"`
	Subcategory  pgtype.Text      `db:"subcategory" json:"subcategory"`
	Brand        pgtype.Text      `db:"brand" json:"brand"`
	Unit         pgtype.Text      `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text      `db:"unit_quantity" json:"unit_quantity"`
	ImageUrl     pgtype.Text      `db:"image_url" json:"image_url"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type ProductAlias struct {
	ID        string           `db:"id" json:"id"`
	ProductID string           `db:"product_id" json:"product_id"`
	Alias     string           `db:"alias" json:"alias"`
	Source    pgtype.Text      `db:"source" json:"source"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ProductLink struct {
	ID             string           `db:"id" json:"id"`
	ProductID      string           `db:"product_id" json:"product_id"`
	RetailerItemID string           `db:"retailer_item_id" json:"retailer_item_id"`
	Confidence     pgtype.Text      `db:"confidence" json:"confidence"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ProductMatchAudit struct {
	ID            int64              `db:"id" json:"id"`
	QueueID       string             `db:"queue_id" json:"queue_id"`
	Action        string             `db:"action" json:"action"`
	UserID        pgtype.Text        `db:"user_id" json:"user_id"`
	PreviousState pgtype.Text        `db:"previous_state" json:"previous_state"`
	NewState      pgtype.Text        `db:"new_state" json:"new_state"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProductMatchCandidate struct {
	ID                 string             `db:"id" json:"id"`
	RetailerItemID     string             `db:"retailer_item_id" json:"retailer_item_id"`
	CandidateProductID pgtype.Text        `db:"candidate_product_id" json:"candidate_product_id"`
	Similarity         pgtype.Text        `db:"similarity" json:"similarity"`
	MatchType          string             `db:"match_type" json:"match_type"`
	Rank               pgtype.Int2        `db:"rank" json:"rank"`
	Flags              pgtype.Text        `db:"flags" json:"flags"`
	MatchingRunID      pgtype.Text        `db:"matching_run_id" json:"matching_run_id"`
	ModelVersion       pgtype.Text        `db:"model_version" json:"model_version"`
	NormalizedTextHash pgtype.Text        `db:"normalized_text_hash" json:"normalized_text_hash"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProductMatchQueue struct {
	ID              string             `db:"id" json:"id"`
	RetailerItemID  string             `db:"retailer_item_id" json:"retailer_item_id"`
	Status          pgtype.Text        `db:"status" json:"status"`
	Decision        pgtype.Text        `db:"decision" json:"decision"`
	LinkedProductID pgtype.Text        `db:"linked_product_id" json:"linked_product_id"`
	ReviewedBy      pgtype.Text        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ReviewNotes     pgtype.Text        `db:"review_notes" json:"review_notes"`
	Version         pgtype.Int4        `db:"version" json:"version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProductMatchRejection struct {
	RetailerItemID    string             `db:"retailer_item_id" json:"retailer_item_id"`
	RejectedProductID string             `db:"rejected_product_id" json:"rejected_product_id"`
	Reason            pgtype.Text        `db:"reason" json:"reason"`
	RejectedBy        pgtype.Text        `db:"rejected_by" json:"rejected_by"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProductRelation struct {
	ID               string           `db:"id" json:"id"`
	ProductID        string           `db:"product_id" json:"product_id"`
	RelatedProductID string           `db:"related_product_id" json:"related_product_id"`
	RelationType     string           `db:"relation_type" json:"relation_type"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type RetailerItem struct {
	ID             string           `db:"id" json:"id"`
	RetailerItemID pgtype.Int4      `db:"retailer_item_id" json:"retailer_item_id"`
	Barcode        pgtype.Text      `db:"barcode" json:"barcode"`
	IsPrimary      pgtype.Bool      `db:"is_primary" json:"is_primary"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	Name           string           `db:"name" json:"name"`
	ExternalID     pgtype.Text      `db:"external_id" json:"external_id"`
	Description    pgtype.Text      `db:"description" json:"description"`
	Brand          pgtype.Text      `db:"brand" json:"brand"`
	Category       pgtype.Text      `db:"category" json:"category"`
	Subcategory    pgtype.Text      `db:"subcategory" json:"subcategory"`
	Unit           pgtype.Text      `db:"unit" json:"unit"`
	UnitQuantity   pgtype.Text      `db:"unit_quantity" json:"unit_quantity"`
	ImageUrl       pgtype.Text      `db:"image_url" json:"image_url"`
	ChainSlug      pgtype.Text      `db:"chain_slug" json:"chain_slug"`
	ArchiveID      pgtype.Text      `db:"archive_id" json:"archive_id"`
}

type RetailerItemBarcode struct {
	ID             string           `db:"id" json:"id"`
	RetailerItemID string           `db:"retailer_item_id" json:"retailer_item_id"`
	Barcode        string           `db:"barcode" json:"barcode"`
	IsPrimary      pgtype.Bool      `db:"is_primary" json:"is_primary"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type RetailerItemsFailed struct {
	ID               string                 `db:"id" json:"id"`
	ChainSlug        string                 `db:"chain_slug" json:"chain_slug"`
	RunID            pgtype.Text            `db:"run_id" json:"run_id"`
	FileID           pgtype.Int8            `db:"file_id" json:"file_id"`
	StoreIdentifier  pgtype.Text            `db:"store_identifier" json:"store_identifier"`
	RowNumber        pgtype.Int4            `db:"row_number" json:"row_number"`
	RawData          string                 `db:"raw_data" json:"raw_data"`
	ValidationErrors jsonb.ValidationErrors `db:"validation_errors" json:"validation_errors"`
	FailedAt         pgtype.Timestamp       `db:"failed_at" json:"failed_at"`
	Reviewed         pgtype.Bool            `db:"reviewed" json:"reviewed"`
	ReviewedBy       pgtype.Text            `db:"reviewed_by" json:"reviewed_by"`
	ReviewNotes      pgtype.Text            `db:"review_notes" json:"review_notes"`
	Reprocessable    pgtype.Bool            `db:"reprocessable" json:"reprocessable"`
	ReprocessedAt    pgtype.Timestamp       `db:"reprocessed_at" json:"reprocessed_at"`
}

type Session struct {
	ID        string           `db:"id" json:"id"`
	ExpiresAt pgtype.Timestamp `db:"expiresAt" json:"expiresAt"`
	Token     string           `db:"token" json:"token"`
	CreatedAt pgtype.Timestamp `db:"createdAt" json:"createdAt"`
	UpdatedAt pgtype.Timestamp `db:"updatedAt" json:"updatedAt"`
	IpAddress pgtype.Text      `db:"ipAddress" json:"ipAddress"`
	UserAgent pgtype.Text      `db:"userAgent" json:"userAgent"`
	UserId    string           `db:"userId" json:"userId"`
}

type Store struct {
	ID                 string           `db:"id" json:"id"`
	ChainSlug          string           `db:"chain_slug" json:"chain_slug"`
	Name               string           `db:"name" json:"name"`
	Address            pgtype.Text      `db:"address" json:"address"`
	City               pgtype.Text      `db:"city" json:"city"`
	PostalCode         pgtype.Text      `db:"postal_code" json:"postal_code"`
	Latitude           pgtype.Text      `db:"latitude" json:"latitude"`
	Longitude          pgtype.Text      `db:"longitude" json:"longitude"`
	IsVirtual          pgtype.Bool      `db:"is_virtual" json:"is_virtual"`
	PriceSourceStoreID pgtype.Text      `db:"price_source_store_id" json:"price_source_store_id"`
	Status             pgtype.Text      `db:"status" json:"status"`
	ApprovalNotes      pgtype.Text      `db:"approval_notes" json:"approval_notes"`
	ApprovedBy         pgtype.Text      `db:"approved_by" json:"approved_by"`
	ApprovedAt         pgtype.Timestamp `db:"approved_at" json:"approved_at"`
	CreatedAt          pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type StoreEnrichmentTask struct {
	ID           string           `db:"id" json:"id"`
	StoreID      string           `db:"store_id" json:"store_id"`
	Type         string           `db:"type" json:"type"`
	Status       string           `db:"status" json:"status"`
	InputData    pgtype.Text      `db:"input_data" json:"input_data"`
	OutputData   pgtype.Text      `db:"output_data" json:"output_data"`
	Confidence   pgtype.Text      `db:"confidence" json:"confidence"`
	VerifiedBy   pgtype.Text      `db:"verified_by" json:"verified_by"`
	VerifiedAt   pgtype.Timestamp `db:"verified_at" json:"verified_at"`
	ErrorMessage pgtype.Text      `db:"error_message" json:"error_message"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type StoreGroupHistory struct {
	ID           string           `db:"id" json:"id"`
	StoreID      string           `db:"store_id" json:"store_id"`
	PriceGroupID string           `db:"price_group_id" json:"price_group_id"`
	ValidFrom    pgtype.Timestamp `db:"valid_from" json:"valid_from"`
	ValidTo      pgtype.Timestamp `db:"valid_to" json:"valid_to"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type StoreIdentifier struct {
	ID        string           `db:"id" json:"id"`
	StoreID   string           `db:"store_id" json:"store_id"`
	Type      string           `db:"type" json:"type"`
	Value     string           `db:"value" json:"value"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type StoreItemPricePeriod struct {
	ID               int64            `db:"id" json:"id"`
	StoreItemStateID int64            `db:"store_item_state_id" json:"store_item_state_id"`
	Price            int32            `db:"price" json:"price"`
	DiscountPrice    pgtype.Int4      `db:"discount_price" json:"discount_price"`
	StartedAt        pgtype.Timestamp `db:"started_at" json:"started_at"`
	EndedAt          pgtype.Timestamp `db:"ended_at" json:"ended_at"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type StoreItemState struct {
	ID                    int64            `db:"id" json:"id"`
	StoreID               string           `db:"store_id" json:"store_id"`
	RetailerItemID        string           `db:"retailer_item_id" json:"retailer_item_id"`
	CurrentPrice          pgtype.Int4      `db:"current_price" json:"current_price"`
	PreviousPrice         pgtype.Int4      `db:"previous_price" json:"previous_price"`
	DiscountPrice         pgtype.Int4      `db:"discount_price" json:"discount_price"`
	DiscountStart         pgtype.Timestamp `db:"discount_start" json:"discount_start"`
	DiscountEnd           pgtype.Timestamp `db:"discount_end" json:"discount_end"`
	InStock               pgtype.Bool      `db:"in_stock" json:"in_stock"`
	UnitPrice             pgtype.Int4      `db:"unit_price" json:"unit_price"`
	UnitPriceBaseQuantity pgtype.Text      `db:"unit_price_base_quantity" json:"unit_price_base_quantity"`
	UnitPriceBaseUnit     pgtype.Text      `db:"unit_price_base_unit" json:"unit_price_base_unit"`
	LowestPrice30d        pgtype.Int4      `db:"lowest_price_30d" json:"lowest_price_30d"`
	AnchorPrice           pgtype.Int4      `db:"anchor_price" json:"anchor_price"`
	AnchorPriceAsOf       pgtype.Timestamp `db:"anchor_price_as_of" json:"anchor_price_as_of"`
	PriceSignature        pgtype.Text      `db:"price_signature" json:"price_signature"`
	LastSeenAt            pgtype.Timestamp `db:"last_seen_at" json:"last_seen_at"`
	UpdatedAt             pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type StorePriceException struct {
	StoreID        string           `db:"store_id" json:"store_id"`
	RetailerItemID string           `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32            `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4      `db:"discount_price" json:"discount_price"`
	Reason         string           `db:"reason" json:"reason"`
	ExpiresAt      pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	CreatedBy      pgtype.Text      `db:"created_by" json:"created_by"`
}

type TaskQueue struct {
	ID           string                 `db:"id" json:"id"`
	TaskType     string                 `db:"task_type" json:"task_type"`
	Payload      jsonb.TaskQueuePayload `db:"payload" json:"payload"`
	Priority     pgtype.Int4            `db:"priority" json:"priority"`
	Status       string                 `db:"status" json:"status"`
	ScheduledFor pgtype.Timestamp       `db:"scheduled_for" json:"scheduled_for"`
	StartedAt    pgtype.Timestamp       `db:"started_at" json:"started_at"`
	CompletedAt  pgtype.Timestamp       `db:"completed_at" json:"completed_at"`
	FailedAt     pgtype.Timestamp       `db:"failed_at" json:"failed_at"`
	WorkerID     pgtype.Text            `db:"worker_id" json:"worker_id"`
	RetryCount   pgtype.Int4            `db:"retry_count" json:"retry_count"`
	MaxRetries   pgtype.Int4            `db:"max_retries" json:"max_retries"`
	ErrorMessage pgtype.Text            `db:"error_message" json:"error_message"`
	CreatedAt    pgtype.Timestamp       `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp       `db:"updated_at" json:"updated_at"`
}

type Todo struct {
	ID        int32            `db:"id" json:"id"`
	Title     string           `db:"title" json:"title"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID            string           `db:"id" json:"id"`
	Name          string           `db:"name" json:"name"`
	Email         string           `db:"email" json:"email"`
	EmailVerified bool             `db:"emailVerified" json:"emailVerified"`
	Image         pgtype.Text      `db:"image" json:"image"`
	Role          pgtype.Text      `db:"role" json:"role"`
	Banned        pgtype.Bool      `db:"banned" json:"banned"`
	BannedAt      pgtype.Timestamp `db:"bannedAt" json:"bannedAt"`
	BannedReason  pgtype.Text      `db:"bannedReason" json:"bannedReason"`
	CreatedAt     pgtype.Timestamp `db:"createdAt" json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `db:"updatedAt" json:"updatedAt"`
}

type Verification struct {
	ID         string           `db:"id" json:"id"`
	Identifier string           `db:"identifier" json:"identifier"`
	Value      string           `db:"value" json:"value"`
	ExpiresAt  pgtype.Timestamp `db:"expiresAt" json:"expiresAt"`
	CreatedAt  pgtype.Timestamp `db:"createdAt" json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `db:"updatedAt" json:"updatedAt"`
}
