// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: optimizer.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveChains = `-- name: GetActiveChains :many

SELECT DISTINCT chain_slug
FROM stores
WHERE status = 'active'
`

// Price cache loading queries
func (q *Queries) GetActiveChains(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getActiveChains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var chain_slug string
		if err := rows.Scan(&chain_slug); err != nil {
			return nil, err
		}
		items = append(items, chain_slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveStoresByChain = `-- name: GetActiveStoresByChain :many
SELECT s.id, s.latitude, s.longitude
FROM stores s
WHERE s.chain_slug = $1
  AND s.status = 'active'
`

type GetActiveStoresByChainRow struct {
	ID        string      `db:"id" json:"id"`
	Latitude  pgtype.Text `db:"latitude" json:"latitude"`
	Longitude pgtype.Text `db:"longitude" json:"longitude"`
}

func (q *Queries) GetActiveStoresByChain(ctx context.Context, chainSlug string) ([]GetActiveStoresByChainRow, error) {
	rows, err := q.db.Query(ctx, getActiveStoresByChain, chainSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveStoresByChainRow{}
	for rows.Next() {
		var i GetActiveStoresByChainRow
		if err := rows.Scan(&i.ID, &i.Latitude, &i.Longitude); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceTiersByChain = `-- name: GetPriceTiersByChain :many
SELECT id, retailer_item_id, price, discount_price
FROM price_tiers
WHERE chain_slug = $1
`

type GetPriceTiersByChainRow struct {
	ID             string      `db:"id" json:"id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
}

func (q *Queries) GetPriceTiersByChain(ctx context.Context, chainSlug string) ([]GetPriceTiersByChainRow, error) {
	rows, err := q.db.Query(ctx, getPriceTiersByChain, chainSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPriceTiersByChainRow{}
	for rows.Next() {
		var i GetPriceTiersByChainRow
		if err := rows.Scan(
			&i.ID,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorePriceRefsByChain = `-- name: GetStorePriceRefsByChain :many
SELECT spr.store_id, spr.retailer_item_id, spr.price_tier_id
FROM store_price_refs spr
JOIN stores s ON s.id = spr.store_id
WHERE s.chain_slug = $1 AND s.status = 'active'
`

type GetStorePriceRefsByChainRow struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string `db:"price_tier_id" json:"price_tier_id"`
}

func (q *Queries) GetStorePriceRefsByChain(ctx context.Context, chainSlug string) ([]GetStorePriceRefsByChainRow, error) {
	rows, err := q.db.Query(ctx, getStorePriceRefsByChain, chainSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStorePriceRefsByChainRow{}
	for rows.Next() {
		var i GetStorePriceRefsByChainRow
		if err := rows.Scan(&i.StoreID, &i.RetailerItemID, &i.PriceTierID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
