// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRunProgressInfo = `-- name: GetRunProgressInfo :one
SELECT status, COALESCE(total_files, 0) as total_files, COALESCE(processed_files, 0) as processed_files
FROM ingestion_runs
WHERE id = $1
`

type GetRunProgressInfoRow struct {
	Status         string `db:"status" json:"status"`
	TotalFiles     int32  `db:"total_files" json:"total_files"`
	ProcessedFiles int32  `db:"processed_files" json:"processed_files"`
}

func (q *Queries) GetRunProgressInfo(ctx context.Context, id string) (GetRunProgressInfoRow, error) {
	row := q.db.QueryRow(ctx, getRunProgressInfo, id)
	var i GetRunProgressInfoRow
	err := row.Scan(&i.Status, &i.TotalFiles, &i.ProcessedFiles)
	return i, err
}

const incrementRunErrorCount = `-- name: IncrementRunErrorCount :exec
UPDATE ingestion_runs
SET error_count = COALESCE(error_count, 0) + $1
WHERE id = $2
`

type IncrementRunErrorCountParams struct {
	ErrorCount pgtype.Int4 `db:"error_count" json:"error_count"`
	ID         string      `db:"id" json:"id"`
}

func (q *Queries) IncrementRunErrorCount(ctx context.Context, arg IncrementRunErrorCountParams) error {
	_, err := q.db.Exec(ctx, incrementRunErrorCount, arg.ErrorCount, arg.ID)
	return err
}

const incrementRunProcessedEntries = `-- name: IncrementRunProcessedEntries :exec
UPDATE ingestion_runs
SET processed_entries = COALESCE(processed_entries, 0) + $1
WHERE id = $2
`

type IncrementRunProcessedEntriesParams struct {
	ProcessedEntries pgtype.Int4 `db:"processed_entries" json:"processed_entries"`
	ID               string      `db:"id" json:"id"`
}

func (q *Queries) IncrementRunProcessedEntries(ctx context.Context, arg IncrementRunProcessedEntriesParams) error {
	_, err := q.db.Exec(ctx, incrementRunProcessedEntries, arg.ProcessedEntries, arg.ID)
	return err
}

const incrementRunProcessedFiles = `-- name: IncrementRunProcessedFiles :exec
UPDATE ingestion_runs
SET processed_files = COALESCE(processed_files, 0) + 1
WHERE id = $1
`

func (q *Queries) IncrementRunProcessedFiles(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementRunProcessedFiles, id)
	return err
}

const updateRunCompleted = `-- name: UpdateRunCompleted :exec
UPDATE ingestion_runs
SET status = 'completed',
    completed_at = $1,
    processed_files = COALESCE($2, processed_files),
    processed_entries = COALESCE($3, processed_entries)
WHERE id = $4
`

type UpdateRunCompletedParams struct {
	CompletedAt      pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	ProcessedFiles   pgtype.Int4      `db:"processed_files" json:"processed_files"`
	ProcessedEntries pgtype.Int4      `db:"processed_entries" json:"processed_entries"`
	ID               string           `db:"id" json:"id"`
}

func (q *Queries) UpdateRunCompleted(ctx context.Context, arg UpdateRunCompletedParams) error {
	_, err := q.db.Exec(ctx, updateRunCompleted,
		arg.CompletedAt,
		arg.ProcessedFiles,
		arg.ProcessedEntries,
		arg.ID,
	)
	return err
}

const updateRunFailed = `-- name: UpdateRunFailed :exec
UPDATE ingestion_runs
SET status = 'failed',
    completed_at = NOW(),
    metadata = jsonb_set(
        COALESCE(metadata::jsonb, '{}'::jsonb),
        '{error}',
        to_jsonb($1::text)
    )::text
WHERE id = $2
`

type UpdateRunFailedParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	ID      string `db:"id" json:"id"`
}

func (q *Queries) UpdateRunFailed(ctx context.Context, arg UpdateRunFailedParams) error {
	_, err := q.db.Exec(ctx, updateRunFailed, arg.Column1, arg.ID)
	return err
}

const updateRunInterrupted = `-- name: UpdateRunInterrupted :exec
UPDATE ingestion_runs
SET status = 'interrupted',
    completed_at = $1,
    metadata = jsonb_set(
        COALESCE(metadata::jsonb, '{}'::jsonb),
        '{interrupted_reason}',
        to_jsonb('Service restarted during processing'::text)
    )::text
WHERE id = $2
`

type UpdateRunInterruptedParams struct {
	CompletedAt pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	ID          string           `db:"id" json:"id"`
}

func (q *Queries) UpdateRunInterrupted(ctx context.Context, arg UpdateRunInterruptedParams) error {
	_, err := q.db.Exec(ctx, updateRunInterrupted, arg.CompletedAt, arg.ID)
	return err
}

const updateRunResumed = `-- name: UpdateRunResumed :exec
UPDATE ingestion_runs
SET status = 'running',
    started_at = $1
WHERE id = $2
`

type UpdateRunResumedParams struct {
	StartedAt pgtype.Timestamp `db:"started_at" json:"started_at"`
	ID        string           `db:"id" json:"id"`
}

func (q *Queries) UpdateRunResumed(ctx context.Context, arg UpdateRunResumedParams) error {
	_, err := q.db.Exec(ctx, updateRunResumed, arg.StartedAt, arg.ID)
	return err
}

const updateRunStartedAt = `-- name: UpdateRunStartedAt :exec
UPDATE ingestion_runs
SET started_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateRunStartedAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateRunStartedAt, id)
	return err
}

const updateRunStatusSummary = `-- name: UpdateRunStatusSummary :exec
UPDATE ingestion_runs
SET status_reason = CASE
        WHEN status_severity IS NULL THEN $1
        WHEN CASE status_severity
                WHEN 'critical' THEN 3
                WHEN 'error' THEN 2
                WHEN 'warning' THEN 1
                ELSE 0
             END
             >= CASE $2
                WHEN 'critical' THEN 3
                WHEN 'error' THEN 2
                WHEN 'warning' THEN 1
                ELSE 0
             END THEN status_reason
        ELSE $1
    END,
    status_severity = CASE
        WHEN status_severity IS NULL THEN $2
        WHEN CASE status_severity
                WHEN 'critical' THEN 3
                WHEN 'error' THEN 2
                WHEN 'warning' THEN 1
                ELSE 0
             END
             >= CASE $2
                WHEN 'critical' THEN 3
                WHEN 'error' THEN 2
                WHEN 'warning' THEN 1
                ELSE 0
             END THEN status_severity
        ELSE $2
    END,
    status_type = CASE
        WHEN status_severity IS NULL THEN $3
        WHEN CASE status_severity
                WHEN 'critical' THEN 3
                WHEN 'error' THEN 2
                WHEN 'warning' THEN 1
                ELSE 0
             END
             >= CASE $2
                WHEN 'critical' THEN 3
                WHEN 'error' THEN 2
                WHEN 'warning' THEN 1
                ELSE 0
             END THEN status_type
        ELSE $3
    END
WHERE id = $4
`

type UpdateRunStatusSummaryParams struct {
	StatusReason   pgtype.Text `db:"status_reason" json:"status_reason"`
	StatusSeverity pgtype.Text `db:"status_severity" json:"status_severity"`
	StatusType     pgtype.Text `db:"status_type" json:"status_type"`
	ID             string      `db:"id" json:"id"`
}

func (q *Queries) UpdateRunStatusSummary(ctx context.Context, arg UpdateRunStatusSummaryParams) error {
	_, err := q.db.Exec(ctx, updateRunStatusSummary,
		arg.StatusReason,
		arg.StatusSeverity,
		arg.StatusType,
		arg.ID,
	)
	return err
}

const updateRunTotalFiles = `-- name: UpdateRunTotalFiles :exec
UPDATE ingestion_runs
SET total_files = $1
WHERE id = $2
`

type UpdateRunTotalFilesParams struct {
	TotalFiles pgtype.Int4 `db:"total_files" json:"total_files"`
	ID         string      `db:"id" json:"id"`
}

func (q *Queries) UpdateRunTotalFiles(ctx context.Context, arg UpdateRunTotalFilesParams) error {
	_, err := q.db.Exec(ctx, updateRunTotalFiles, arg.TotalFiles, arg.ID)
	return err
}
