// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_groups.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeStoreGroupMembership = `-- name: CloseStoreGroupMembership :exec
UPDATE store_group_history
SET valid_to = $1
WHERE store_id = $2 AND valid_to IS NULL
`

type CloseStoreGroupMembershipParams struct {
	ValidTo pgtype.Timestamp `db:"valid_to" json:"valid_to"`
	StoreID string           `db:"store_id" json:"store_id"`
}

func (q *Queries) CloseStoreGroupMembership(ctx context.Context, arg CloseStoreGroupMembershipParams) error {
	_, err := q.db.Exec(ctx, closeStoreGroupMembership, arg.ValidTo, arg.StoreID)
	return err
}

const countPriceGroupsByChain = `-- name: CountPriceGroupsByChain :one
SELECT COUNT(*) FROM price_groups WHERE chain_slug = $1
`

func (q *Queries) CountPriceGroupsByChain(ctx context.Context, chainSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceGroupsByChain, chainSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceGroup = `-- name: CreatePriceGroup :one
INSERT INTO price_groups (
    id, chain_slug, price_hash, hash_version, store_count, item_count,
    first_seen_at, last_seen_at, created_at, updated_at
) VALUES (
    $1, $2, $3, 1, 0, 0, $4, $4, $4, $4
)
ON CONFLICT (chain_slug, price_hash, hash_version) DO NOTHING
RETURNING id, chain_slug, price_hash, hash_version, store_count, item_count,
          first_seen_at, last_seen_at, created_at, updated_at
`

type CreatePriceGroupParams struct {
	ID          string           `db:"id" json:"id"`
	ChainSlug   string           `db:"chain_slug" json:"chain_slug"`
	PriceHash   string           `db:"price_hash" json:"price_hash"`
	FirstSeenAt pgtype.Timestamp `db:"first_seen_at" json:"first_seen_at"`
}

func (q *Queries) CreatePriceGroup(ctx context.Context, arg CreatePriceGroupParams) (PriceGroup, error) {
	row := q.db.QueryRow(ctx, createPriceGroup,
		arg.ID,
		arg.ChainSlug,
		arg.PriceHash,
		arg.FirstSeenAt,
	)
	var i PriceGroup
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.PriceHash,
		&i.HashVersion,
		&i.StoreCount,
		&i.ItemCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStoreGroupHistory = `-- name: CreateStoreGroupHistory :exec
INSERT INTO store_group_history (id, store_id, price_group_id, valid_from, valid_to, created_at)
VALUES ($1, $2, $3, $4, NULL, NOW())
`

type CreateStoreGroupHistoryParams struct {
	ID           string           `db:"id" json:"id"`
	StoreID      string           `db:"store_id" json:"store_id"`
	PriceGroupID string           `db:"price_group_id" json:"price_group_id"`
	ValidFrom    pgtype.Timestamp `db:"valid_from" json:"valid_from"`
}

func (q *Queries) CreateStoreGroupHistory(ctx context.Context, arg CreateStoreGroupHistoryParams) error {
	_, err := q.db.Exec(ctx, createStoreGroupHistory,
		arg.ID,
		arg.StoreID,
		arg.PriceGroupID,
		arg.ValidFrom,
	)
	return err
}

const decrementPriceGroupStoreCount = `-- name: DecrementPriceGroupStoreCount :exec
UPDATE price_groups
SET store_count = store_count - 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DecrementPriceGroupStoreCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, decrementPriceGroupStoreCount, id)
	return err
}

const deleteExpiredPriceExceptions = `-- name: DeleteExpiredPriceExceptions :execrows
DELETE FROM store_price_exceptions
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredPriceExceptions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPriceExceptions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanGroupPrices = `-- name: DeleteOrphanGroupPrices :exec
DELETE FROM group_prices
WHERE price_group_id IN (
    SELECT pg.id
    FROM price_groups pg
    WHERE pg.store_count = 0
      AND pg.last_seen_at < $1
      AND NOT EXISTS (
          SELECT 1
          FROM store_group_history sgh
          WHERE sgh.price_group_id = pg.id
            AND sgh.valid_to IS NULL
      )
)
`

func (q *Queries) DeleteOrphanGroupPrices(ctx context.Context, lastSeenAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteOrphanGroupPrices, lastSeenAt)
	return err
}

const deleteOrphanPriceGroups = `-- name: DeleteOrphanPriceGroups :execrows
DELETE FROM price_groups
WHERE store_count = 0
  AND last_seen_at < $1
  AND NOT EXISTS (
      SELECT 1
      FROM store_group_history sgh
      WHERE sgh.price_group_id = price_groups.id
        AND sgh.valid_to IS NULL
  )
`

func (q *Queries) DeleteOrphanPriceGroups(ctx context.Context, lastSeenAt pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanPriceGroups, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPriceGroupByHash = `-- name: FindPriceGroupByHash :one
SELECT id, chain_slug, price_hash, hash_version, store_count, item_count,
       first_seen_at, last_seen_at, created_at, updated_at
FROM price_groups
WHERE chain_slug = $1 AND price_hash = $2 AND hash_version = 1
LIMIT 1
`

type FindPriceGroupByHashParams struct {
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	PriceHash string `db:"price_hash" json:"price_hash"`
}

func (q *Queries) FindPriceGroupByHash(ctx context.Context, arg FindPriceGroupByHashParams) (PriceGroup, error) {
	row := q.db.QueryRow(ctx, findPriceGroupByHash, arg.ChainSlug, arg.PriceHash)
	var i PriceGroup
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.PriceHash,
		&i.HashVersion,
		&i.StoreCount,
		&i.ItemCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentStoreGroupId = `-- name: GetCurrentStoreGroupId :one
SELECT price_group_id
FROM store_group_history
WHERE store_id = $1 AND valid_to IS NULL
LIMIT 1
`

func (q *Queries) GetCurrentStoreGroupId(ctx context.Context, storeID string) (string, error) {
	row := q.db.QueryRow(ctx, getCurrentStoreGroupId, storeID)
	var price_group_id string
	err := row.Scan(&price_group_id)
	return price_group_id, err
}

const getHistoricalStorePrice = `-- name: GetHistoricalStorePrice :one
SELECT gp.price, gp.discount_price
FROM group_prices gp
JOIN store_group_history sgh ON sgh.price_group_id = gp.price_group_id
WHERE sgh.store_id = $1
  AND gp.retailer_item_id = $2
  AND sgh.valid_from <= $3
  AND (sgh.valid_to IS NULL OR sgh.valid_to > $3)
ORDER BY sgh.valid_from DESC
LIMIT 1
`

type GetHistoricalStorePriceParams struct {
	StoreID        string           `db:"store_id" json:"store_id"`
	RetailerItemID string           `db:"retailer_item_id" json:"retailer_item_id"`
	ValidFrom      pgtype.Timestamp `db:"valid_from" json:"valid_from"`
}

type GetHistoricalStorePriceRow struct {
	Price         int32       `db:"price" json:"price"`
	DiscountPrice pgtype.Int4 `db:"discount_price" json:"discount_price"`
}

func (q *Queries) GetHistoricalStorePrice(ctx context.Context, arg GetHistoricalStorePriceParams) (GetHistoricalStorePriceRow, error) {
	row := q.db.QueryRow(ctx, getHistoricalStorePrice, arg.StoreID, arg.RetailerItemID, arg.ValidFrom)
	var i GetHistoricalStorePriceRow
	err := row.Scan(&i.Price, &i.DiscountPrice)
	return i, err
}

const getPriceGroupById = `-- name: GetPriceGroupById :one
SELECT id, chain_slug, price_hash, hash_version, store_count, item_count,
       first_seen_at, last_seen_at, created_at, updated_at
FROM price_groups
WHERE id = $1
`

func (q *Queries) GetPriceGroupById(ctx context.Context, id string) (PriceGroup, error) {
	row := q.db.QueryRow(ctx, getPriceGroupById, id)
	var i PriceGroup
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.PriceHash,
		&i.HashVersion,
		&i.StoreCount,
		&i.ItemCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorePriceException = `-- name: GetStorePriceException :one
SELECT price, discount_price
FROM store_price_exceptions
WHERE store_id = $1 AND retailer_item_id = $2 AND expires_at > NOW()
LIMIT 1
`

type GetStorePriceExceptionParams struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

type GetStorePriceExceptionRow struct {
	Price         int32       `db:"price" json:"price"`
	DiscountPrice pgtype.Int4 `db:"discount_price" json:"discount_price"`
}

func (q *Queries) GetStorePriceException(ctx context.Context, arg GetStorePriceExceptionParams) (GetStorePriceExceptionRow, error) {
	row := q.db.QueryRow(ctx, getStorePriceException, arg.StoreID, arg.RetailerItemID)
	var i GetStorePriceExceptionRow
	err := row.Scan(&i.Price, &i.DiscountPrice)
	return i, err
}

const getStorePriceFromGroup = `-- name: GetStorePriceFromGroup :one
SELECT gp.price, gp.discount_price
FROM group_prices gp
JOIN store_group_history sgh ON sgh.price_group_id = gp.price_group_id
WHERE sgh.store_id = $1
  AND gp.retailer_item_id = $2
  AND sgh.valid_to IS NULL
LIMIT 1
`

type GetStorePriceFromGroupParams struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

type GetStorePriceFromGroupRow struct {
	Price         int32       `db:"price" json:"price"`
	DiscountPrice pgtype.Int4 `db:"discount_price" json:"discount_price"`
}

func (q *Queries) GetStorePriceFromGroup(ctx context.Context, arg GetStorePriceFromGroupParams) (GetStorePriceFromGroupRow, error) {
	row := q.db.QueryRow(ctx, getStorePriceFromGroup, arg.StoreID, arg.RetailerItemID)
	var i GetStorePriceFromGroupRow
	err := row.Scan(&i.Price, &i.DiscountPrice)
	return i, err
}

const incrementPriceGroupStoreCount = `-- name: IncrementPriceGroupStoreCount :exec
UPDATE price_groups
SET store_count = store_count + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementPriceGroupStoreCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementPriceGroupStoreCount, id)
	return err
}

const listGroupPrices = `-- name: ListGroupPrices :many
SELECT price_group_id, retailer_item_id, price, discount_price,
       unit_price, anchor_price, created_at
FROM group_prices
WHERE price_group_id = $1
ORDER BY retailer_item_id
`

func (q *Queries) ListGroupPrices(ctx context.Context, priceGroupID string) ([]GroupPrice, error) {
	rows, err := q.db.Query(ctx, listGroupPrices, priceGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupPrice{}
	for rows.Next() {
		var i GroupPrice
		if err := rows.Scan(
			&i.PriceGroupID,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceGroupsByChain = `-- name: ListPriceGroupsByChain :many
SELECT id, chain_slug, price_hash, hash_version, store_count, item_count,
       first_seen_at, last_seen_at, created_at, updated_at
FROM price_groups
WHERE chain_slug = $1
ORDER BY last_seen_at DESC
LIMIT $2 OFFSET $3
`

type ListPriceGroupsByChainParams struct {
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListPriceGroupsByChain(ctx context.Context, arg ListPriceGroupsByChainParams) ([]PriceGroup, error) {
	rows, err := q.db.Query(ctx, listPriceGroupsByChain, arg.ChainSlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceGroup{}
	for rows.Next() {
		var i PriceGroup
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.PriceHash,
			&i.HashVersion,
			&i.StoreCount,
			&i.ItemCount,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorePricesViaGroup = `-- name: ListStorePricesViaGroup :many
SELECT
    gp.retailer_item_id,
    gp.price,
    gp.discount_price,
    gp.unit_price,
    gp.anchor_price,
    COALESCE(spe.store_id, '') != '' AS is_exception
FROM group_prices gp
JOIN store_group_history sgh ON sgh.price_group_id = gp.price_group_id
LEFT JOIN store_price_exceptions spe ON spe.store_id = sgh.store_id
    AND spe.retailer_item_id = gp.retailer_item_id
    AND spe.expires_at > NOW()
WHERE sgh.store_id = $1 AND sgh.valid_to IS NULL
ORDER BY gp.retailer_item_id
`

type ListStorePricesViaGroupRow struct {
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	IsException    bool        `db:"is_exception" json:"is_exception"`
}

func (q *Queries) ListStorePricesViaGroup(ctx context.Context, storeID string) ([]ListStorePricesViaGroupRow, error) {
	rows, err := q.db.Query(ctx, listStorePricesViaGroup, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorePricesViaGroupRow{}
	for rows.Next() {
		var i ListStorePricesViaGroupRow
		if err := rows.Scan(
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.IsException,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceGroupItemCount = `-- name: UpdatePriceGroupItemCount :exec
UPDATE price_groups
SET item_count = (
    SELECT COUNT(*) FROM group_prices WHERE price_group_id = $1
),
updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdatePriceGroupItemCount(ctx context.Context, priceGroupID string) error {
	_, err := q.db.Exec(ctx, updatePriceGroupItemCount, priceGroupID)
	return err
}

const updatePriceGroupLastSeen = `-- name: UpdatePriceGroupLastSeen :exec
UPDATE price_groups
SET last_seen_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdatePriceGroupLastSeen(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updatePriceGroupLastSeen, id)
	return err
}

const upsertGroupPrice = `-- name: UpsertGroupPrice :exec
INSERT INTO group_prices (
    price_group_id, retailer_item_id, price, discount_price,
    unit_price, anchor_price, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (price_group_id, retailer_item_id) DO UPDATE SET
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    unit_price = EXCLUDED.unit_price,
    anchor_price = EXCLUDED.anchor_price
`

type UpsertGroupPriceParams struct {
	PriceGroupID   string           `db:"price_group_id" json:"price_group_id"`
	RetailerItemID string           `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32            `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4      `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4      `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4      `db:"anchor_price" json:"anchor_price"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertGroupPrice(ctx context.Context, arg UpsertGroupPriceParams) error {
	_, err := q.db.Exec(ctx, upsertGroupPrice,
		arg.PriceGroupID,
		arg.RetailerItemID,
		arg.Price,
		arg.DiscountPrice,
		arg.UnitPrice,
		arg.AnchorPrice,
		arg.CreatedAt,
	)
	return err
}
