// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_tiers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPriceTiersByChain = `-- name: CountPriceTiersByChain :one
SELECT COUNT(*) FROM price_tiers WHERE chain_slug = $1
`

func (q *Queries) CountPriceTiersByChain(ctx context.Context, chainSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceTiersByChain, chainSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStorePriceRefsByChain = `-- name: CountStorePriceRefsByChain :one
SELECT COUNT(*)
FROM store_price_refs spr
JOIN stores s ON s.id = spr.store_id
WHERE s.chain_slug = $1
`

func (q *Queries) CountStorePriceRefsByChain(ctx context.Context, chainSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countStorePriceRefsByChain, chainSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceTier = `-- name: CreatePriceTier :one
INSERT INTO price_tiers (
    id, chain_slug, retailer_item_id, price, discount_price,
    unit_price, anchor_price, first_seen_at, last_seen_at,
    store_count, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW(), 0, NOW()
)
ON CONFLICT (chain_slug, retailer_item_id, price, COALESCE(discount_price, -1)) DO NOTHING
RETURNING id, chain_slug, retailer_item_id, price, discount_price,
          unit_price, anchor_price, first_seen_at, last_seen_at,
          store_count, created_at
`

type CreatePriceTierParams struct {
	ID             string      `db:"id" json:"id"`
	ChainSlug      string      `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
}

// Create a new price tier, returns the tier on success
func (q *Queries) CreatePriceTier(ctx context.Context, arg CreatePriceTierParams) (PriceTier, error) {
	row := q.db.QueryRow(ctx, createPriceTier,
		arg.ID,
		arg.ChainSlug,
		arg.RetailerItemID,
		arg.Price,
		arg.DiscountPrice,
		arg.UnitPrice,
		arg.AnchorPrice,
	)
	var i PriceTier
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.RetailerItemID,
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.StoreCount,
		&i.CreatedAt,
	)
	return i, err
}

const decrementPriceTierStoreCount = `-- name: DecrementPriceTierStoreCount :exec
UPDATE price_tiers
SET store_count = store_count - 1
WHERE id = $1
`

func (q *Queries) DecrementPriceTierStoreCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, decrementPriceTierStoreCount, id)
	return err
}

const deleteOrphanPriceTiers = `-- name: DeleteOrphanPriceTiers :execrows
DELETE FROM price_tiers
WHERE store_count = 0
  AND last_seen_at < $1
`

// Clean up price tiers with no store references
func (q *Queries) DeleteOrphanPriceTiers(ctx context.Context, lastSeenAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanPriceTiers, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStoreAllPriceRefs = `-- name: DeleteStoreAllPriceRefs :exec
DELETE FROM store_price_refs
WHERE store_id = $1
`

// Remove all price refs for a store
func (q *Queries) DeleteStoreAllPriceRefs(ctx context.Context, storeID string) error {
	_, err := q.db.Exec(ctx, deleteStoreAllPriceRefs, storeID)
	return err
}

const deleteStorePriceRef = `-- name: DeleteStorePriceRef :exec
DELETE FROM store_price_refs
WHERE store_id = $1 AND retailer_item_id = $2
`

type DeleteStorePriceRefParams struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

func (q *Queries) DeleteStorePriceRef(ctx context.Context, arg DeleteStorePriceRefParams) error {
	_, err := q.db.Exec(ctx, deleteStorePriceRef, arg.StoreID, arg.RetailerItemID)
	return err
}

const findPriceTier = `-- name: FindPriceTier :one
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, first_seen_at, last_seen_at,
       store_count, created_at
FROM price_tiers
WHERE chain_slug = $1
  AND retailer_item_id = $2
  AND price = $3
  AND COALESCE(discount_price, -1) = COALESCE($4::int, -1)
LIMIT 1
`

type FindPriceTierParams struct {
	ChainSlug      string `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32  `db:"price" json:"price"`
	Column4        int32  `db:"column_4" json:"column_4"`
}

// Find existing price tier by chain, item, price, and discount
func (q *Queries) FindPriceTier(ctx context.Context, arg FindPriceTierParams) (PriceTier, error) {
	row := q.db.QueryRow(ctx, findPriceTier,
		arg.ChainSlug,
		arg.RetailerItemID,
		arg.Price,
		arg.Column4,
	)
	var i PriceTier
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.RetailerItemID,
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.StoreCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPriceTierById = `-- name: GetPriceTierById :one
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, first_seen_at, last_seen_at,
       store_count, created_at
FROM price_tiers
WHERE id = $1
`

func (q *Queries) GetPriceTierById(ctx context.Context, id string) (PriceTier, error) {
	row := q.db.QueryRow(ctx, getPriceTierById, id)
	var i PriceTier
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.RetailerItemID,
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.StoreCount,
		&i.CreatedAt,
	)
	return i, err
}

const getStorePriceRef = `-- name: GetStorePriceRef :one
SELECT store_id, retailer_item_id, price_tier_id, in_stock, last_seen_at
FROM store_price_refs
WHERE store_id = $1 AND retailer_item_id = $2
`

type GetStorePriceRefParams struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

// Get the price tier reference for a specific store+item
func (q *Queries) GetStorePriceRef(ctx context.Context, arg GetStorePriceRefParams) (StorePriceRef, error) {
	row := q.db.QueryRow(ctx, getStorePriceRef, arg.StoreID, arg.RetailerItemID)
	var i StorePriceRef
	err := row.Scan(
		&i.StoreID,
		&i.RetailerItemID,
		&i.PriceTierID,
		&i.InStock,
		&i.LastSeenAt,
	)
	return i, err
}

const getStorePriceViaTier = `-- name: GetStorePriceViaTier :one
SELECT pt.price, pt.discount_price, pt.unit_price, pt.anchor_price
FROM store_price_refs spr
JOIN price_tiers pt ON pt.id = spr.price_tier_id
WHERE spr.store_id = $1 AND spr.retailer_item_id = $2
`

type GetStorePriceViaTierParams struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

type GetStorePriceViaTierRow struct {
	Price         int32       `db:"price" json:"price"`
	DiscountPrice pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice     pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice   pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
}

// Get price for a specific store+item via tier join
func (q *Queries) GetStorePriceViaTier(ctx context.Context, arg GetStorePriceViaTierParams) (GetStorePriceViaTierRow, error) {
	row := q.db.QueryRow(ctx, getStorePriceViaTier, arg.StoreID, arg.RetailerItemID)
	var i GetStorePriceViaTierRow
	err := row.Scan(
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
	)
	return i, err
}

const incrementPriceTierStoreCount = `-- name: IncrementPriceTierStoreCount :exec
UPDATE price_tiers
SET store_count = store_count + 1,
    last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementPriceTierStoreCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementPriceTierStoreCount, id)
	return err
}

const listPriceTiersByChain = `-- name: ListPriceTiersByChain :many
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, first_seen_at, last_seen_at,
       store_count, created_at
FROM price_tiers
WHERE chain_slug = $1
ORDER BY last_seen_at DESC
LIMIT $2 OFFSET $3
`

type ListPriceTiersByChainParams struct {
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListPriceTiersByChain(ctx context.Context, arg ListPriceTiersByChainParams) ([]PriceTier, error) {
	rows, err := q.db.Query(ctx, listPriceTiersByChain, arg.ChainSlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceTier{}
	for rows.Next() {
		var i PriceTier
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.StoreCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTiersByItem = `-- name: ListPriceTiersByItem :many
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, first_seen_at, last_seen_at,
       store_count, created_at
FROM price_tiers
WHERE retailer_item_id = $1
ORDER BY price
`

func (q *Queries) ListPriceTiersByItem(ctx context.Context, retailerItemID string) ([]PriceTier, error) {
	rows, err := q.db.Query(ctx, listPriceTiersByItem, retailerItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceTier{}
	for rows.Next() {
		var i PriceTier
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.StoreCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTiersForCache = `-- name: ListPriceTiersForCache :many
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price
FROM price_tiers
WHERE chain_slug = $1
`

type ListPriceTiersForCacheRow struct {
	ID             string      `db:"id" json:"id"`
	ChainSlug      string      `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
}

// Get all price tiers for a chain (for cache loading)
func (q *Queries) ListPriceTiersForCache(ctx context.Context, chainSlug string) ([]ListPriceTiersForCacheRow, error) {
	rows, err := q.db.Query(ctx, listPriceTiersForCache, chainSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceTiersForCacheRow{}
	for rows.Next() {
		var i ListPriceTiersForCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorePricesViaTiers = `-- name: ListStorePricesViaTiers :many
SELECT
    spr.retailer_item_id,
    pt.id AS price_tier_id,
    pt.price,
    pt.discount_price,
    pt.unit_price,
    pt.anchor_price,
    spr.in_stock
FROM store_price_refs spr
JOIN price_tiers pt ON pt.id = spr.price_tier_id
WHERE spr.store_id = $1
ORDER BY spr.retailer_item_id
`

type ListStorePricesViaTiersRow struct {
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string      `db:"price_tier_id" json:"price_tier_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	InStock        pgtype.Bool `db:"in_stock" json:"in_stock"`
}

// Get all prices for a store via tier join (for cache loading)
func (q *Queries) ListStorePricesViaTiers(ctx context.Context, storeID string) ([]ListStorePricesViaTiersRow, error) {
	rows, err := q.db.Query(ctx, listStorePricesViaTiers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorePricesViaTiersRow{}
	for rows.Next() {
		var i ListStorePricesViaTiersRow
		if err := rows.Scan(
			&i.RetailerItemID,
			&i.PriceTierID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.InStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreRefsByChain = `-- name: ListStoreRefsByChain :many
SELECT
    spr.store_id,
    spr.retailer_item_id,
    spr.price_tier_id,
    spr.in_stock
FROM store_price_refs spr
JOIN stores s ON s.id = spr.store_id
WHERE s.chain_slug = $1 AND s.status = 'active'
`

type ListStoreRefsByChainRow struct {
	StoreID        string      `db:"store_id" json:"store_id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string      `db:"price_tier_id" json:"price_tier_id"`
	InStock        pgtype.Bool `db:"in_stock" json:"in_stock"`
}

// Get all store->tier references for a chain (for cache loading)
func (q *Queries) ListStoreRefsByChain(ctx context.Context, chainSlug string) ([]ListStoreRefsByChainRow, error) {
	rows, err := q.db.Query(ctx, listStoreRefsByChain, chainSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoreRefsByChainRow{}
	for rows.Next() {
		var i ListStoreRefsByChainRow
		if err := rows.Scan(
			&i.StoreID,
			&i.RetailerItemID,
			&i.PriceTierID,
			&i.InStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceTierLastSeen = `-- name: UpdatePriceTierLastSeen :exec
UPDATE price_tiers
SET last_seen_at = NOW()
WHERE id = $1
`

// Update last_seen_at timestamp for a price tier
func (q *Queries) UpdatePriceTierLastSeen(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updatePriceTierLastSeen, id)
	return err
}

const updatePriceTierStoreCount = `-- name: UpdatePriceTierStoreCount :exec
UPDATE price_tiers
SET store_count = (
    SELECT COUNT(DISTINCT store_id)
    FROM store_price_refs
    WHERE price_tier_id = $1
)
WHERE id = $1
`

// Recalculate store_count from store_price_refs
func (q *Queries) UpdatePriceTierStoreCount(ctx context.Context, priceTierID string) error {
	_, err := q.db.Exec(ctx, updatePriceTierStoreCount, priceTierID)
	return err
}

const upsertStorePriceRef = `-- name: UpsertStorePriceRef :exec
INSERT INTO store_price_refs (
    store_id, retailer_item_id, price_tier_id, in_stock, last_seen_at
) VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (store_id, retailer_item_id) DO UPDATE SET
    price_tier_id = EXCLUDED.price_tier_id,
    in_stock = EXCLUDED.in_stock,
    last_seen_at = NOW()
`

type UpsertStorePriceRefParams struct {
	StoreID        string      `db:"store_id" json:"store_id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string      `db:"price_tier_id" json:"price_tier_id"`
	InStock        pgtype.Bool `db:"in_stock" json:"in_stock"`
}

// Insert or update a store->tier reference
func (q *Queries) UpsertStorePriceRef(ctx context.Context, arg UpsertStorePriceRefParams) error {
	_, err := q.db.Exec(ctx, upsertStorePriceRef,
		arg.StoreID,
		arg.RetailerItemID,
		arg.PriceTierID,
		arg.InStock,
	)
	return err
}
