// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_tiers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPriceTiersByChain = `-- name: CountPriceTiersByChain :one
SELECT COUNT(*) FROM price_tiers WHERE chain_slug = $1
`

func (q *Queries) CountPriceTiersByChain(ctx context.Context, chainSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceTiersByChain, chainSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStorePriceRefsByChain = `-- name: CountStorePriceRefsByChain :one
SELECT COUNT(*)
FROM store_price_refs spr
JOIN stores s ON s.id = spr.store_id
WHERE s.chain_slug = $1
`

func (q *Queries) CountStorePriceRefsByChain(ctx context.Context, chainSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countStorePriceRefsByChain, chainSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceTier = `-- name: CreatePriceTier :one
INSERT INTO price_tiers (
    id, chain_slug, retailer_item_id, price, discount_price,
    unit_price, anchor_price, target_date, first_seen_at, last_seen_at,
    store_count, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW(), 0, NOW()
)
ON CONFLICT (target_date, chain_slug, retailer_item_id, price, COALESCE(discount_price, -1)) DO NOTHING
RETURNING id, chain_slug, retailer_item_id, price, discount_price,
          unit_price, anchor_price, target_date, first_seen_at, last_seen_at,
          store_count, created_at
`

type CreatePriceTierParams struct {
	ID             string      `db:"id" json:"id"`
	ChainSlug      string      `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
}

type CreatePriceTierRow struct {
	ID             string             `db:"id" json:"id"`
	ChainSlug      string             `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string             `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32              `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4        `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4        `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4        `db:"anchor_price" json:"anchor_price"`
	TargetDate     pgtype.Date        `db:"target_date" json:"target_date"`
	FirstSeenAt    pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	StoreCount     int32              `db:"store_count" json:"store_count"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Create a new price tier, returns the tier on success
func (q *Queries) CreatePriceTier(ctx context.Context, arg CreatePriceTierParams) (CreatePriceTierRow, error) {
	row := q.db.QueryRow(ctx, createPriceTier,
		arg.ID,
		arg.ChainSlug,
		arg.RetailerItemID,
		arg.Price,
		arg.DiscountPrice,
		arg.UnitPrice,
		arg.AnchorPrice,
		arg.TargetDate,
	)
	var i CreatePriceTierRow
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.RetailerItemID,
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
		&i.TargetDate,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.StoreCount,
		&i.CreatedAt,
	)
	return i, err
}

const decrementPriceTierStoreCount = `-- name: DecrementPriceTierStoreCount :exec
UPDATE price_tiers
SET store_count = store_count - 1
WHERE id = $1
`

func (q *Queries) DecrementPriceTierStoreCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, decrementPriceTierStoreCount, id)
	return err
}

const deleteOrphanPriceTiers = `-- name: DeleteOrphanPriceTiers :execrows
DELETE FROM price_tiers
WHERE store_count = 0
  AND last_seen_at < $1
`

// Clean up price tiers with no store references
func (q *Queries) DeleteOrphanPriceTiers(ctx context.Context, lastSeenAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanPriceTiers, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePriceTiersByChainAndDate = `-- name: DeletePriceTiersByChainAndDate :execrows
DELETE FROM price_tiers
WHERE chain_slug = $1 AND target_date = $2
`

type DeletePriceTiersByChainAndDateParams struct {
	ChainSlug  string      `db:"chain_slug" json:"chain_slug"`
	TargetDate pgtype.Date `db:"target_date" json:"target_date"`
}

// Delete all price_tiers for a chain at a specific date
// Used for same-day overwrite during ingestion
func (q *Queries) DeletePriceTiersByChainAndDate(ctx context.Context, arg DeletePriceTiersByChainAndDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePriceTiersByChainAndDate, arg.ChainSlug, arg.TargetDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStoreAllPriceRefs = `-- name: DeleteStoreAllPriceRefs :exec
DELETE FROM store_price_refs
WHERE store_id = $1
`

// Remove all price refs for a store
func (q *Queries) DeleteStoreAllPriceRefs(ctx context.Context, storeID string) error {
	_, err := q.db.Exec(ctx, deleteStoreAllPriceRefs, storeID)
	return err
}

const deleteStorePriceRef = `-- name: DeleteStorePriceRef :exec
DELETE FROM store_price_refs
WHERE target_date = $1 AND store_id = $2 AND retailer_item_id = $3
`

type DeleteStorePriceRefParams struct {
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
	StoreID        string      `db:"store_id" json:"store_id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
}

func (q *Queries) DeleteStorePriceRef(ctx context.Context, arg DeleteStorePriceRefParams) error {
	_, err := q.db.Exec(ctx, deleteStorePriceRef, arg.TargetDate, arg.StoreID, arg.RetailerItemID)
	return err
}

const deleteStorePriceRefsByChainAndDate = `-- name: DeleteStorePriceRefsByChainAndDate :execrows
DELETE FROM store_price_refs
WHERE target_date = $1
  AND store_id IN (
    SELECT id FROM stores WHERE chain_slug = $2
  )
`

type DeleteStorePriceRefsByChainAndDateParams struct {
	TargetDate pgtype.Date `db:"target_date" json:"target_date"`
	ChainSlug  string      `db:"chain_slug" json:"chain_slug"`
}

// Delete all store_price_refs for stores in a chain at a specific date
// Used for same-day overwrite during ingestion
func (q *Queries) DeleteStorePriceRefsByChainAndDate(ctx context.Context, arg DeleteStorePriceRefsByChainAndDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStorePriceRefsByChainAndDate, arg.TargetDate, arg.ChainSlug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPriceTier = `-- name: FindPriceTier :one
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, target_date, first_seen_at, last_seen_at,
       store_count, created_at
FROM price_tiers
WHERE target_date = $1
  AND chain_slug = $2
  AND retailer_item_id = $3
  AND price = $4
  AND COALESCE(discount_price, -1) = COALESCE($5::int, -1)
LIMIT 1
`

type FindPriceTierParams struct {
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
	ChainSlug      string      `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32       `db:"price" json:"price"`
	Column5        int32       `db:"column_5" json:"column_5"`
}

type FindPriceTierRow struct {
	ID             string             `db:"id" json:"id"`
	ChainSlug      string             `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string             `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32              `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4        `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4        `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4        `db:"anchor_price" json:"anchor_price"`
	TargetDate     pgtype.Date        `db:"target_date" json:"target_date"`
	FirstSeenAt    pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	StoreCount     int32              `db:"store_count" json:"store_count"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Find existing price tier by target_date, chain, item, price, and discount
func (q *Queries) FindPriceTier(ctx context.Context, arg FindPriceTierParams) (FindPriceTierRow, error) {
	row := q.db.QueryRow(ctx, findPriceTier,
		arg.TargetDate,
		arg.ChainSlug,
		arg.RetailerItemID,
		arg.Price,
		arg.Column5,
	)
	var i FindPriceTierRow
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.RetailerItemID,
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
		&i.TargetDate,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.StoreCount,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestStorePriceViaTier = `-- name: GetLatestStorePriceViaTier :one
SELECT pt.price, pt.discount_price, pt.unit_price, pt.anchor_price, spr.target_date
FROM store_price_refs spr
JOIN price_tiers pt ON pt.id = spr.price_tier_id
WHERE spr.store_id = $1
  AND spr.retailer_item_id = $2
  AND spr.target_date = (
    SELECT MAX(target_date) FROM store_price_refs
    WHERE store_id = $1 AND retailer_item_id = $2
  )
`

type GetLatestStorePriceViaTierParams struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

type GetLatestStorePriceViaTierRow struct {
	Price         int32       `db:"price" json:"price"`
	DiscountPrice pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice     pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice   pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	TargetDate    pgtype.Date `db:"target_date" json:"target_date"`
}

// Get the latest price for a store+item (uses MAX(target_date))
func (q *Queries) GetLatestStorePriceViaTier(ctx context.Context, arg GetLatestStorePriceViaTierParams) (GetLatestStorePriceViaTierRow, error) {
	row := q.db.QueryRow(ctx, getLatestStorePriceViaTier, arg.StoreID, arg.RetailerItemID)
	var i GetLatestStorePriceViaTierRow
	err := row.Scan(
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
		&i.TargetDate,
	)
	return i, err
}

const getMaxTargetDateForChain = `-- name: GetMaxTargetDateForChain :one

SELECT MAX(target_date)::date AS max_date
FROM price_tiers
WHERE chain_slug = $1
`

// ============================================================================
// Date-Scoped Operations for Ingestion
// ============================================================================
// Get the latest target_date for a chain (for production queries)
func (q *Queries) GetMaxTargetDateForChain(ctx context.Context, chainSlug string) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getMaxTargetDateForChain, chainSlug)
	var max_date pgtype.Date
	err := row.Scan(&max_date)
	return max_date, err
}

const getPriceTierById = `-- name: GetPriceTierById :one
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, target_date, first_seen_at, last_seen_at,
       store_count, created_at
FROM price_tiers
WHERE id = $1
`

type GetPriceTierByIdRow struct {
	ID             string             `db:"id" json:"id"`
	ChainSlug      string             `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string             `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32              `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4        `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4        `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4        `db:"anchor_price" json:"anchor_price"`
	TargetDate     pgtype.Date        `db:"target_date" json:"target_date"`
	FirstSeenAt    pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	StoreCount     int32              `db:"store_count" json:"store_count"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPriceTierById(ctx context.Context, id string) (GetPriceTierByIdRow, error) {
	row := q.db.QueryRow(ctx, getPriceTierById, id)
	var i GetPriceTierByIdRow
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.RetailerItemID,
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
		&i.TargetDate,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.StoreCount,
		&i.CreatedAt,
	)
	return i, err
}

const getStorePriceRef = `-- name: GetStorePriceRef :one
SELECT store_id, retailer_item_id, price_tier_id, in_stock, target_date, last_seen_at
FROM store_price_refs
WHERE target_date = $1 AND store_id = $2 AND retailer_item_id = $3
`

type GetStorePriceRefParams struct {
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
	StoreID        string      `db:"store_id" json:"store_id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
}

type GetStorePriceRefRow struct {
	StoreID        string             `db:"store_id" json:"store_id"`
	RetailerItemID string             `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string             `db:"price_tier_id" json:"price_tier_id"`
	InStock        pgtype.Bool        `db:"in_stock" json:"in_stock"`
	TargetDate     pgtype.Date        `db:"target_date" json:"target_date"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

// Get the price tier reference for a specific store+item at a specific date
func (q *Queries) GetStorePriceRef(ctx context.Context, arg GetStorePriceRefParams) (GetStorePriceRefRow, error) {
	row := q.db.QueryRow(ctx, getStorePriceRef, arg.TargetDate, arg.StoreID, arg.RetailerItemID)
	var i GetStorePriceRefRow
	err := row.Scan(
		&i.StoreID,
		&i.RetailerItemID,
		&i.PriceTierID,
		&i.InStock,
		&i.TargetDate,
		&i.LastSeenAt,
	)
	return i, err
}

const getStorePriceViaTier = `-- name: GetStorePriceViaTier :one
SELECT pt.price, pt.discount_price, pt.unit_price, pt.anchor_price, spr.target_date
FROM store_price_refs spr
JOIN price_tiers pt ON pt.id = spr.price_tier_id
WHERE spr.target_date = $1 AND spr.store_id = $2 AND spr.retailer_item_id = $3
`

type GetStorePriceViaTierParams struct {
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
	StoreID        string      `db:"store_id" json:"store_id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
}

type GetStorePriceViaTierRow struct {
	Price         int32       `db:"price" json:"price"`
	DiscountPrice pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice     pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice   pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	TargetDate    pgtype.Date `db:"target_date" json:"target_date"`
}

// Get price for a specific store+item via tier join at a specific date
func (q *Queries) GetStorePriceViaTier(ctx context.Context, arg GetStorePriceViaTierParams) (GetStorePriceViaTierRow, error) {
	row := q.db.QueryRow(ctx, getStorePriceViaTier, arg.TargetDate, arg.StoreID, arg.RetailerItemID)
	var i GetStorePriceViaTierRow
	err := row.Scan(
		&i.Price,
		&i.DiscountPrice,
		&i.UnitPrice,
		&i.AnchorPrice,
		&i.TargetDate,
	)
	return i, err
}

const incrementPriceTierStoreCount = `-- name: IncrementPriceTierStoreCount :exec
UPDATE price_tiers
SET store_count = store_count + 1,
    last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementPriceTierStoreCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementPriceTierStoreCount, id)
	return err
}

const listLatestPriceTiersByChain = `-- name: ListLatestPriceTiersByChain :many
SELECT pt.id, pt.chain_slug, pt.retailer_item_id, pt.price, pt.discount_price,
       pt.unit_price, pt.anchor_price, pt.target_date, pt.first_seen_at, pt.last_seen_at,
       pt.store_count, pt.created_at
FROM price_tiers pt
WHERE pt.chain_slug = $1
  AND pt.target_date = (SELECT MAX(pt2.target_date) FROM price_tiers pt2 WHERE pt2.chain_slug = $1)
ORDER BY pt.retailer_item_id
`

type ListLatestPriceTiersByChainRow struct {
	ID             string             `db:"id" json:"id"`
	ChainSlug      string             `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string             `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32              `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4        `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4        `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4        `db:"anchor_price" json:"anchor_price"`
	TargetDate     pgtype.Date        `db:"target_date" json:"target_date"`
	FirstSeenAt    pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	StoreCount     int32              `db:"store_count" json:"store_count"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Get all price tiers for a chain at the latest date
func (q *Queries) ListLatestPriceTiersByChain(ctx context.Context, chainSlug string) ([]ListLatestPriceTiersByChainRow, error) {
	rows, err := q.db.Query(ctx, listLatestPriceTiersByChain, chainSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestPriceTiersByChainRow{}
	for rows.Next() {
		var i ListLatestPriceTiersByChainRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.TargetDate,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.StoreCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestStorePricesViaTiers = `-- name: ListLatestStorePricesViaTiers :many
SELECT
    spr.retailer_item_id,
    pt.id AS price_tier_id,
    pt.price,
    pt.discount_price,
    pt.unit_price,
    pt.anchor_price,
    spr.in_stock,
    spr.target_date
FROM store_price_refs spr
JOIN price_tiers pt ON pt.id = spr.price_tier_id
JOIN stores s ON s.id = spr.store_id
WHERE spr.store_id = $1
  AND spr.target_date = (
    SELECT MAX(target_date) FROM price_tiers WHERE chain_slug = s.chain_slug
  )
ORDER BY spr.retailer_item_id
`

type ListLatestStorePricesViaTiersRow struct {
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string      `db:"price_tier_id" json:"price_tier_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	InStock        pgtype.Bool `db:"in_stock" json:"in_stock"`
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
}

// Get all latest prices for a store (uses MAX(target_date) per chain)
func (q *Queries) ListLatestStorePricesViaTiers(ctx context.Context, storeID string) ([]ListLatestStorePricesViaTiersRow, error) {
	rows, err := q.db.Query(ctx, listLatestStorePricesViaTiers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestStorePricesViaTiersRow{}
	for rows.Next() {
		var i ListLatestStorePricesViaTiersRow
		if err := rows.Scan(
			&i.RetailerItemID,
			&i.PriceTierID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.InStock,
			&i.TargetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTiersByChain = `-- name: ListPriceTiersByChain :many
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, target_date, first_seen_at, last_seen_at,
       store_count, created_at
FROM price_tiers
WHERE chain_slug = $1
ORDER BY target_date DESC, last_seen_at DESC
LIMIT $2 OFFSET $3
`

type ListPriceTiersByChainParams struct {
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

type ListPriceTiersByChainRow struct {
	ID             string             `db:"id" json:"id"`
	ChainSlug      string             `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string             `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32              `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4        `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4        `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4        `db:"anchor_price" json:"anchor_price"`
	TargetDate     pgtype.Date        `db:"target_date" json:"target_date"`
	FirstSeenAt    pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	StoreCount     int32              `db:"store_count" json:"store_count"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListPriceTiersByChain(ctx context.Context, arg ListPriceTiersByChainParams) ([]ListPriceTiersByChainRow, error) {
	rows, err := q.db.Query(ctx, listPriceTiersByChain, arg.ChainSlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceTiersByChainRow{}
	for rows.Next() {
		var i ListPriceTiersByChainRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.TargetDate,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.StoreCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTiersByItem = `-- name: ListPriceTiersByItem :many
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, target_date, first_seen_at, last_seen_at,
       store_count, created_at
FROM price_tiers
WHERE retailer_item_id = $1
ORDER BY target_date DESC, price
`

type ListPriceTiersByItemRow struct {
	ID             string             `db:"id" json:"id"`
	ChainSlug      string             `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string             `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32              `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4        `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4        `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4        `db:"anchor_price" json:"anchor_price"`
	TargetDate     pgtype.Date        `db:"target_date" json:"target_date"`
	FirstSeenAt    pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	StoreCount     int32              `db:"store_count" json:"store_count"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListPriceTiersByItem(ctx context.Context, retailerItemID string) ([]ListPriceTiersByItemRow, error) {
	rows, err := q.db.Query(ctx, listPriceTiersByItem, retailerItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceTiersByItemRow{}
	for rows.Next() {
		var i ListPriceTiersByItemRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.TargetDate,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.StoreCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTiersForCache = `-- name: ListPriceTiersForCache :many
SELECT id, chain_slug, retailer_item_id, price, discount_price,
       unit_price, anchor_price, target_date
FROM price_tiers
WHERE chain_slug = $1 AND target_date = $2
`

type ListPriceTiersForCacheParams struct {
	ChainSlug  string      `db:"chain_slug" json:"chain_slug"`
	TargetDate pgtype.Date `db:"target_date" json:"target_date"`
}

type ListPriceTiersForCacheRow struct {
	ID             string      `db:"id" json:"id"`
	ChainSlug      string      `db:"chain_slug" json:"chain_slug"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
}

// Get all price tiers for a chain at a specific date (for cache loading)
func (q *Queries) ListPriceTiersForCache(ctx context.Context, arg ListPriceTiersForCacheParams) ([]ListPriceTiersForCacheRow, error) {
	rows, err := q.db.Query(ctx, listPriceTiersForCache, arg.ChainSlug, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceTiersForCacheRow{}
	for rows.Next() {
		var i ListPriceTiersForCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.RetailerItemID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.TargetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorePricesViaTiers = `-- name: ListStorePricesViaTiers :many
SELECT
    spr.retailer_item_id,
    pt.id AS price_tier_id,
    pt.price,
    pt.discount_price,
    pt.unit_price,
    pt.anchor_price,
    spr.in_stock,
    spr.target_date
FROM store_price_refs spr
JOIN price_tiers pt ON pt.id = spr.price_tier_id
WHERE spr.target_date = $1 AND spr.store_id = $2
ORDER BY spr.retailer_item_id
`

type ListStorePricesViaTiersParams struct {
	TargetDate pgtype.Date `db:"target_date" json:"target_date"`
	StoreID    string      `db:"store_id" json:"store_id"`
}

type ListStorePricesViaTiersRow struct {
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string      `db:"price_tier_id" json:"price_tier_id"`
	Price          int32       `db:"price" json:"price"`
	DiscountPrice  pgtype.Int4 `db:"discount_price" json:"discount_price"`
	UnitPrice      pgtype.Int4 `db:"unit_price" json:"unit_price"`
	AnchorPrice    pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	InStock        pgtype.Bool `db:"in_stock" json:"in_stock"`
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
}

// Get all prices for a store via tier join at a specific date
func (q *Queries) ListStorePricesViaTiers(ctx context.Context, arg ListStorePricesViaTiersParams) ([]ListStorePricesViaTiersRow, error) {
	rows, err := q.db.Query(ctx, listStorePricesViaTiers, arg.TargetDate, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorePricesViaTiersRow{}
	for rows.Next() {
		var i ListStorePricesViaTiersRow
		if err := rows.Scan(
			&i.RetailerItemID,
			&i.PriceTierID,
			&i.Price,
			&i.DiscountPrice,
			&i.UnitPrice,
			&i.AnchorPrice,
			&i.InStock,
			&i.TargetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreRefsByChain = `-- name: ListStoreRefsByChain :many
SELECT
    spr.store_id,
    spr.retailer_item_id,
    spr.price_tier_id,
    spr.in_stock,
    spr.target_date
FROM store_price_refs spr
JOIN stores s ON s.id = spr.store_id
WHERE s.chain_slug = $1 AND spr.target_date = $2 AND s.status = 'active'
`

type ListStoreRefsByChainParams struct {
	ChainSlug  string      `db:"chain_slug" json:"chain_slug"`
	TargetDate pgtype.Date `db:"target_date" json:"target_date"`
}

type ListStoreRefsByChainRow struct {
	StoreID        string      `db:"store_id" json:"store_id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string      `db:"price_tier_id" json:"price_tier_id"`
	InStock        pgtype.Bool `db:"in_stock" json:"in_stock"`
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
}

// Get all store->tier references for a chain at a specific date
func (q *Queries) ListStoreRefsByChain(ctx context.Context, arg ListStoreRefsByChainParams) ([]ListStoreRefsByChainRow, error) {
	rows, err := q.db.Query(ctx, listStoreRefsByChain, arg.ChainSlug, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoreRefsByChainRow{}
	for rows.Next() {
		var i ListStoreRefsByChainRow
		if err := rows.Scan(
			&i.StoreID,
			&i.RetailerItemID,
			&i.PriceTierID,
			&i.InStock,
			&i.TargetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceTierLastSeen = `-- name: UpdatePriceTierLastSeen :exec
UPDATE price_tiers
SET last_seen_at = NOW()
WHERE id = $1
`

// Update last_seen_at timestamp for a price tier
func (q *Queries) UpdatePriceTierLastSeen(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updatePriceTierLastSeen, id)
	return err
}

const updatePriceTierStoreCount = `-- name: UpdatePriceTierStoreCount :exec
UPDATE price_tiers
SET store_count = (
    SELECT COUNT(DISTINCT store_id)
    FROM store_price_refs
    WHERE price_tier_id = $1
)
WHERE id = $1
`

// Recalculate store_count from store_price_refs
func (q *Queries) UpdatePriceTierStoreCount(ctx context.Context, priceTierID string) error {
	_, err := q.db.Exec(ctx, updatePriceTierStoreCount, priceTierID)
	return err
}

const upsertStorePriceRef = `-- name: UpsertStorePriceRef :exec
INSERT INTO store_price_refs (
    store_id, retailer_item_id, price_tier_id, in_stock, target_date, last_seen_at
) VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (target_date, store_id, retailer_item_id) DO UPDATE SET
    price_tier_id = EXCLUDED.price_tier_id,
    in_stock = EXCLUDED.in_stock,
    last_seen_at = NOW()
`

type UpsertStorePriceRefParams struct {
	StoreID        string      `db:"store_id" json:"store_id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	PriceTierID    string      `db:"price_tier_id" json:"price_tier_id"`
	InStock        pgtype.Bool `db:"in_stock" json:"in_stock"`
	TargetDate     pgtype.Date `db:"target_date" json:"target_date"`
}

// Insert or update a store->tier reference (scoped by date)
func (q *Queries) UpsertStorePriceRef(ctx context.Context, arg UpsertStorePriceRefParams) error {
	_, err := q.db.Exec(ctx, upsertStorePriceRef,
		arg.StoreID,
		arg.RetailerItemID,
		arg.PriceTierID,
		arg.InStock,
		arg.TargetDate,
	)
	return err
}
