// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchItems = `-- name: CountSearchItems :one
SELECT COUNT(DISTINCT ri.id)
FROM retailer_items ri
WHERE ri.name ILIKE '%' || $1::text || '%'
  AND ($2::text = '' OR ri.chain_slug = $2::text)
`

type CountSearchItemsParams struct {
	SearchQuery string `db:"search_query" json:"search_query"`
	ChainFilter string `db:"chain_filter" json:"chain_filter"`
}

// Counts items matching search query with optional chain filter
// Pass empty string for chain_slug to search all chains
func (q *Queries) CountSearchItems(ctx context.Context, arg CountSearchItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchItems, arg.SearchQuery, arg.ChainFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStorePrices = `-- name: CountStorePrices :one
SELECT COUNT(*)
FROM store_item_state sis
JOIN retailer_items ri ON sis.retailer_item_id = ri.id
JOIN stores s ON sis.store_id = s.id
WHERE s.id = $1 AND s.chain_slug = $2
`

type CountStorePricesParams struct {
	ID        string `db:"id" json:"id"`
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
}

func (q *Queries) CountStorePrices(ctx context.Context, arg CountStorePricesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStorePrices, arg.ID, arg.ChainSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listStorePricesWithDetails = `-- name: ListStorePricesWithDetails :many
SELECT
    ri.id as retailer_item_id,
    ri.name as item_name,
    ri.external_id as item_external_id,
    ri.brand,
    ri.unit,
    ri.unit_quantity,
    sis.current_price,
    sis.previous_price,
    sis.discount_price,
    TO_CHAR(sis.discount_start, 'YYYY-MM-DD HH24:MI:SS') as discount_start,
    TO_CHAR(sis.discount_end, 'YYYY-MM-DD HH24:MI:SS') as discount_end,
    sis.in_stock,
    sis.unit_price,
    sis.unit_price_base_quantity,
    sis.unit_price_base_unit,
    sis.lowest_price_30d,
    sis.anchor_price,
    sis.price_signature,
    TO_CHAR(sis.last_seen_at, 'YYYY-MM-DD HH24:MI:SS') as last_seen_at
FROM store_item_state sis
JOIN retailer_items ri ON sis.retailer_item_id = ri.id
JOIN stores s ON sis.store_id = s.id
WHERE s.id = $1 AND s.chain_slug = $2
ORDER BY ri.name
LIMIT $3 OFFSET $4
`

type ListStorePricesWithDetailsParams struct {
	ID        string `db:"id" json:"id"`
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

type ListStorePricesWithDetailsRow struct {
	RetailerItemID        string      `db:"retailer_item_id" json:"retailer_item_id"`
	ItemName              string      `db:"item_name" json:"item_name"`
	ItemExternalID        pgtype.Text `db:"item_external_id" json:"item_external_id"`
	Brand                 pgtype.Text `db:"brand" json:"brand"`
	Unit                  pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity          pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
	CurrentPrice          pgtype.Int4 `db:"current_price" json:"current_price"`
	PreviousPrice         pgtype.Int4 `db:"previous_price" json:"previous_price"`
	DiscountPrice         pgtype.Int4 `db:"discount_price" json:"discount_price"`
	DiscountStart         string      `db:"discount_start" json:"discount_start"`
	DiscountEnd           string      `db:"discount_end" json:"discount_end"`
	InStock               pgtype.Bool `db:"in_stock" json:"in_stock"`
	UnitPrice             pgtype.Int4 `db:"unit_price" json:"unit_price"`
	UnitPriceBaseQuantity pgtype.Text `db:"unit_price_base_quantity" json:"unit_price_base_quantity"`
	UnitPriceBaseUnit     pgtype.Text `db:"unit_price_base_unit" json:"unit_price_base_unit"`
	LowestPrice30d        pgtype.Int4 `db:"lowest_price_30d" json:"lowest_price_30d"`
	AnchorPrice           pgtype.Int4 `db:"anchor_price" json:"anchor_price"`
	PriceSignature        pgtype.Text `db:"price_signature" json:"price_signature"`
	LastSeenAt            string      `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) ListStorePricesWithDetails(ctx context.Context, arg ListStorePricesWithDetailsParams) ([]ListStorePricesWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listStorePricesWithDetails,
		arg.ID,
		arg.ChainSlug,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorePricesWithDetailsRow{}
	for rows.Next() {
		var i ListStorePricesWithDetailsRow
		if err := rows.Scan(
			&i.RetailerItemID,
			&i.ItemName,
			&i.ItemExternalID,
			&i.Brand,
			&i.Unit,
			&i.UnitQuantity,
			&i.CurrentPrice,
			&i.PreviousPrice,
			&i.DiscountPrice,
			&i.DiscountStart,
			&i.DiscountEnd,
			&i.InStock,
			&i.UnitPrice,
			&i.UnitPriceBaseQuantity,
			&i.UnitPriceBaseUnit,
			&i.LowestPrice30d,
			&i.AnchorPrice,
			&i.PriceSignature,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemsWithStats = `-- name: SearchItemsWithStats :many
SELECT DISTINCT
    ri.id,
    ri.chain_slug::text as chain_slug,
    ri.external_id,
    ri.name,
    ri.description,
    ri.brand,
    ri.category,
    ri.subcategory,
    ri.unit,
    ri.unit_quantity,
    ri.image_url,
    COALESCE(AVG(sis.current_price), 0)::int as avg_price,
    COUNT(DISTINCT sis.store_id)::int as store_count
FROM retailer_items ri
LEFT JOIN store_item_state sis ON ri.id = sis.retailer_item_id
WHERE ri.name ILIKE '%' || $1::text || '%'
  AND ($2::text = '' OR ri.chain_slug = $2::text)
GROUP BY ri.id, ri.chain_slug, ri.external_id, ri.name, ri.description,
         ri.brand, ri.category, ri.subcategory, ri.unit, ri.unit_quantity, ri.image_url
ORDER BY ri.name
LIMIT $3::int
`

type SearchItemsWithStatsParams struct {
	SearchQuery string `db:"search_query" json:"search_query"`
	ChainFilter string `db:"chain_filter" json:"chain_filter"`
	ResultLimit int32  `db:"result_limit" json:"result_limit"`
}

type SearchItemsWithStatsRow struct {
	ID           string      `db:"id" json:"id"`
	ChainSlug    string      `db:"chain_slug" json:"chain_slug"`
	ExternalID   pgtype.Text `db:"external_id" json:"external_id"`
	Name         string      `db:"name" json:"name"`
	Description  pgtype.Text `db:"description" json:"description"`
	Brand        pgtype.Text `db:"brand" json:"brand"`
	Category     pgtype.Text `db:"category" json:"category"`
	Subcategory  pgtype.Text `db:"subcategory" json:"subcategory"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
	ImageUrl     pgtype.Text `db:"image_url" json:"image_url"`
	AvgPrice     int32       `db:"avg_price" json:"avg_price"`
	StoreCount   int32       `db:"store_count" json:"store_count"`
}

// Search items by name with aggregated stats, optional chain filter
// Pass empty string for chain_slug to search all chains
func (q *Queries) SearchItemsWithStats(ctx context.Context, arg SearchItemsWithStatsParams) ([]SearchItemsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, searchItemsWithStats, arg.SearchQuery, arg.ChainFilter, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchItemsWithStatsRow{}
	for rows.Next() {
		var i SearchItemsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainSlug,
			&i.ExternalID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Unit,
			&i.UnitQuantity,
			&i.ImageUrl,
			&i.AvgPrice,
			&i.StoreCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
