// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retailer_item_barcodes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRetailerItemBarcode = `-- name: InsertRetailerItemBarcode :exec
INSERT INTO retailer_item_barcodes (id, retailer_item_id, barcode, is_primary, created_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT DO NOTHING
`

type InsertRetailerItemBarcodeParams struct {
	ID             string      `db:"id" json:"id"`
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	Barcode        string      `db:"barcode" json:"barcode"`
	IsPrimary      pgtype.Bool `db:"is_primary" json:"is_primary"`
}

func (q *Queries) InsertRetailerItemBarcode(ctx context.Context, arg InsertRetailerItemBarcodeParams) error {
	_, err := q.db.Exec(ctx, insertRetailerItemBarcode,
		arg.ID,
		arg.RetailerItemID,
		arg.Barcode,
		arg.IsPrimary,
	)
	return err
}
