// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: retailer_items.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRetailerItemByExternalId = `-- name: GetRetailerItemByExternalId :one
SELECT id FROM retailer_items
WHERE chain_slug = $1 AND external_id = $2
LIMIT 1
`

type GetRetailerItemByExternalIdParams struct {
	ChainSlug  pgtype.Text `db:"chain_slug" json:"chain_slug"`
	ExternalID pgtype.Text `db:"external_id" json:"external_id"`
}

func (q *Queries) GetRetailerItemByExternalId(ctx context.Context, arg GetRetailerItemByExternalIdParams) (string, error) {
	row := q.db.QueryRow(ctx, getRetailerItemByExternalId, arg.ChainSlug, arg.ExternalID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getRetailerItemDetails = `-- name: GetRetailerItemDetails :one
SELECT name, external_id, brand, unit, unit_quantity
FROM retailer_items
WHERE id = $1
`

type GetRetailerItemDetailsRow struct {
	Name         string      `db:"name" json:"name"`
	ExternalID   pgtype.Text `db:"external_id" json:"external_id"`
	Brand        pgtype.Text `db:"brand" json:"brand"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
}

func (q *Queries) GetRetailerItemDetails(ctx context.Context, id string) (GetRetailerItemDetailsRow, error) {
	row := q.db.QueryRow(ctx, getRetailerItemDetails, id)
	var i GetRetailerItemDetailsRow
	err := row.Scan(
		&i.Name,
		&i.ExternalID,
		&i.Brand,
		&i.Unit,
		&i.UnitQuantity,
	)
	return i, err
}

const getRetailerItemName = `-- name: GetRetailerItemName :one
SELECT name FROM retailer_items WHERE id = $1
`

func (q *Queries) GetRetailerItemName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getRetailerItemName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateRetailerItem = `-- name: UpdateRetailerItem :exec
UPDATE retailer_items
SET name = $1, description = $2, category = $3, subcategory = $4,
    brand = $5, unit = $6, unit_quantity = $7, image_url = $8
WHERE id = $9
`

type UpdateRetailerItemParams struct {
	Name         string      `db:"name" json:"name"`
	Description  pgtype.Text `db:"description" json:"description"`
	Category     pgtype.Text `db:"category" json:"category"`
	Subcategory  pgtype.Text `db:"subcategory" json:"subcategory"`
	Brand        pgtype.Text `db:"brand" json:"brand"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
	ImageUrl     pgtype.Text `db:"image_url" json:"image_url"`
	ID           string      `db:"id" json:"id"`
}

func (q *Queries) UpdateRetailerItem(ctx context.Context, arg UpdateRetailerItemParams) error {
	_, err := q.db.Exec(ctx, updateRetailerItem,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Subcategory,
		arg.Brand,
		arg.Unit,
		arg.UnitQuantity,
		arg.ImageUrl,
		arg.ID,
	)
	return err
}

const updateRetailerItemsArchiveId = `-- name: UpdateRetailerItemsArchiveId :exec
UPDATE retailer_items
SET archive_id = $1
WHERE id = ANY($2::text[])
`

type UpdateRetailerItemsArchiveIdParams struct {
	ArchiveID pgtype.Text `db:"archive_id" json:"archive_id"`
	Column2   []string    `db:"column_2" json:"column_2"`
}

func (q *Queries) UpdateRetailerItemsArchiveId(ctx context.Context, arg UpdateRetailerItemsArchiveIdParams) error {
	_, err := q.db.Exec(ctx, updateRetailerItemsArchiveId, arg.ArchiveID, arg.Column2)
	return err
}

const upsertRetailerItem = `-- name: UpsertRetailerItem :one
INSERT INTO retailer_items (
    id, chain_slug, external_id, name, description, category, subcategory,
    brand, unit, unit_quantity, image_url, archive_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW()
)
ON CONFLICT (chain_slug, external_id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    brand = EXCLUDED.brand,
    unit = EXCLUDED.unit,
    unit_quantity = EXCLUDED.unit_quantity,
    image_url = EXCLUDED.image_url,
    archive_id = EXCLUDED.archive_id
RETURNING id
`

type UpsertRetailerItemParams struct {
	ID           string      `db:"id" json:"id"`
	ChainSlug    pgtype.Text `db:"chain_slug" json:"chain_slug"`
	ExternalID   pgtype.Text `db:"external_id" json:"external_id"`
	Name         string      `db:"name" json:"name"`
	Description  pgtype.Text `db:"description" json:"description"`
	Category     pgtype.Text `db:"category" json:"category"`
	Subcategory  pgtype.Text `db:"subcategory" json:"subcategory"`
	Brand        pgtype.Text `db:"brand" json:"brand"`
	Unit         pgtype.Text `db:"unit" json:"unit"`
	UnitQuantity pgtype.Text `db:"unit_quantity" json:"unit_quantity"`
	ImageUrl     pgtype.Text `db:"image_url" json:"image_url"`
	ArchiveID    pgtype.Text `db:"archive_id" json:"archive_id"`
}

func (q *Queries) UpsertRetailerItem(ctx context.Context, arg UpsertRetailerItemParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertRetailerItem,
		arg.ID,
		arg.ChainSlug,
		arg.ExternalID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Subcategory,
		arg.Brand,
		arg.Unit,
		arg.UnitQuantity,
		arg.ImageUrl,
		arg.ArchiveID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
