// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkRunExists = `-- name: CheckRunExists :one
SELECT EXISTS(SELECT 1 FROM ingestion_runs WHERE id = $1)
`

func (q *Queries) CheckRunExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, checkRunExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createReprocessingRun = `-- name: CreateReprocessingRun :exec
INSERT INTO ingestion_runs (id, chain_slug, source, status, started_at, created_at)
VALUES ($1, $2, 'reprocess', 'running', NOW(), NOW())
`

type CreateReprocessingRunParams struct {
	ID        string `db:"id" json:"id"`
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
}

func (q *Queries) CreateReprocessingRun(ctx context.Context, arg CreateReprocessingRunParams) error {
	_, err := q.db.Exec(ctx, createReprocessingRun, arg.ID, arg.ChainSlug)
	return err
}

const createRerunRun = `-- name: CreateRerunRun :exec
INSERT INTO ingestion_runs (
    id, chain_slug, source, status, started_at, created_at,
    parent_run_id, rerun_type, rerun_target_id
) VALUES (
    $1, $2, 'rerun', 'pending', NOW(), NOW(),
    $3, $4, $5
)
`

type CreateRerunRunParams struct {
	ID            string      `db:"id" json:"id"`
	ChainSlug     string      `db:"chain_slug" json:"chain_slug"`
	ParentRunID   pgtype.Text `db:"parent_run_id" json:"parent_run_id"`
	RerunType     pgtype.Text `db:"rerun_type" json:"rerun_type"`
	RerunTargetID pgtype.Text `db:"rerun_target_id" json:"rerun_target_id"`
}

func (q *Queries) CreateRerunRun(ctx context.Context, arg CreateRerunRunParams) error {
	_, err := q.db.Exec(ctx, createRerunRun,
		arg.ID,
		arg.ChainSlug,
		arg.ParentRunID,
		arg.RerunType,
		arg.RerunTargetID,
	)
	return err
}

const deleteIngestionErrors = `-- name: DeleteIngestionErrors :exec
DELETE FROM ingestion_errors WHERE run_id = $1
`

func (q *Queries) DeleteIngestionErrors(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, deleteIngestionErrors, runID)
	return err
}

const deleteIngestionFiles = `-- name: DeleteIngestionFiles :exec
DELETE FROM ingestion_files WHERE run_id = $1
`

func (q *Queries) DeleteIngestionFiles(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, deleteIngestionFiles, runID)
	return err
}

const deleteIngestionRun = `-- name: DeleteIngestionRun :exec
DELETE FROM ingestion_runs WHERE id = $1
`

func (q *Queries) DeleteIngestionRun(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteIngestionRun, id)
	return err
}

const getIngestionRunById = `-- name: GetIngestionRunById :one
SELECT id, chain_slug, source, status, started_at, completed_at,
       total_files, processed_files, total_entries, processed_entries,
       error_count, metadata, created_at
FROM ingestion_runs
WHERE id = $1
`

type GetIngestionRunByIdRow struct {
	ID               string           `db:"id" json:"id"`
	ChainSlug        string           `db:"chain_slug" json:"chain_slug"`
	Source           string           `db:"source" json:"source"`
	Status           string           `db:"status" json:"status"`
	StartedAt        pgtype.Timestamp `db:"started_at" json:"started_at"`
	CompletedAt      pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	TotalFiles       pgtype.Int4      `db:"total_files" json:"total_files"`
	ProcessedFiles   pgtype.Int4      `db:"processed_files" json:"processed_files"`
	TotalEntries     pgtype.Int4      `db:"total_entries" json:"total_entries"`
	ProcessedEntries pgtype.Int4      `db:"processed_entries" json:"processed_entries"`
	ErrorCount       pgtype.Int4      `db:"error_count" json:"error_count"`
	Metadata         pgtype.Text      `db:"metadata" json:"metadata"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetIngestionRunById(ctx context.Context, id string) (GetIngestionRunByIdRow, error) {
	row := q.db.QueryRow(ctx, getIngestionRunById, id)
	var i GetIngestionRunByIdRow
	err := row.Scan(
		&i.ID,
		&i.ChainSlug,
		&i.Source,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.TotalEntries,
		&i.ProcessedEntries,
		&i.ErrorCount,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getRunChainSlug = `-- name: GetRunChainSlug :one
SELECT chain_slug FROM ingestion_runs WHERE id = $1
`

func (q *Queries) GetRunChainSlug(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getRunChainSlug, id)
	var chain_slug string
	err := row.Scan(&chain_slug)
	return chain_slug, err
}

const getRunStats = `-- name: GetRunStats :one
SELECT
    COUNT(*) as total_runs,
    COUNT(*) FILTER (WHERE status = 'completed') as completed,
    COUNT(*) FILTER (WHERE status = 'failed') as failed,
    COUNT(*) FILTER (WHERE status = 'running') as running,
    COUNT(*) FILTER (WHERE status = 'pending') as pending,
    COALESCE(SUM(total_files), 0) as total_files
FROM ingestion_runs
WHERE created_at >= $1 AND created_at <= $2
`

type GetRunStatsParams struct {
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `db:"created_at_2" json:"created_at_2"`
}

type GetRunStatsRow struct {
	TotalRuns  int64       `db:"total_runs" json:"total_runs"`
	Completed  int64       `db:"completed" json:"completed"`
	Failed     int64       `db:"failed" json:"failed"`
	Running    int64       `db:"running" json:"running"`
	Pending    int64       `db:"pending" json:"pending"`
	TotalFiles interface{} `db:"total_files" json:"total_files"`
}

func (q *Queries) GetRunStats(ctx context.Context, arg GetRunStatsParams) (GetRunStatsRow, error) {
	row := q.db.QueryRow(ctx, getRunStats, arg.CreatedAt, arg.CreatedAt_2)
	var i GetRunStatsRow
	err := row.Scan(
		&i.TotalRuns,
		&i.Completed,
		&i.Failed,
		&i.Running,
		&i.Pending,
		&i.TotalFiles,
	)
	return i, err
}
