// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store_item_state.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpsertStoreItemState = `-- name: BatchUpsertStoreItemState :exec
WITH new_values (store_id, retailer_item_id, current_price, previous_price, discount_price, discount_start, discount_end,
                 in_stock, unit_price, unit_price_base_quantity, unit_price_base_unit,
                 lowest_price_30d, anchor_price, anchor_price_as_of, price_signature) AS (
    SELECT UNNEST($1::text[]), UNNEST($2::text[]), UNNEST($3::int4[]), UNNEST($4::int4[]),
           UNNEST($5::int4[]), UNNEST($6::timestamptz[]), UNNEST($7::timestamptz[]),
           $8::boolean, UNNEST($9::int4[]), UNNEST($10::text[]), UNNEST($11::text[]),
           UNNEST($12::int4[]), UNNEST($13::int4[]), UNNEST($14::timestamptz[]), UNNEST($15::text[])
)
INSERT INTO store_item_state (
    store_id, retailer_item_id, current_price, previous_price,
    discount_price, discount_start, discount_end, in_stock,
    unit_price, unit_price_base_quantity, unit_price_base_unit,
    lowest_price_30d, anchor_price, anchor_price_as_of,
    price_signature, last_seen_at, updated_at
)
SELECT nv.store_id, nv.retailer_item_id, nv.current_price, nv.previous_price,
       nv.discount_price, nv.discount_start, nv.discount_end, nv.in_stock,
       nv.unit_price, nv.unit_price_base_quantity, nv.unit_price_base_unit,
       nv.lowest_price_30d, nv.anchor_price, nv.anchor_price_as_of,
       nv.price_signature, NOW(), NOW()
FROM new_values nv
ON CONFLICT (store_id, retailer_item_id) DO UPDATE SET
    previous_price = store_item_state.current_price,
    current_price = EXCLUDED.current_price,
    discount_price = EXCLUDED.discount_price,
    discount_start = EXCLUDED.discount_start,
    discount_end = EXCLUDED.discount_end,
    unit_price = EXCLUDED.unit_price,
    unit_price_base_quantity = EXCLUDED.unit_price_base_quantity,
    unit_price_base_unit = EXCLUDED.unit_price_base_unit,
    lowest_price_30d = EXCLUDED.lowest_price_30d,
    anchor_price = EXCLUDED.anchor_price,
    anchor_price_as_of = EXCLUDED.anchor_price_as_of,
    price_signature = EXCLUDED.price_signature,
    last_seen_at = NOW(),
    updated_at = NOW()
`

type BatchUpsertStoreItemStateParams struct {
	Column1  []string             `db:"column_1" json:"column_1"`
	Column2  []string             `db:"column_2" json:"column_2"`
	Column3  []int32              `db:"column_3" json:"column_3"`
	Column4  []int32              `db:"column_4" json:"column_4"`
	Column5  []int32              `db:"column_5" json:"column_5"`
	Column6  []pgtype.Timestamptz `db:"column_6" json:"column_6"`
	Column7  []pgtype.Timestamptz `db:"column_7" json:"column_7"`
	Column8  bool                 `db:"column_8" json:"column_8"`
	Column9  []int32              `db:"column_9" json:"column_9"`
	Column10 []string             `db:"column_10" json:"column_10"`
	Column11 []string             `db:"column_11" json:"column_11"`
	Column12 []int32              `db:"column_12" json:"column_12"`
	Column13 []int32              `db:"column_13" json:"column_13"`
	Column14 []pgtype.Timestamptz `db:"column_14" json:"column_14"`
	Column15 []string             `db:"column_15" json:"column_15"`
}

func (q *Queries) BatchUpsertStoreItemState(ctx context.Context, arg BatchUpsertStoreItemStateParams) error {
	_, err := q.db.Exec(ctx, batchUpsertStoreItemState,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
	)
	return err
}

const getStorePreviousPrice = `-- name: GetStorePreviousPrice :one
SELECT current_price
FROM store_item_state
WHERE store_id = $1 AND retailer_item_id = $2
`

type GetStorePreviousPriceParams struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

func (q *Queries) GetStorePreviousPrice(ctx context.Context, arg GetStorePreviousPriceParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getStorePreviousPrice, arg.StoreID, arg.RetailerItemID)
	var current_price pgtype.Int4
	err := row.Scan(&current_price)
	return current_price, err
}

const getStorePreviousPricesBatch = `-- name: GetStorePreviousPricesBatch :many
SELECT retailer_item_id, current_price
FROM store_item_state
WHERE store_id = $1 AND retailer_item_id = ANY($2::text[])
`

type GetStorePreviousPricesBatchParams struct {
	StoreID string   `db:"store_id" json:"store_id"`
	Column2 []string `db:"column_2" json:"column_2"`
}

type GetStorePreviousPricesBatchRow struct {
	RetailerItemID string      `db:"retailer_item_id" json:"retailer_item_id"`
	CurrentPrice   pgtype.Int4 `db:"current_price" json:"current_price"`
}

func (q *Queries) GetStorePreviousPricesBatch(ctx context.Context, arg GetStorePreviousPricesBatchParams) ([]GetStorePreviousPricesBatchRow, error) {
	rows, err := q.db.Query(ctx, getStorePreviousPricesBatch, arg.StoreID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStorePreviousPricesBatchRow{}
	for rows.Next() {
		var i GetStorePreviousPricesBatchRow
		if err := rows.Scan(&i.RetailerItemID, &i.CurrentPrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStoreItemState = `-- name: UpsertStoreItemState :one
INSERT INTO store_item_state (
    store_id, retailer_item_id, current_price, previous_price,
    discount_price, discount_start, discount_end, in_stock,
    unit_price, unit_price_base_quantity, unit_price_base_unit,
    lowest_price_30d, anchor_price, anchor_price_as_of,
    price_signature, last_seen_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, true,
    $8, $9, $10, $11, $12, $13, $14, NOW(), NOW()
)
ON CONFLICT (store_id, retailer_item_id) DO UPDATE SET
    previous_price = store_item_state.current_price,
    current_price = EXCLUDED.current_price,
    discount_price = EXCLUDED.discount_price,
    discount_start = EXCLUDED.discount_start,
    discount_end = EXCLUDED.discount_end,
    unit_price = EXCLUDED.unit_price,
    unit_price_base_quantity = EXCLUDED.unit_price_base_quantity,
    unit_price_base_unit = EXCLUDED.unit_price_base_unit,
    lowest_price_30d = EXCLUDED.lowest_price_30d,
    anchor_price = EXCLUDED.anchor_price,
    anchor_price_as_of = EXCLUDED.anchor_price_as_of,
    price_signature = EXCLUDED.price_signature,
    last_seen_at = NOW(),
    updated_at = NOW()
RETURNING previous_price, current_price
`

type UpsertStoreItemStateParams struct {
	StoreID               string           `db:"store_id" json:"store_id"`
	RetailerItemID        string           `db:"retailer_item_id" json:"retailer_item_id"`
	CurrentPrice          pgtype.Int4      `db:"current_price" json:"current_price"`
	PreviousPrice         pgtype.Int4      `db:"previous_price" json:"previous_price"`
	DiscountPrice         pgtype.Int4      `db:"discount_price" json:"discount_price"`
	DiscountStart         pgtype.Timestamp `db:"discount_start" json:"discount_start"`
	DiscountEnd           pgtype.Timestamp `db:"discount_end" json:"discount_end"`
	UnitPrice             pgtype.Int4      `db:"unit_price" json:"unit_price"`
	UnitPriceBaseQuantity pgtype.Text      `db:"unit_price_base_quantity" json:"unit_price_base_quantity"`
	UnitPriceBaseUnit     pgtype.Text      `db:"unit_price_base_unit" json:"unit_price_base_unit"`
	LowestPrice30d        pgtype.Int4      `db:"lowest_price_30d" json:"lowest_price_30d"`
	AnchorPrice           pgtype.Int4      `db:"anchor_price" json:"anchor_price"`
	AnchorPriceAsOf       pgtype.Timestamp `db:"anchor_price_as_of" json:"anchor_price_as_of"`
	PriceSignature        pgtype.Text      `db:"price_signature" json:"price_signature"`
}

type UpsertStoreItemStateRow struct {
	PreviousPrice pgtype.Int4 `db:"previous_price" json:"previous_price"`
	CurrentPrice  pgtype.Int4 `db:"current_price" json:"current_price"`
}

func (q *Queries) UpsertStoreItemState(ctx context.Context, arg UpsertStoreItemStateParams) (UpsertStoreItemStateRow, error) {
	row := q.db.QueryRow(ctx, upsertStoreItemState,
		arg.StoreID,
		arg.RetailerItemID,
		arg.CurrentPrice,
		arg.PreviousPrice,
		arg.DiscountPrice,
		arg.DiscountStart,
		arg.DiscountEnd,
		arg.UnitPrice,
		arg.UnitPriceBaseQuantity,
		arg.UnitPriceBaseUnit,
		arg.LowestPrice30d,
		arg.AnchorPrice,
		arg.AnchorPriceAsOf,
		arg.PriceSignature,
	)
	var i UpsertStoreItemStateRow
	err := row.Scan(&i.PreviousPrice, &i.CurrentPrice)
	return i, err
}
