// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stores.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :exec
INSERT INTO stores (id, chain_slug, name, address, city, postal_code, is_virtual, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, false, 'pending', NOW(), NOW())
ON CONFLICT (id) DO NOTHING
`

type CreateStoreParams struct {
	ID         string      `db:"id" json:"id"`
	ChainSlug  string      `db:"chain_slug" json:"chain_slug"`
	Name       string      `db:"name" json:"name"`
	Address    pgtype.Text `db:"address" json:"address"`
	City       pgtype.Text `db:"city" json:"city"`
	PostalCode pgtype.Text `db:"postal_code" json:"postal_code"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) error {
	_, err := q.db.Exec(ctx, createStore,
		arg.ID,
		arg.ChainSlug,
		arg.Name,
		arg.Address,
		arg.City,
		arg.PostalCode,
	)
	return err
}

const createStoreIdentifier = `-- name: CreateStoreIdentifier :exec
INSERT INTO store_identifiers (id, store_id, type, value, created_at)
VALUES ($1, $2, 'filename_code', $3, NOW())
ON CONFLICT (id) DO NOTHING
`

type CreateStoreIdentifierParams struct {
	ID      string `db:"id" json:"id"`
	StoreID string `db:"store_id" json:"store_id"`
	Value   string `db:"value" json:"value"`
}

func (q *Queries) CreateStoreIdentifier(ctx context.Context, arg CreateStoreIdentifierParams) error {
	_, err := q.db.Exec(ctx, createStoreIdentifier, arg.ID, arg.StoreID, arg.Value)
	return err
}

const getStoreByIdentifier = `-- name: GetStoreByIdentifier :one
SELECT si.id
FROM stores si
JOIN store_identifiers sident ON sident.store_id = si.id
WHERE si.chain_slug = $1
  AND sident.type = 'filename_code'
  AND sident.value = $2
LIMIT 1
`

type GetStoreByIdentifierParams struct {
	ChainSlug string `db:"chain_slug" json:"chain_slug"`
	Value     string `db:"value" json:"value"`
}

func (q *Queries) GetStoreByIdentifier(ctx context.Context, arg GetStoreByIdentifierParams) (string, error) {
	row := q.db.QueryRow(ctx, getStoreByIdentifier, arg.ChainSlug, arg.Value)
	var id string
	err := row.Scan(&id)
	return id, err
}
