// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: store_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIngestionStoreStatsByFileID = `-- name: CountIngestionStoreStatsByFileID :one
SELECT COUNT(*)
FROM ingestion_store_stats
WHERE file_id = $1
`

func (q *Queries) CountIngestionStoreStatsByFileID(ctx context.Context, fileID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestionStoreStatsByFileID, fileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIngestionStoreStatsByRunID = `-- name: CountIngestionStoreStatsByRunID :one
SELECT COUNT(*)
FROM (
    SELECT 1
    FROM ingestion_store_stats
    WHERE run_id = $1
    GROUP BY store_id, store_identifier
) AS store_counts
`

func (q *Queries) CountIngestionStoreStatsByRunID(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestionStoreStatsByRunID, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngestionStoreStats = `-- name: CreateIngestionStoreStats :exec
INSERT INTO ingestion_store_stats (
    run_id, file_id, store_id, store_identifier,
    row_count, persisted_count, price_changes, failed_rows, warning_rows, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, NOW()
)
`

type CreateIngestionStoreStatsParams struct {
	RunID           string `db:"run_id" json:"run_id"`
	FileID          int64  `db:"file_id" json:"file_id"`
	StoreID         string `db:"store_id" json:"store_id"`
	StoreIdentifier string `db:"store_identifier" json:"store_identifier"`
	RowCount        int32  `db:"row_count" json:"row_count"`
	PersistedCount  int32  `db:"persisted_count" json:"persisted_count"`
	PriceChanges    int32  `db:"price_changes" json:"price_changes"`
	FailedRows      int32  `db:"failed_rows" json:"failed_rows"`
	WarningRows     int32  `db:"warning_rows" json:"warning_rows"`
}

func (q *Queries) CreateIngestionStoreStats(ctx context.Context, arg CreateIngestionStoreStatsParams) error {
	_, err := q.db.Exec(ctx, createIngestionStoreStats,
		arg.RunID,
		arg.FileID,
		arg.StoreID,
		arg.StoreIdentifier,
		arg.RowCount,
		arg.PersistedCount,
		arg.PriceChanges,
		arg.FailedRows,
		arg.WarningRows,
	)
	return err
}

const getIngestionFileStatsSummary = `-- name: GetIngestionFileStatsSummary :one
SELECT
    COALESCE(SUM(row_count), 0)::bigint AS row_count,
    COALESCE(SUM(persisted_count), 0)::bigint AS persisted_count,
    COALESCE(SUM(price_changes), 0)::bigint AS price_changes,
    COALESCE(SUM(failed_rows), 0)::bigint AS failed_rows,
    COALESCE(SUM(warning_rows), 0)::bigint AS warning_rows,
    COUNT(DISTINCT store_id) AS store_count
FROM ingestion_store_stats
WHERE file_id = $1
`

type GetIngestionFileStatsSummaryRow struct {
	RowCount       int64 `db:"row_count" json:"row_count"`
	PersistedCount int64 `db:"persisted_count" json:"persisted_count"`
	PriceChanges   int64 `db:"price_changes" json:"price_changes"`
	FailedRows     int64 `db:"failed_rows" json:"failed_rows"`
	WarningRows    int64 `db:"warning_rows" json:"warning_rows"`
	StoreCount     int64 `db:"store_count" json:"store_count"`
}

func (q *Queries) GetIngestionFileStatsSummary(ctx context.Context, fileID int64) (GetIngestionFileStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getIngestionFileStatsSummary, fileID)
	var i GetIngestionFileStatsSummaryRow
	err := row.Scan(
		&i.RowCount,
		&i.PersistedCount,
		&i.PriceChanges,
		&i.FailedRows,
		&i.WarningRows,
		&i.StoreCount,
	)
	return i, err
}

const getIngestionRunStatsSummary = `-- name: GetIngestionRunStatsSummary :one
SELECT
    COALESCE(SUM(row_count), 0)::bigint AS row_count,
    COALESCE(SUM(persisted_count), 0)::bigint AS persisted_count,
    COALESCE(SUM(price_changes), 0)::bigint AS price_changes,
    COALESCE(SUM(failed_rows), 0)::bigint AS failed_rows,
    COALESCE(SUM(warning_rows), 0)::bigint AS warning_rows,
    COUNT(DISTINCT store_id) AS store_count,
    COUNT(DISTINCT file_id) AS file_count
FROM ingestion_store_stats
WHERE run_id = $1
`

type GetIngestionRunStatsSummaryRow struct {
	RowCount       int64 `db:"row_count" json:"row_count"`
	PersistedCount int64 `db:"persisted_count" json:"persisted_count"`
	PriceChanges   int64 `db:"price_changes" json:"price_changes"`
	FailedRows     int64 `db:"failed_rows" json:"failed_rows"`
	WarningRows    int64 `db:"warning_rows" json:"warning_rows"`
	StoreCount     int64 `db:"store_count" json:"store_count"`
	FileCount      int64 `db:"file_count" json:"file_count"`
}

func (q *Queries) GetIngestionRunStatsSummary(ctx context.Context, runID string) (GetIngestionRunStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getIngestionRunStatsSummary, runID)
	var i GetIngestionRunStatsSummaryRow
	err := row.Scan(
		&i.RowCount,
		&i.PersistedCount,
		&i.PriceChanges,
		&i.FailedRows,
		&i.WarningRows,
		&i.StoreCount,
		&i.FileCount,
	)
	return i, err
}

const listIngestionStoreStatsByFileID = `-- name: ListIngestionStoreStatsByFileID :many
SELECT
    iss.id,
    iss.run_id,
    iss.file_id,
    iss.store_id,
    s.name AS store_name,
    s.city AS store_city,
    iss.store_identifier,
    iss.row_count,
    iss.persisted_count,
    iss.price_changes,
    iss.failed_rows,
    iss.warning_rows,
    iss.created_at
FROM ingestion_store_stats iss
JOIN stores s ON s.id = iss.store_id
WHERE iss.file_id = $1
ORDER BY iss.persisted_count DESC
LIMIT $2 OFFSET $3
`

type ListIngestionStoreStatsByFileIDParams struct {
	FileID int64 `db:"file_id" json:"file_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListIngestionStoreStatsByFileIDRow struct {
	ID              int64            `db:"id" json:"id"`
	RunID           string           `db:"run_id" json:"run_id"`
	FileID          int64            `db:"file_id" json:"file_id"`
	StoreID         string           `db:"store_id" json:"store_id"`
	StoreName       string           `db:"store_name" json:"store_name"`
	StoreCity       pgtype.Text      `db:"store_city" json:"store_city"`
	StoreIdentifier string           `db:"store_identifier" json:"store_identifier"`
	RowCount        int32            `db:"row_count" json:"row_count"`
	PersistedCount  int32            `db:"persisted_count" json:"persisted_count"`
	PriceChanges    int32            `db:"price_changes" json:"price_changes"`
	FailedRows      int32            `db:"failed_rows" json:"failed_rows"`
	WarningRows     int32            `db:"warning_rows" json:"warning_rows"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) ListIngestionStoreStatsByFileID(ctx context.Context, arg ListIngestionStoreStatsByFileIDParams) ([]ListIngestionStoreStatsByFileIDRow, error) {
	rows, err := q.db.Query(ctx, listIngestionStoreStatsByFileID, arg.FileID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngestionStoreStatsByFileIDRow{}
	for rows.Next() {
		var i ListIngestionStoreStatsByFileIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FileID,
			&i.StoreID,
			&i.StoreName,
			&i.StoreCity,
			&i.StoreIdentifier,
			&i.RowCount,
			&i.PersistedCount,
			&i.PriceChanges,
			&i.FailedRows,
			&i.WarningRows,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestionStoreStatsByRunID = `-- name: ListIngestionStoreStatsByRunID :many
SELECT
    s.id AS store_id,
    s.name AS store_name,
    s.city AS store_city,
    iss.store_identifier,
    SUM(iss.row_count) AS row_count,
    SUM(iss.persisted_count) AS persisted_count,
    SUM(iss.price_changes) AS price_changes,
    SUM(iss.failed_rows) AS failed_rows,
    SUM(iss.warning_rows) AS warning_rows,
    COUNT(DISTINCT iss.file_id) AS file_count
FROM ingestion_store_stats iss
JOIN stores s ON s.id = iss.store_id
WHERE iss.run_id = $1
GROUP BY s.id, s.name, s.city, iss.store_identifier
ORDER BY persisted_count DESC
LIMIT $2 OFFSET $3
`

type ListIngestionStoreStatsByRunIDParams struct {
	RunID  string `db:"run_id" json:"run_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type ListIngestionStoreStatsByRunIDRow struct {
	StoreID         string      `db:"store_id" json:"store_id"`
	StoreName       string      `db:"store_name" json:"store_name"`
	StoreCity       pgtype.Text `db:"store_city" json:"store_city"`
	StoreIdentifier string      `db:"store_identifier" json:"store_identifier"`
	RowCount        int64       `db:"row_count" json:"row_count"`
	PersistedCount  int64       `db:"persisted_count" json:"persisted_count"`
	PriceChanges    int64       `db:"price_changes" json:"price_changes"`
	FailedRows      int64       `db:"failed_rows" json:"failed_rows"`
	WarningRows     int64       `db:"warning_rows" json:"warning_rows"`
	FileCount       int64       `db:"file_count" json:"file_count"`
}

func (q *Queries) ListIngestionStoreStatsByRunID(ctx context.Context, arg ListIngestionStoreStatsByRunIDParams) ([]ListIngestionStoreStatsByRunIDRow, error) {
	rows, err := q.db.Query(ctx, listIngestionStoreStatsByRunID, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngestionStoreStatsByRunIDRow{}
	for rows.Next() {
		var i ListIngestionStoreStatsByRunIDRow
		if err := rows.Scan(
			&i.StoreID,
			&i.StoreName,
			&i.StoreCity,
			&i.StoreIdentifier,
			&i.RowCount,
			&i.PersistedCount,
			&i.PriceChanges,
			&i.FailedRows,
			&i.WarningRows,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
