// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: store_item_state.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStorePreviousPrice = `-- name: GetStorePreviousPrice :one
SELECT current_price
FROM store_item_state
WHERE store_id = $1 AND retailer_item_id = $2
`

type GetStorePreviousPriceParams struct {
	StoreID        string `db:"store_id" json:"store_id"`
	RetailerItemID string `db:"retailer_item_id" json:"retailer_item_id"`
}

func (q *Queries) GetStorePreviousPrice(ctx context.Context, arg GetStorePreviousPriceParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getStorePreviousPrice, arg.StoreID, arg.RetailerItemID)
	var current_price pgtype.Int4
	err := row.Scan(&current_price)
	return current_price, err
}

const upsertStoreItemState = `-- name: UpsertStoreItemState :one
INSERT INTO store_item_state (
    store_id, retailer_item_id, current_price, previous_price,
    discount_price, discount_start, discount_end, in_stock,
    unit_price, unit_price_base_quantity, unit_price_base_unit,
    lowest_price_30d, anchor_price, anchor_price_as_of,
    price_signature, last_seen_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, true,
    $8, $9, $10, $11, $12, $13, $14, NOW(), NOW()
)
ON CONFLICT (store_id, retailer_item_id) DO UPDATE SET
    previous_price = store_item_state.current_price,
    current_price = EXCLUDED.current_price,
    discount_price = EXCLUDED.discount_price,
    discount_start = EXCLUDED.discount_start,
    discount_end = EXCLUDED.discount_end,
    unit_price = EXCLUDED.unit_price,
    unit_price_base_quantity = EXCLUDED.unit_price_base_quantity,
    unit_price_base_unit = EXCLUDED.unit_price_base_unit,
    lowest_price_30d = EXCLUDED.lowest_price_30d,
    anchor_price = EXCLUDED.anchor_price,
    anchor_price_as_of = EXCLUDED.anchor_price_as_of,
    price_signature = EXCLUDED.price_signature,
    last_seen_at = NOW(),
    updated_at = NOW()
RETURNING previous_price, current_price
`

type UpsertStoreItemStateParams struct {
	StoreID               string           `db:"store_id" json:"store_id"`
	RetailerItemID        string           `db:"retailer_item_id" json:"retailer_item_id"`
	CurrentPrice          pgtype.Int4      `db:"current_price" json:"current_price"`
	PreviousPrice         pgtype.Int4      `db:"previous_price" json:"previous_price"`
	DiscountPrice         pgtype.Int4      `db:"discount_price" json:"discount_price"`
	DiscountStart         pgtype.Timestamp `db:"discount_start" json:"discount_start"`
	DiscountEnd           pgtype.Timestamp `db:"discount_end" json:"discount_end"`
	UnitPrice             pgtype.Int4      `db:"unit_price" json:"unit_price"`
	UnitPriceBaseQuantity pgtype.Text      `db:"unit_price_base_quantity" json:"unit_price_base_quantity"`
	UnitPriceBaseUnit     pgtype.Text      `db:"unit_price_base_unit" json:"unit_price_base_unit"`
	LowestPrice30d        pgtype.Int4      `db:"lowest_price_30d" json:"lowest_price_30d"`
	AnchorPrice           pgtype.Int4      `db:"anchor_price" json:"anchor_price"`
	AnchorPriceAsOf       pgtype.Timestamp `db:"anchor_price_as_of" json:"anchor_price_as_of"`
	PriceSignature        pgtype.Text      `db:"price_signature" json:"price_signature"`
}

type UpsertStoreItemStateRow struct {
	PreviousPrice pgtype.Int4 `db:"previous_price" json:"previous_price"`
	CurrentPrice  pgtype.Int4 `db:"current_price" json:"current_price"`
}

func (q *Queries) UpsertStoreItemState(ctx context.Context, arg UpsertStoreItemStateParams) (UpsertStoreItemStateRow, error) {
	row := q.db.QueryRow(ctx, upsertStoreItemState,
		arg.StoreID,
		arg.RetailerItemID,
		arg.CurrentPrice,
		arg.PreviousPrice,
		arg.DiscountPrice,
		arg.DiscountStart,
		arg.DiscountEnd,
		arg.UnitPrice,
		arg.UnitPriceBaseQuantity,
		arg.UnitPriceBaseUnit,
		arg.LowestPrice30d,
		arg.AnchorPrice,
		arg.AnchorPriceAsOf,
		arg.PriceSignature,
	)
	var i UpsertStoreItemStateRow
	err := row.Scan(&i.PreviousPrice, &i.CurrentPrice)
	return i, err
}
