// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taskqueue.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTask = `-- name: CancelTask :exec
UPDATE task_queue
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND status IN ('pending', 'claimed')
`

func (q *Queries) CancelTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, cancelTask, id)
	return err
}

const countTasksByStatus = `-- name: CountTasksByStatus :one
SELECT COUNT(*) FROM task_queue WHERE status = $1
`

func (q *Queries) CountTasksByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTask = `-- name: GetTask :one
SELECT id, task_type, payload, priority, status, scheduled_for, started_at, completed_at, failed_at, worker_id, retry_count, max_retries, error_message, created_at, updated_at FROM task_queue WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (TaskQueue, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i TaskQueue
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.WorkerID,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, task_type, payload, priority, status, scheduled_for, started_at, completed_at, failed_at, worker_id, retry_count, max_retries, error_message, created_at, updated_at FROM task_queue
WHERE status = 'pending'
  AND scheduled_for <= NOW()
ORDER BY priority DESC, scheduled_for ASC
LIMIT $1
`

func (q *Queries) ListPendingTasks(ctx context.Context, limit int32) ([]TaskQueue, error) {
	rows, err := q.db.Query(ctx, listPendingTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueue{}
	for rows.Next() {
		var i TaskQueue
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.WorkerID,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, task_type, payload, priority, status, scheduled_for, started_at, completed_at, failed_at, worker_id, retry_count, max_retries, error_message, created_at, updated_at FROM task_queue
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByStatusParams struct {
	Status string `db:"status" json:"status"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]TaskQueue, error) {
	rows, err := q.db.Query(ctx, listTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueue{}
	for rows.Next() {
		var i TaskQueue
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.WorkerID,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleTask = `-- name: ScheduleTask :one
INSERT INTO task_queue (task_type, payload, priority, scheduled_for, max_retries)
VALUES ($1, $2, $3, COALESCE($4, NOW()), $5)
RETURNING id
`

type ScheduleTaskParams struct {
	TaskType   string      `db:"task_type" json:"task_type"`
	Payload    []byte      `db:"payload" json:"payload"`
	Priority   pgtype.Int4 `db:"priority" json:"priority"`
	Column4    interface{} `db:"column_4" json:"column_4"`
	MaxRetries pgtype.Int4 `db:"max_retries" json:"max_retries"`
}

func (q *Queries) ScheduleTask(ctx context.Context, arg ScheduleTaskParams) (string, error) {
	row := q.db.QueryRow(ctx, scheduleTask,
		arg.TaskType,
		arg.Payload,
		arg.Priority,
		arg.Column4,
		arg.MaxRetries,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setTaskProcessing = `-- name: SetTaskProcessing :exec
UPDATE task_queue
SET status = 'processing', updated_at = NOW()
WHERE id = $1 AND status = 'claimed'
`

func (q *Queries) SetTaskProcessing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setTaskProcessing, id)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE task_queue
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     string `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
