// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taskqueue.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kosarica/price-service/internal/jsonb"
)

const cancelTask = `-- name: CancelTask :exec
UPDATE task_queue
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND status IN ('pending', 'claimed')
`

func (q *Queries) CancelTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, cancelTask, id)
	return err
}

const claimTasks = `-- name: ClaimTasks :many
SELECT claim_tasks FROM claim_tasks($1, $2, $3)
`

type ClaimTasksParams struct {
	PWorkerID  string `db:"p_worker_id" json:"p_worker_id"`
	PTaskTypes string `db:"p_task_types" json:"p_task_types"`
	PMaxTasks  int32  `db:"p_max_tasks" json:"p_max_tasks"`
}

func (q *Queries) ClaimTasks(ctx context.Context, arg ClaimTasksParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, claimTasks, arg.PWorkerID, arg.PTaskTypes, arg.PMaxTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var claim_tasks interface{}
		if err := rows.Scan(&claim_tasks); err != nil {
			return nil, err
		}
		items = append(items, claim_tasks)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupOldTasksFunc = `-- name: CleanupOldTasksFunc :one
SELECT cleanup_old_tasks($1)
`

func (q *Queries) CleanupOldTasksFunc(ctx context.Context, pDaysToKeep int32) (int32, error) {
	row := q.db.QueryRow(ctx, cleanupOldTasksFunc, pDaysToKeep)
	var cleanup_old_tasks int32
	err := row.Scan(&cleanup_old_tasks)
	return cleanup_old_tasks, err
}

const completeTaskFunc = `-- name: CompleteTaskFunc :one
SELECT complete_task($1, $2::jsonb)
`

type CompleteTaskFuncParams struct {
	PTaskID string `db:"p_task_id" json:"p_task_id"`
	Column2 []byte `db:"column_2" json:"column_2"`
}

func (q *Queries) CompleteTaskFunc(ctx context.Context, arg CompleteTaskFuncParams) (bool, error) {
	row := q.db.QueryRow(ctx, completeTaskFunc, arg.PTaskID, arg.Column2)
	var complete_task bool
	err := row.Scan(&complete_task)
	return complete_task, err
}

const countTasksByStatus = `-- name: CountTasksByStatus :one
SELECT COUNT(*) FROM task_queue WHERE status = $1
`

func (q *Queries) CountTasksByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failTaskFunc = `-- name: FailTaskFunc :one
SELECT fail_task($1, $2, $3)
`

type FailTaskFuncParams struct {
	PTaskID       string `db:"p_task_id" json:"p_task_id"`
	PErrorMessage string `db:"p_error_message" json:"p_error_message"`
	PRetry        bool   `db:"p_retry" json:"p_retry"`
}

func (q *Queries) FailTaskFunc(ctx context.Context, arg FailTaskFuncParams) (bool, error) {
	row := q.db.QueryRow(ctx, failTaskFunc, arg.PTaskID, arg.PErrorMessage, arg.PRetry)
	var fail_task bool
	err := row.Scan(&fail_task)
	return fail_task, err
}

const getTask = `-- name: GetTask :one
SELECT id, task_type, payload, priority, status, scheduled_for, started_at, completed_at, failed_at, worker_id, retry_count, max_retries, error_message, created_at, updated_at FROM task_queue WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (TaskQueue, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i TaskQueue
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.WorkerID,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, task_type, payload, priority, status, scheduled_for, started_at, completed_at, failed_at, worker_id, retry_count, max_retries, error_message, created_at, updated_at FROM task_queue
WHERE status = 'pending'
  AND scheduled_for <= NOW()
ORDER BY priority DESC, scheduled_for ASC
LIMIT $1
`

func (q *Queries) ListPendingTasks(ctx context.Context, limit int32) ([]TaskQueue, error) {
	rows, err := q.db.Query(ctx, listPendingTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueue{}
	for rows.Next() {
		var i TaskQueue
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.WorkerID,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, task_type, payload, priority, status, scheduled_for, started_at, completed_at, failed_at, worker_id, retry_count, max_retries, error_message, created_at, updated_at FROM task_queue
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByStatusParams struct {
	Status string `db:"status" json:"status"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]TaskQueue, error) {
	rows, err := q.db.Query(ctx, listTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueue{}
	for rows.Next() {
		var i TaskQueue
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.WorkerID,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleTask = `-- name: ScheduleTask :one
INSERT INTO task_queue (task_type, payload, priority, scheduled_for, max_retries)
VALUES ($1, $2, $3, COALESCE($4, NOW()), $5)
RETURNING id
`

type ScheduleTaskParams struct {
	TaskType   string                 `db:"task_type" json:"task_type"`
	Payload    jsonb.TaskQueuePayload `db:"payload" json:"payload"`
	Priority   pgtype.Int4            `db:"priority" json:"priority"`
	Column4    interface{}            `db:"column_4" json:"column_4"`
	MaxRetries pgtype.Int4            `db:"max_retries" json:"max_retries"`
}

func (q *Queries) ScheduleTask(ctx context.Context, arg ScheduleTaskParams) (string, error) {
	row := q.db.QueryRow(ctx, scheduleTask,
		arg.TaskType,
		arg.Payload,
		arg.Priority,
		arg.Column4,
		arg.MaxRetries,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setTaskProcessing = `-- name: SetTaskProcessing :exec
UPDATE task_queue
SET status = 'processing', updated_at = NOW()
WHERE id = $1 AND status = 'claimed'
`

func (q *Queries) SetTaskProcessing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setTaskProcessing, id)
	return err
}

const setTaskProcessingAny = `-- name: SetTaskProcessingAny :exec
UPDATE task_queue
SET status = 'processing', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetTaskProcessingAny(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setTaskProcessingAny, id)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE task_queue
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     string `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
